<script setup>
import {ref,computed,nextTick,onBeforeUnmount} from 'vue';
import {useTheme} from 'vuetify';
import MediaRow from './MediaRow.vue';
import Episode from './Episode.vue';
import Scheme from './Scheme.vue';
import {media,exampleScheme,blankScheme} from './model.mjs';
const theme=useTheme(),section=ref('subscriptions'),selected=ref(''),query=ref(''),filter=ref('all'),episodeFilter=ref('all'),detailTab=ref('episodes');
const listPosition=ref(0),listFocus=ref(null),scroll=ref(null),scheme=ref(null),leave=ref(null),notice=ref(''),candidateOpen=ref(false),candidateState=ref('idle'),candidateFailure=ref(false),about=ref(false);
const schemes=ref([structuredClone(exampleScheme)]),savedDraft=ref(null),lastDraft=ref(null),storageKey='subscribetter:design-study:draft';
try{const data=JSON.parse(sessionStorage.getItem(storageKey)||'null');if(data&&typeof data.id==='string')savedDraft.value=data}catch{}
const current=computed(()=>media.find(m=>m.id===selected.value));
const filtered=computed(()=>media.filter(m=>(!query.value||m.title.toLowerCase().includes(query.value.toLowerCase()))&&(filter.value==='all'||filter.value==='attention'&&m.episodes.some(e=>e.phase==='UNKNOWN')||filter.value==='active'&&m.episodes.length||filter.value==='paused'&&m.state==='PAUSED')));
const units=computed(()=>(current.value?.episodes||[]).filter(u=>episodeFilter.value==='all'||u.phase==='UNKNOWN'));
function select(id){listPosition.value=scroll.value?.scrollTop||0;listFocus.value=id;selected.value=id;detailTab.value='episodes';episodeFilter.value='all';candidateOpen.value=false;nextTick(()=>{if(scroll.value)scroll.value.scrollTop=0;document.querySelector('.work-heading h1')?.focus()})}
function back(){selected.value='';nextTick(()=>{if(scroll.value)scroll.value.scrollTop=listPosition.value;[...document.querySelectorAll('.media-row')].find(el=>el.dataset.mediaId===listFocus.value)?.focus({preventScroll:true})})}
function navigate(value){section.value=value;selected.value='';notice.value='';nextTick(()=>scroll.value?.scrollTo(0,0))}
function start(value){scheme.value=JSON.parse(JSON.stringify(value||blankScheme()));lastDraft.value=scheme.value;notice.value=''}
function cache(value){lastDraft.value=value;try{sessionStorage.setItem(storageKey,JSON.stringify(value))}catch{notice.value='浏览器无法保留草稿，请勿刷新页面。'}}
function closeEditor(event){if(event.dirty){leave.value=event;return}scheme.value=null;lastDraft.value=null;savedDraft.value=null;sessionStorage.removeItem(storageKey)}
function leaveEditor(keep){if(keep){savedDraft.value=JSON.parse(JSON.stringify(leave.value.draft));cache(savedDraft.value)}else{savedDraft.value=null;lastDraft.value=null;sessionStorage.removeItem(storageKey)}scheme.value=null;leave.value=null}
function save(value){const n=schemes.value.findIndex(s=>s.id===value.id);if(n<0)schemes.value.push(value);else schemes.value[n]=value;lastDraft.value=null;savedDraft.value=null;sessionStorage.removeItem(storageKey)}
let alive=true;async function readCandidate(){if(candidateState.value==='loading')return;candidateOpen.value=true;candidateState.value='loading';await new Promise(r=>setTimeout(r,500));if(alive)candidateState.value=candidateFailure.value?'error':'loaded'}
function protect(event){if(scheme.value&&lastDraft.value&&JSON.stringify(lastDraft.value)!==JSON.stringify(schemes.value.find(s=>s.id===scheme.value.id))){event.preventDefault();event.returnValue=''}}
window.addEventListener('beforeunload',protect);onBeforeUnmount(()=>{alive=false;window.removeEventListener('beforeunload',protect)});
</script>
<template><VApp><div class="design-study"><aside class="study-banner"><span><b>交互样板</b><span class="banner-detail">合成数据 · 不连接 NAS · 所有操作仅在浏览器模拟</span></span><button @click="about=!about">{{about?'收起说明':'验证范围'}}</button></aside><section v-if="about" class="study-about"><strong>本轮只确定三个场景的设计</strong><p>订阅列表 → 分集升级 → 首次配置。这里没有真实下载、云端核对或写入设置。正式接口、原生保存合同与其余功能尚未接入；美观和操作连贯性等待审阅。</p></section>
 <div class="product-shell"><header class="product-header"><a href="#" class="brand" aria-label="subscriBetter 订阅首页" @click.prevent="!scheme&&navigate('subscriptions')"><span class="brand-mark" aria-hidden="true">sB</span><strong>subscriBetter</strong></a><nav aria-label="工作区"><button :aria-current="section==='subscriptions'?'page':undefined" :disabled="!!scheme" @click="navigate('subscriptions')">订阅</button><button :aria-current="section==='schemes'?'page':undefined" :disabled="!!scheme" @click="navigate('schemes')">下载与入库方案</button></nav><button class="theme-button" @click="theme.global.name.value=theme.global.name.value==='dark'?'light':'dark'" aria-label="切换明暗主题">◐</button></header>
 <main ref="scroll" class="product-content" :class="{'focused-content':!!scheme}">
 <Scheme v-if="scheme" :key="scheme.id" :initial="scheme" :baseline="schemes.find(s=>s.id===scheme.id)" @save="save" @draft="cache" @leave="closeEditor"/>
 <section v-else-if="section==='schemes'" class="schemes-page"><header class="page-heading"><div><span class="eyebrow">为下一次订阅准备好</span><h1>下载与入库方案</h1><p>下载到哪里、选择什么版本、整理到哪个媒体库。</p></div><VBtn color="primary" @click="start()">新建方案 <span aria-hidden="true">＋</span></VBtn></header><div v-if="savedDraft" class="draft-notice"><span>有一份未保存的草稿：{{savedDraft.name||'未命名方案'}}</span><VBtn variant="text" @click="start(savedDraft)">继续编辑</VBtn></div><div class="scheme-list"><button v-for="s in schemes" :key="s.id" @click="start(s)"><span class="scheme-icon" aria-hidden="true">↳</span><span><strong>{{s.name}}</strong><small>{{s.category}} · {{s.policy}}</small><span class="scheme-route">{{s.downloader}}<span>→</span>{{s.library}}</span></span><span class="row-arrow" aria-hidden="true">›</span></button></div><p class="quiet">已有方案可以改显示名称；内部关联使用稳定编号。</p></section>
 <section v-else-if="!selected" class="subscriptions-page"><header class="page-heading"><div><h1>订阅 <span class="title-count">{{media.length}}</span></h1></div><VBtn variant="tonal" @click="navigate('schemes')">管理下载方案 <span aria-hidden="true">↗</span></VBtn></header>
 <div class="list-toolbar"><div class="list-filters" role="group" aria-label="筛选订阅"><button v-for="[value,label,count] in [['all','全部',4],['active','处理中',1],['attention','需核对',1],['paused','已暂停',1]]" :key="value" :aria-pressed="filter===value" @click="filter=value">{{label}} <span>{{count}}</span></button></div><label class="search-field"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/></svg><input v-model="query" aria-label="搜索订阅" placeholder="搜索作品"></label></div>
 <div class="media-table-header" aria-hidden="true"><span>作品</span><span>当前收藏</span><span>正在发生</span></div><div class="media-list"><MediaRow v-for="work in filtered" :key="work.id" :work="work" @open="select"/></div><div v-if="!filtered.length" class="empty-state"><h2>没有找到这部作品</h2><p>尝试换一个名称，或清除当前筛选。</p><VBtn variant="text" @click="query='';filter='all'">清除筛选</VBtn></div><footer class="list-foot"><span>显示 {{filtered.length}} 部作品</span><span>新增订阅继续使用 MoviePilot</span></footer></section>
 <section v-else class="work-page"><button class="back-link" @click="back"><span aria-hidden="true">←</span> 订阅列表</button><header class="work-heading"><span class="cover detail-cover" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.2"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M7 4v16M17 4v16M3 9h4m10 0h4M3 15h4m10 0h4"/></svg></span><div><h1 tabindex="-1">{{current.title}}</h1><p>{{[current.year,current.type,current.season?'第 '+current.season+' 季':null].filter(Boolean).join(' · ')}}<span class="work-status">{{current.state==='PAUSED'?'已暂停':current.state==='STOPPED'?'已停止':'自动追踪'}}</span></p></div><div class="work-collection" v-if="current.present!==null"><strong>{{current.present}} <small>/ {{current.known}} 集</small></strong><span>已在库</span></div></header>
 <nav class="detail-tabs" aria-label="作品内容"><button :aria-current="detailTab==='episodes'?'page':undefined" @click="detailTab='episodes'">分集与版本</button><button :aria-current="detailTab==='candidates'?'page':undefined" @click="detailTab='candidates'">候选比较</button></nav>
 <template v-if="detailTab==='episodes'"><div v-if="current.episodes.length" class="episode-toolbar"><div class="compact-filters"><button :aria-pressed="episodeFilter==='all'" @click="episodeFilter='all'">全部 {{current.episodes.length}} 集</button><button :aria-pressed="episodeFilter==='attention'" @click="episodeFilter='attention'">需核对 1</button></div><details class="column-help"><summary>如何理解版本信息</summary><p>库内规格来自已有记录；升级目标采用发布信息。高亮表示服务端比较记录中的决定性维度，完整来源与文件依据放在各集详情。</p></details></div><div v-if="units.length" class="episode-list"><Episode v-for="episode in units" :key="episode.number" :episode="episode"/></div><div v-else class="empty-state"><h2>{{current.state==='PAUSED'?'升级已暂停':current.state==='STOPPED'?'当前没有追踪任务':'还没有可展示的分集'}}</h2><p>{{current.state==='PAUSED'?'已有库内版本继续保留。':'取得可靠集数与版本信息后，会在这里显示。'}}</p><small>此样板未接入暂停、恢复或接管的真实接口。</small></div></template>
 <section v-else-if="current.id==='gate24'" class="candidate-view"><header><span class="resource-tag">WEB-DL · 4K</span><h2>GATE24 S01 · NF · HHWEB</h2><p class="quiet">本资源的可处理范围，按当时的比较结果显示</p></header><div class="candidate-groups"><div><strong>第 1–6 集</strong><span data-tone="active">升级已有版本</span><small>分辨率更优</small></div><div><strong>第 7–8 集</strong><span>补齐缺少的集数</span><small>尚未在库中找到</small></div></div><p class="quiet">摘要覆盖 8 / 16 集。其余结果需展开读取。</p><VBtn variant="text" @click="candidateOpen?candidateOpen=false:readCandidate()">{{candidateOpen?'收起详情':'查看全部 16 集的比较'}}</VBtn><label class="simulation-option"><input type="checkbox" v-model="candidateFailure">模拟详情读取失败</label><section v-if="candidateOpen" class="candidate-detail"><div v-if="candidateState==='loading'" class="skeleton" role="status">正在加载比较详情…</div><div v-else-if="candidateState==='error'" class="read-error" role="alert"><strong>比较详情暂时无法加载</strong><p>已显示的摘要保留。</p><VBtn variant="tonal" @click="readCandidate">重新加载</VBtn><details><summary>错误详情</summary><p>合成响应 HTTP 503 · 读取候选比较详情</p></details></div><template v-else><div v-for="n in 16" :key="n" class="comparison-item"><strong>第 {{n}} 集</strong><span>{{n<7?'升级已有版本':'补齐缺少的集数'}}</span><small>{{n<7?'比较依据：分辨率':'比较依据：尚未在库中找到'}}</small></div></template></section></section>
 <section v-else class="empty-state"><h2>暂无候选比较记录</h2><p>这部作品没有可展示的比较结果。</p></section>
 </section></main><div v-if="notice" class="toast" role="status">{{notice}}</div></div>
 <VDialog :model-value="!!leave" max-width="460" persistent><section class="leave-dialog"><span class="eyebrow">方案草稿</span><h2>稍后继续这份配置？</h2><p>保留草稿后，可从方案列表回到这里。尚未写入 MoviePilot。</p><div><VBtn variant="text" @click="leave=null">继续编辑</VBtn><VBtn variant="text" @click="leaveEditor(false)">放弃修改</VBtn><VBtn color="primary" @click="leaveEditor(true)">保留草稿</VBtn></div></section></VDialog>
 </div></VApp></template>
