<script setup>
import {ref,computed,watch,nextTick} from 'vue';
import {issues,mappingKey,samples,simulatePathCheck,exampleScheme} from './model.mjs';
const props=defineProps({initial:Object,baseline:Object});const emit=defineEmits(['save','leave','draft']);
const draft=ref(JSON.parse(JSON.stringify(props.initial))),step=ref(0),errors=ref([]),sample=ref(''),choosing=ref(false),checking=ref(false),checkResult=ref(null),saved=ref(false),saving=ref(false),saveFailure=ref(false),saveError=ref('');
const steps=[['下载与偏好','选择作品分类和版本'],['云盘与目录','限定允许写入的范围'],['媒体库与路径','用一部作品检查连接'],['整理与交付','确认文件交给谁'],['确认方案','检查后保存']];
const hints=['下载新版本时，继续保留当前可播放的版本。','只使用已连接的服务。文件写入限制在下方目录内。','选择样本，只检查这一部作品的路径转换。无需开启自动追踪。','先暂存完整视频与必要字幕，再交给 Symedia 整理。','保存后可在接管订阅时选用此方案。'];
const availableSamples=computed(()=>draft.value.library==='剧集（示例）'?samples:[]);
watch(()=>[draft.value.server,draft.value.library],()=>{sample.value='';choosing.value=false});
const dirty=computed(()=>JSON.stringify(draft.value)!==JSON.stringify(props.baseline));
watch(draft,()=>{errors.value=[];saved.value=false;saveError.value='';emit('draft',structuredClone(JSON.parse(JSON.stringify(draft.value))))},{deep:true});
let sequence=0;watch(()=>mappingKey(draft.value),()=>{sequence++;checkResult.value=null;checking.value=false});watch(sample,()=>{sequence++;checkResult.value=null;checking.value=false});
function go(index){if(index>step.value){for(let n=step.value;n<index;n++){const found=issues(draft.value,n);if(found.length){step.value=n;errors.value=found;nextTick(()=>document.getElementById('scheme-'+found[0].key)?.focus());return}}}step.value=index;errors.value=[];nextTick(()=>document.querySelector('.scheme-body')?.scrollTo(0,0))}
async function check(){if(checking.value||!sample.value)return;const n=++sequence;checking.value=true;checkResult.value=null;const s=JSON.parse(JSON.stringify(draft.value)),item=samples.find(v=>v.id===sample.value);await new Promise(r=>setTimeout(r,600));if(n!==sequence)return;checkResult.value=simulatePathCheck(s,item);checking.value=false;nextTick(()=>document.querySelector('.mapping-result')?.scrollIntoView({block:'nearest'}));}
async function save(){if(saving.value)return;saving.value=true;saveError.value='';await new Promise(r=>setTimeout(r,500));saving.value=false;if(saveFailure.value){saveError.value='模拟保存失败，输入仍保留。检查后可以再次保存。';return}saved.value=true;emit('save',JSON.parse(JSON.stringify(draft.value)));}
function fillExample(){draft.value={...exampleScheme,id:draft.value.id,name:draft.value.name||exampleScheme.name}}
defineExpose({dirty});
</script>
<template><section class="scheme-flow">
 <header class="scheme-heading"><div><span class="eyebrow">下载与入库方案</span><h1>{{draft.name||'新建方案'}}</h1></div><button class="text-button" @click="emit('leave',{dirty,draft})">退出编辑 <span aria-hidden="true">↗</span></button></header>
 <div class="scheme-layout"><nav class="scheme-nav" aria-label="方案配置步骤"><button v-for="([label,note],index) in steps" :key="label" :aria-label="'第 '+(index+1)+' 步：'+label" :aria-current="step===index?'step':undefined" :disabled="saving" @click="go(index)"><span class="step-number">{{index+1}}</span><span><b>{{label}}</b><small>{{note}}</small></span></button><aside><span class="quiet">本轮设计验证</span><p>保存、读取样本和路径检查均在浏览器内模拟。</p><button class="text-button" @click="fillExample">填入一份完整示例</button></aside></nav>
 <div class="scheme-main"><div class="scheme-body"><header class="step-heading"><span class="eyebrow">{{String(step+1).padStart(2,'0')}} / 05</span><h2>{{steps[step][0]}}</h2><p>{{hints[step]}}</p></header>
 <div v-if="errors.length" class="form-errors" role="alert"><p v-for="error in errors" :key="error.key">{{error.message}}</p></div>
 <section v-if="step===0" class="form-fields"><label class="full">方案名称<input id="scheme-name" v-model="draft.name" maxlength="120" placeholder="例如：追更剧集"><small>可以随时改名，已使用它的订阅仍指向同一份方案。</small></label><label>作品分类<select id="scheme-category" v-model="draft.category"><option disabled value="">选择分类</option><option>电视剧</option><option>电影</option></select></label><label>下载器<select id="scheme-downloader" v-model="draft.downloader"><option disabled value="">选择已连接的下载器</option><option>qBittorrent（示例）</option></select></label><label class="full">下载目录<input id="scheme-download" v-model="draft.download" placeholder="/downloads/series"></label><fieldset class="full preference-options"><legend>版本偏好</legend><label><input id="scheme-policy" type="radio" v-model="draft.policy" value="4K 优先 · 保留当前可播版本"><span><b>4K 优先</b><small>条件符合时升级，等待期间保留原版</small></span></label><label><input type="radio" v-model="draft.policy" value="1080p 优先 · 保留当前可播版本"><span><b>1080p 优先</b><small>优先选择体积适中的版本</small></span></label></fieldset></section>
 <section v-else-if="step===1" class="form-fields"><label>CD2 连接<select id="scheme-cd2" v-model="draft.cd2"><option disabled value="">选择连接</option><option>CD2（示例）</option></select></label><label>115 连接<select id="scheme-p115" v-model="draft.p115"><option disabled value="">选择连接</option><option>115（示例）</option></select></label><label class="full">云盘根目录<input id="scheme-root" v-model="draft.root" placeholder="/115"></label><label class="full">允许写入的目录<input id="scheme-allowed" v-model="draft.allowed" placeholder="/115/series"><small>暂存和整理入口都应位于这个目录内。</small></label><div class="scope-note full"><span aria-hidden="true">↳</span><p>此方案不会自动获得整个云盘的写入权限。</p></div></section>
 <section v-else-if="step===2"><div class="form-fields"><label>Emby 连接<select id="scheme-server" v-model="draft.server"><option disabled value="">选择连接</option><option>Emby（示例）</option></select></label><label>媒体库<select id="scheme-library" v-model="draft.library"><option disabled value="">选择媒体库</option><option>剧集（示例）</option><option>电影（示例）</option></select></label></div>
 <div class="path-pair"><header><span class="pair-number">1</span><div><h3>找到 STRM 文件</h3><p>同一文件在 Emby 与 MoviePilot 中的目录</p></div></header><label>Emby 中的路径<input id="scheme-emby" v-model="draft.emby" placeholder="/strm/series"></label><span class="path-connector" aria-hidden="true">↓</span><label>MoviePilot 中的路径<input id="scheme-local" v-model="draft.local" placeholder="/media/strm/series"></label></div>
 <div class="path-pair"><header><span class="pair-number">2</span><div><h3>定位云端视频</h3><p>将 STRM 内的播放地址对应到 CD2 路径</p></div></header><label>STRM 内的地址<input id="scheme-playback" v-model="draft.playback" placeholder="http://cd2.example/115/series"></label><span class="path-connector" aria-hidden="true">↓</span><label>CD2 中的路径<input id="scheme-remote" v-model="draft.remote" placeholder="/115/series"></label></div>
 <section class="sample-check"><header><div><h3>用一部作品试一下</h3><p>检查当前输入，不保存设置。</p></div><VBtn variant="tonal" :disabled="!draft.server||!draft.library" @click="choosing=!choosing">{{sample?'更换样本':'选择样本'}}</VBtn></header><div v-if="choosing" class="sample-options"><button v-for="s in availableSamples" :key="s.id" :aria-pressed="sample===s.id" @click="sample=s.id;choosing=false"><span><b>{{s.name}}</b><small>{{s.episode}} · STRM 文件（合成）</small></span><span aria-hidden="true">{{sample===s.id?'✓':'›'}}</span></button></div><p v-if="choosing&&!availableSamples.length" class="quiet">此示例媒体库没有 STRM 样本，请选择剧集库检查示例。</p><div v-if="sample" class="selected-sample"><span><b>{{samples.find(s=>s.id===sample)?.name}}</b><small>{{samples.find(s=>s.id===sample)?.episode}}</small></span><VBtn color="primary" :loading="checking" @click="check">检查当前路径</VBtn></div><section v-if="checkResult" class="mapping-result" :data-valid="checkResult.ok" role="status"><strong>{{checkResult.ok?'示例路径转换通过':'这份样本尚未匹配'}}</strong><p v-if="!checkResult.ok">{{checkResult.message}}</p><dl v-else><dt>Emby 文件</dt><dd>{{checkResult.emby}}</dd><dt>MoviePilot 读取</dt><dd>{{checkResult.local}}</dd><dt>CD2 视频</dt><dd>{{checkResult.remote}}</dd></dl><small>模拟草稿检查 · 未读取真实 Emby、STRM 或云端文件</small></section><p v-if="!sample" class="quiet">真实版本需只读获取选定媒体库的一页作品；本样板使用两条固定样本。</p></section>
 </section>
 <section v-else-if="step===3" class="form-fields"><label class="full">暂存目录<input id="scheme-staging" v-model="draft.staging" placeholder="/115/series/staging"><small>视频和字幕在这里等候齐备，Symedia 不应监控此目录。</small></label><label class="full">Symedia 入口<input id="scheme-incoming" v-model="draft.incoming" placeholder="/115/series/incoming"><small>文件齐备后交到这里，由 Symedia 整理和生成 STRM。</small></label><div class="delivery-strip full"><span>下载器</span><span aria-hidden="true">→</span><span>115 暂存</span><span aria-hidden="true">→</span><strong>Symedia 整理</strong></div><p class="quiet full">此处不授予删除权限。已有清理设置在正式接入时继续生效。</p></section>
 <section v-else class="scheme-review"><div v-if="saved" class="save-success" role="status"><span aria-hidden="true">✓</span><div><h3>方案已保存到本页</h3><p>这是浏览器样板，未修改 MoviePilot。</p></div></div><dl><dt>方案名称</dt><dd>{{draft.name}}</dd><dt>作品与偏好</dt><dd>{{draft.category}} · {{draft.policy}}</dd><dt>下载到</dt><dd>{{draft.downloader}}<small>{{draft.download}}</small></dd><dt>存放到</dt><dd>{{draft.cd2}} · {{draft.allowed}}</dd><dt>媒体库</dt><dd>{{draft.server}} / {{draft.library}}</dd><dt>路径检查</dt><dd>{{checkResult?.ok?'当前草稿通过示例检查':'未通过示例检查'}}<small>未替代真实媒体库验证</small></dd><dt>交给 Symedia</dt><dd>{{draft.incoming}}</dd></dl><details class="review-technical"><summary>保存范围与内部标识</summary><p>本页仅保存这一份模拟方案。正式接入仍须使用原有整份配置预检、原生保存和生效回读，并展示其他未保存改动与共享影响。</p><p>稳定 ID：<code>{{draft.id}}</code>，修改显示名称不会改变它。</p></details><label class="simulation-option"><input type="checkbox" v-model="saveFailure">模拟保存失败</label><p v-if="saveError" role="alert" class="form-errors">{{saveError}}</p></section>
 </div><footer class="scheme-footer"><VBtn variant="text" :disabled="step===0||saving" @click="go(step-1)">上一步</VBtn><span>{{saved?'仅在当前样板保存':dirty?'尚未保存':'未修改'}}</span><VBtn v-if="step<4" color="primary" @click="go(step+1)">下一步 <span aria-hidden="true">→</span></VBtn><VBtn v-else-if="!saved" color="primary" :loading="saving" @click="save">保存方案</VBtn><VBtn v-else color="primary" @click="emit('leave',{dirty:false,draft})">完成</VBtn></footer></div></div>
</section></template>
