<script setup>
import {ref,computed,watch,nextTick} from 'vue';
import {issues,mappingKey,samples,simulatePathCheck,exampleScheme,policies,categories,schedule,rules,policyName,categoryName} from './model.mjs';
import PathInput from '../../src/PathInput.vue';
import {dimensions} from '../../src/media.mjs';
const props=defineProps({initial:Object,baseline:Object});const emit=defineEmits(['save','leave','draft']);
const draft=ref(JSON.parse(JSON.stringify(props.initial))),step=ref(0),errors=ref([]),sample=ref(''),choosing=ref(false),checking=ref(false),checkResult=ref(null),saved=ref(false),saving=ref(false),saveFailure=ref(false),saveError=ref('');
const seconds=value=>value==null?'未设置':value+' 秒';
const steps=[['下载与策略','选择分类和已有策略'],['云盘与目录','限定允许写入的范围'],['媒体库与路径','选择样本检查路径'],['整理与交付','设置暂存与整理目录'],['确认方案','检查后保存']];
const hints=['选择分类和已有策略；此处展示仓库默认策略的离线快照。','只使用已连接的服务。文件写入限制在下方目录内。','选择样本，只检查这一部作品的路径转换。无需开启自动追踪。','先暂存完整视频与必要字幕，再交给 Symedia 整理。','保存后可在接管订阅时选用此方案。'];
const selectedPolicy=computed(()=>policies.find(p=>p.id===draft.value.policy));
const availablePolicies=computed(()=>policies.filter(p=>p.category_id===draft.value.category));
function selectPolicy(){draft.value.policyRevision=selectedPolicy.value?.revision||''}
function selectCategory(){draft.value.policy=availablePolicies.value[0]?.id||'';selectPolicy()}
const availableSamples=computed(()=>draft.value.library==='剧集（示例）'?samples:[]);
watch(()=>[draft.value.server,draft.value.library],()=>{sample.value='';choosing.value=false});
const dirty=computed(()=>JSON.stringify(draft.value)!==JSON.stringify(props.baseline));
watch(draft,()=>{errors.value=[];saved.value=false;saveError.value='';emit('draft',structuredClone(JSON.parse(JSON.stringify(draft.value))))},{deep:true});
let sequence=0;watch(()=>mappingKey(draft.value),()=>{sequence++;checkResult.value=null;checking.value=false});watch(sample,()=>{sequence++;checkResult.value=null;checking.value=false});
function go(index){if(index>step.value){for(let n=step.value;n<index;n++){const found=issues(draft.value,n);if(found.length){step.value=n;errors.value=found;nextTick(()=>document.getElementById('scheme-'+found[0].key)?.focus());return}}}step.value=index;errors.value=[];nextTick(()=>document.querySelector('.scheme-body')?.scrollTo(0,0))}
async function check(){if(checking.value||!sample.value)return;const n=++sequence;checking.value=true;checkResult.value=null;const s=JSON.parse(JSON.stringify(draft.value)),item=samples.find(v=>v.id===sample.value);await new Promise(r=>setTimeout(r,600));if(n!==sequence)return;checkResult.value=simulatePathCheck(s,item);checking.value=false;nextTick(()=>document.querySelector('.mapping-result')?.scrollIntoView({block:'nearest'}));}
async function save(){if(saving.value)return;saving.value=true;saveError.value='';await new Promise(r=>setTimeout(r,500));saving.value=false;if(saveFailure.value){saveError.value='模拟保存失败，输入仍保留。检查后可以再次保存。';return}saved.value=true;emit('save',JSON.parse(JSON.stringify(draft.value)));}
function fillExample(){draft.value={...exampleScheme,id:draft.value.id,name:draft.value.name||exampleScheme.name}}
defineExpose({dirty});
</script>
<template><section class="scheme-flow">
 <header class="scheme-heading"><div><span class="eyebrow">下载与入库方案</span><h1>{{draft.name||'新建方案'}}</h1></div><button class="text-button" @click="emit('leave',{dirty,draft})">退出编辑 <span aria-hidden="true">↗</span></button></header>
 <div class="scheme-layout"><nav class="scheme-nav" aria-label="方案配置步骤"><button v-for="([label,note],index) in steps" :key="label" :aria-label="'第 '+(index+1)+' 步：'+label" :aria-current="step===index?'step':undefined" :disabled="saving" @click="go(index)"><span class="step-number">{{index+1}}</span><span><b>{{label}}</b><small>{{note}}</small></span></button><aside><span class="quiet">本轮设计验证</span><p>保存、读取样本和路径检查均在浏览器内模拟。</p><button class="text-button" @click="fillExample">填入一份完整示例</button></aside></nav>
 <div class="scheme-main"><div class="scheme-body"><header class="step-heading"><h2 class="sr-only">{{steps[step][0]}}</h2><p>{{hints[step]}}</p></header>
 <div v-if="errors.length" class="form-errors" role="alert"><p v-for="error in errors" :key="error.key">{{error.message}}</p></div>
 <section v-if="step===0" class="form-fields"><label class="full">方案名称<input id="scheme-name" v-model="draft.name" maxlength="120" placeholder="例如：追更剧集"><small>名称用于在订阅时选择此方案。</small></label><label>MP 分类（示例）<select id="scheme-category" v-model="draft.category" @change="selectCategory"><option disabled value="">选择分类</option><option v-if="draft.category&&!categories.some(c=>c.id===draft.category)" :value="draft.category">已保存分类暂不可用</option><option v-for="c in categories" :key="c.id" :value="c.id">{{c.name}} · {{c.media_type}}</option></select></label><label>下载器<select id="scheme-downloader" v-model="draft.downloader"><option disabled value="">选择已连接的下载器</option><option>qBittorrent（示例）</option></select></label><label class="full">下载目录<input id="scheme-download" v-model="draft.download" placeholder="/downloads/series"></label><section class="full policy-reference"><label>质量策略<select id="scheme-policy" v-model="draft.policy" :disabled="!draft.category" @change="selectPolicy"><option disabled value="">先选择分类</option><option v-if="draft.policy&&!availablePolicies.some(p=>p.id===draft.policy)" :value="draft.policy">已保存策略暂不可用</option><option v-for="p in availablePolicies" :key="p.id" :value="p.id">{{p.name}}</option></select></label>
 <template v-if="selectedPolicy"><p class="policy-brief">允许 {{selectedPolicy.summary.resolutions.map(r=>r===2160?'4K':r+'p').join('、')}}；按 {{selectedPolicy.summary.comparison.map(r=>dimensions[r.dimension]).join(' › ')}} 依次比较。</p><details class="policy-rules"><summary>查看完整规则</summary><h3>{{selectedPolicy.name}}</h3><dl><dt>准入条件</dt><dd>身份与范围已确认；通过基础过滤；具有符合要求的中文音轨或字幕依据。</dd><dt>发布组</dt><dd>{{selectedPolicy.summary.group}}</dd><dt>片源</dt><dd>{{selectedPolicy.summary.source}}</dd></dl><h4>优先顺序</h4><p>先比较前一项，首个不同的条件决定优劣。</p><ol><li v-for="row in selectedPolicy.summary.comparison" :key="row.dimension"><b>{{dimensions[row.dimension]}}</b><span>{{row.order.join(' › ')}}</span><small v-if="row.note">{{row.note}}</small></li></ol><h4>同质量替换例外</h4><p v-if="selectedPolicy.summary.comparison.some(row=>row.dimension==='special')">质量相同时，可将PGS 推定更新为发布者明确标注；仍需通过准入与证据回执约束，不产生新的画质档。</p><p v-else>当前策略不比较特效字幕，不适用同质量字幕依据更新。</p><h4>观察与冷却（默认设置示例）</h4><p>观察{{schedule.observation_enabled?'已启用':'未启用'}} · 冷却{{schedule.cooldown_enabled?'已启用':'未启用'}} · {{schedule.supersession_limit===0?'禁止自动取代':'取代上限 '+schedule.supersession_limit+' 次'}}。</p><p v-if="schedule.observation_enabled&&[schedule.base_seconds,schedule.quiet_seconds,schedule.max_seconds].some(v=>v==null)" role="alert">观察已启用，但参数不完整。</p><p v-if="schedule.cooldown_enabled&&schedule.cooldown_seconds==null" role="alert">冷却已启用，但间隔未设置。</p><details><summary>查看时间参数</summary><p>基础 {{seconds(schedule.base_seconds)}} · 静默 {{seconds(schedule.quiet_seconds)}} · 最长 {{seconds(schedule.max_seconds)}} · 冷却间隔 {{seconds(schedule.cooldown_seconds)}} · 取代时间范围 {{seconds(schedule.supersession_seconds)}}</p></details><h4>额外限制</h4><p>此默认示例没有额外锁定、自定义准入或覆盖规则；正式接入读取所选策略的实际配置。</p><details class="policy-source"><summary>规则定义与版本</summary><p>由仓库 Policy.describe 与默认调度导出，未读取 NAS 保存配置。</p><p class="path-text">版本：{{selectedPolicy.revision}}</p><pre>{{JSON.stringify({configuration:selectedPolicy.configuration,rules},null,2)}}</pre></details></details></template>
 </section></section>
 <section v-else-if="step===1" class="form-fields"><label>CD2 连接<select id="scheme-cd2" v-model="draft.cd2"><option disabled value="">选择连接</option><option>CD2（示例）</option></select></label><label>115 连接<select id="scheme-p115" v-model="draft.p115"><option disabled value="">选择连接</option><option>115（示例）</option></select></label><label class="full">云盘根目录<input id="scheme-root" v-model="draft.root" placeholder="/115"></label><label class="full">允许写入的目录<input id="scheme-allowed" v-model="draft.allowed" placeholder="/115/series"><small>暂存和整理入口都应位于这个目录内。</small></label><div class="scope-note full"><span aria-hidden="true">↳</span><p>此方案不会自动获得整个云盘的写入权限。</p></div></section>
 <section v-else-if="step===2"><div class="form-fields"><label>Emby 连接<select id="scheme-server" v-model="draft.server"><option disabled value="">选择连接</option><option>Emby（示例）</option></select></label><label>媒体库<select id="scheme-library" v-model="draft.library"><option disabled value="">选择媒体库</option><option>剧集（示例）</option><option>电影（示例）</option></select></label></div>
 <div class="path-pair"><header><span class="pair-number">1</span><div><h3>找到 STRM 文件</h3><p>填写目录前缀，不含文件名。下方 Emby / MP 目录仅为示例，须按容器挂载填写。</p></div></header><PathInput label="Emby STRM 路径前缀" input-id="scheme-emby" v-model="draft.emby"/><span class="path-connector" aria-hidden="true">↓</span><PathInput label="MP 可读 STRM 路径前缀" input-id="scheme-local" v-model="draft.local"/></div>
 <div class="path-pair"><header><span class="pair-number">2</span><div><h3>定位云端视频</h3><p>读取 STRM 中的本地挂载路径，再映射到 CD2 API 内部路径。</p></div></header><PathInput label="STRM 内容路径前缀" input-id="scheme-playback" v-model="draft.playback"/><span class="path-connector" aria-hidden="true">↓</span><PathInput label="CD2 内部路径前缀" input-id="scheme-remote" v-model="draft.remote"/></div>
 <section class="sample-check"><header><div><h3>选择样本检查路径</h3><p>检查当前输入，不保存设置。</p></div><VBtn variant="tonal" :disabled="!draft.server||!draft.library" @click="choosing=!choosing">{{sample?'更换样本':'选择样本'}}</VBtn></header><div v-if="choosing" class="sample-options"><button v-for="s in availableSamples" :key="s.id" :aria-pressed="sample===s.id" @click="sample=s.id;choosing=false"><span><b>{{s.name}}</b><small>{{s.episode}} · STRM 文件（合成）</small></span><span aria-hidden="true">{{sample===s.id?'✓':'›'}}</span></button></div><p v-if="choosing&&!availableSamples.length" class="quiet">此示例媒体库没有 STRM 样本，请选择剧集库检查示例。</p><div v-if="sample" class="selected-sample"><span><b>{{samples.find(s=>s.id===sample)?.name}}</b><small>{{samples.find(s=>s.id===sample)?.episode}}</small></span><VBtn color="primary" :loading="checking" @click="check">检查当前路径</VBtn></div><section v-if="checkResult" class="mapping-result" :data-valid="checkResult.ok" role="status"><strong>{{checkResult.ok?'示例路径转换通过':'这份样本尚未匹配'}}</strong><p v-if="!checkResult.ok">{{checkResult.message}}</p><dl v-else><dt>Emby STRM 文件</dt><dd>{{checkResult.emby}}</dd><dt>MP 可读文件</dt><dd>{{checkResult.local}}</dd><dt>STRM 文件内容</dt><dd>{{checkResult.content}}</dd><dt>CD2 内部路径</dt><dd>{{checkResult.remote}}</dd></dl><small>模拟草稿检查 · 未读取真实 Emby、STRM 或云端文件</small></section><p v-if="!sample" class="quiet">真实版本需只读获取选定媒体库的一页作品；本样板使用两条固定样本。</p></section>
 </section>
 <section v-else-if="step===3" class="form-fields"><label class="full">暂存目录<input id="scheme-staging" v-model="draft.staging" placeholder="/115/series/staging"><small>视频和字幕在这里等候齐备，Symedia 不应监控此目录。</small></label><label class="full">Symedia 入口<input id="scheme-incoming" v-model="draft.incoming" placeholder="/115/series/incoming"><small>文件齐备后交到这里，由 Symedia 整理和生成 STRM。</small></label><div class="delivery-strip full"><span>下载器</span><span aria-hidden="true">→</span><span>115 暂存</span><span aria-hidden="true">→</span><strong>Symedia 整理</strong></div><p class="quiet full">此处不授予删除权限。已有清理设置在正式接入时继续生效。</p></section>
 <section v-else class="scheme-review"><div v-if="saved" class="save-success" role="status"><span aria-hidden="true">✓</span><div><h3>方案已保存到本页</h3><p>这是浏览器样板，未修改 MoviePilot。</p></div></div><dl><dt>方案名称</dt><dd>{{draft.name}}</dd><dt>分类与策略</dt><dd>{{categoryName(draft.category)}} · {{policyName(draft.policy)}}<small>保存所选策略的引用与版本</small></dd><dt>下载到</dt><dd>{{draft.downloader}}<small>{{draft.download}}</small></dd><dt>存放到</dt><dd>{{draft.cd2}} · {{draft.allowed}}</dd><dt>媒体库</dt><dd>{{draft.server}} / {{draft.library}}</dd><dt>路径检查</dt><dd>{{checkResult?.ok?'当前草稿通过示例检查':'未通过示例检查'}}<small>未替代真实媒体库验证</small></dd><dt>交给 Symedia</dt><dd>{{draft.incoming}}</dd></dl><details class="review-technical"><summary>保存范围与内部标识</summary><p>本页仅保存这一份模拟方案。正式接入仍须使用原有整份配置预检、原生保存和生效回读，并展示其他未保存改动与共享影响。</p><p>稳定 ID：<code>{{draft.id}}</code>，修改显示名称不会改变它。</p></details><label class="simulation-option"><input type="checkbox" v-model="saveFailure">模拟保存失败</label><p v-if="saveError" role="alert" class="form-errors">{{saveError}}</p></section>
 </div><footer class="scheme-footer"><VBtn variant="text" :disabled="step===0||saving" @click="go(step-1)">上一步</VBtn><span>{{saved?'仅在当前样板保存':dirty?'尚未保存':'未修改'}}</span><VBtn v-if="step<4" color="primary" @click="go(step+1)">下一步 <span aria-hidden="true">→</span></VBtn><VBtn v-else-if="!saved" color="primary" :loading="saving" @click="save">保存方案</VBtn><VBtn v-else color="primary" @click="emit('leave',{dirty:false,draft})">完成</VBtn></footer></div></div>
</section></template>
