<script setup>
import {computed,ref,onBeforeUnmount} from 'vue';
import Field from './Field.vue';import {reasonText,stateLabel,unitLabel} from './media.mjs';import {label} from './labels.mjs';
import {bodySchema,parameters,initial,clone,validate,resolve} from './schema.mjs';
import {pathFor,applyBody,errorText,id,saveFollowup} from './client.mjs';
const props=defineProps({action:Array,client:Object,status:Object,context:{type:Object,default:()=>({})}});
const emit=defineEmits(['close','changed','configure']);let mounted=true;
const schema=bodySchema(props.action[1]);const fields=ref(initial(schema));const paths=ref({});const errors=ref([]),busy=ref(false),preview=ref(null),review=ref(null),result=ref(null),attempted=ref(false);
const op=id();const hidden=['config_revision','runtime_generation','operation_id'];
for(const key of Object.keys(schema.properties||{}))if(props.context[key]!==undefined)fields.value[key]=clone(props.context[key]);
for(const p of parameters(props.action[1]).filter(p=>p.in==='path'))paths.value[p.name]=props.context[p.name]??initial(p.schema);
const pathParams=parameters(props.action[1]).filter(p=>p.in==='path'&&(!props.context._bound||props.context[p.name]===undefined));
const editable=computed(()=>Object.entries(schema.properties||{}).filter(([key])=>!hidden.includes(key)&&(!props.context._bound||props.context[key]===undefined)));
const receiptPath=ref('');
const scopes=[{value:'monitor',title:'本地监控文件'},{value:'staging',title:'115 暂存文件'},{value:'downloader_task',title:'下载器任务（保留数据）'},{value:'downloader_data',title:'下载器数据'}];
const retained={monitor:'保留 115 文件与下载器任务；若本地路径同时是下载器数据，删除会影响该本地文件。',staging:'保留本地文件、下载器任务和暂存父目录。',downloader_task:'只移除下载器任务，保留下载数据。',downloader_data:'删除原下载数据，已发布的云盘文件保留。'};
async function prepare(){if(busy.value)return;errors.value=[];
 const body=clone(fields.value);if(schema.properties?.config_revision){body.config_revision=props.status.current.value.revision;body.runtime_generation=props.status.health.value.generation;}if(schema.properties?.operation_id)body.operation_id=op;
 errors.value=validate(schema,body);if(errors.value.length)return;
 busy.value=true;try{receiptPath.value=pathFor(props.action[1],paths.value);if(props.action[1].endsWith('/preview')){const p=await props.client.post(receiptPath.value,body);if(mounted)preview.value=Object.freeze(clone(p));}else review.value=Object.freeze(body);}catch(e){if(mounted)errors.value=[errorText(e)];}finally{if(mounted)busy.value=false;}}
async function execute(){if(busy.value||attempted.value)return;busy.value=true;attempted.value=true;errors.value=[];
 try{const r=preview.value?await props.client.post(receiptPath.value.replace(/\/preview$/,'/apply'),applyBody(preview.value,op)):await props.client.post(receiptPath.value,review.value);if(mounted){result.value=r;emit('changed');}}
 catch(e){if(mounted)errors.value=[errorText(e)];}finally{if(mounted)busy.value=false;}}
async function observe(){busy.value=true;try{const r=await props.client.get('/management/operations/'+op);if(mounted)result.value=r;}catch(e){if(mounted)errors.value=[errorText(e)]}finally{if(mounted)busy.value=false}}
onBeforeUnmount(()=>{mounted=false;fields.value={};review.value=null});
function continueSave(){saveFollowup(props.client.pluginId,{operation:op});emit('configure')}
</script>
<template><div class="sb-root sb-dialog" role="dialog" aria-modal="true" :aria-label="action[0]"><h2>{{action[0]}}</h2><template v-if="context._bound"><h3>{{context._label}}</h3><p>{{context._description}}</p></template>
 <template v-if="!preview&&!review&&!result"><p v-if="!context._bound">只提交当前表单中的精确范围。服务端仍校验当前配置、代次、归属与权限。</p><Field v-for="p in pathParams" :key="p.name" :name="p.name" :schema="p.schema" v-model="paths[p.name]"/><Field v-for="[key,s] in editable" :key="key" :name="key" :schema="s" :options="key==='scope'&&action[1].includes('/cleanup/')?scopes:[]" v-model="fields[key]"/><VBtn color="primary" :disabled="busy||!status.current.value||!!status.error.value" @click="prepare">{{context._bound?'核对操作':action[1].endsWith('/preview')?'取得不可变预览':'核对待提交操作'}}</VBtn></template>
 <template v-else-if="!result"><h3>{{context._bound?'请确认本次操作':'无法确认操作范围'}}</h3><template v-if="context._bound"><section v-if="preview&&['cancel','cleanup'].includes(preview.kind)" class="sb-confirm-scope"><h3>{{preview.kind==='cancel'?'取消范围':'将清理的范围'}}</h3><p v-if="preview.kind==='cancel'">取消此交付组；保留文件和下载器任务，不删除数据。</p><template v-else><p><strong>{{scopes.find(s=>s.value===preview.objects.scope)?.title}}</strong></p><p>{{retained[preview.objects.scope]}}</p><p v-if="preview.objects.download">下载器：{{preview.objects.download.downloader}} · 任务标识：{{preview.objects.download.infohash}}</p><ul class="sb-path-current"><li v-for="p in preview.objects.locations||[]" :key="p">{{p}}</li></ul></template><p v-if="preview.objects.authority">作品范围：{{Object.keys(preview.objects.authority).map(target_key=>unitLabel({target_key})).join('、')}}</p><ul class="sb-confirm-files"><li v-for="f in preview.objects.files||[]" :key="f.file_index">{{f.relative_path}}</li></ul><p class="sb-muted">确认后仍会复查文件身份与共享引用；实际处理以服务器记录为准。</p></section><section v-if="preview?.kind==='select_candidate'&&preview.objects.selection" class="sb-confirm-scope"><h3>将使用的替代资源</h3><p><strong>{{preview.objects.selection.title}}</strong></p><p>处理范围：{{preview.objects.selection.affected_targets.map(target_key=>unitLabel({target_key})).join('、')}} · {{preview.objects.selection.file_count}} 个文件</p><p v-if="preview.objects.selection.shared_files" class="sb-warning">包含覆盖多集的共享文件，上述处理范围会一起执行。</p><p class="sb-muted">确认时会重新检查当前版本、策略和任务占用；已有可播放版本继续保留到正常交付完成。</p></section><ul v-if="preview?.blockers?.length" class="sb-error"><li v-for="b in preview.blockers" :key="b">{{reasonText(b)}}</li></ul><ul v-if="preview?.permissions"><li v-for="(allowed,key) in preview.permissions" :key="key">{{label(key)}}：{{allowed?'当前已授权':'当前未授权'}}</li></ul></template><p v-else class="sb-error">请从具体作品、候选或交付记录发起操作。</p><p v-if="preview?.blockers?.length" role="alert" class="sb-error">存在阻塞；不能确认。刷新实际状态后重新预览。</p><VBtn v-if="context._bound" :color="action[1].includes('/cleanup/')?'error':'primary'" :disabled="busy||attempted||!!preview?.blockers?.length" @click="execute">确认{{action[0]}}</VBtn></template>
 <template v-if="result"><h3>操作结果</h3><p v-if="result.state">{{stateLabel(result.state)}}</p><p v-if="result.reason">{{reasonText(result.reason)}}</p><ul v-if="result.sources"><li v-for="(stage,key) in result.sources" :key="key">{{context._label||key}}：{{stateLabel(stage.state)}}{{stage.items!==null&&stage.items!==undefined?' · '+stage.items+' 条':''}}<span v-if="stage.reason"> · {{reasonText(stage.reason)}}</span></li></ul><p v-if="result.items!==undefined">本次抓取 {{result.items}} 条，仅验证抓取。</p><p v-if="result.changed!==undefined">已更新 {{result.changed}} 条记录。</p><p v-if="result.state==='UNKNOWN'" class="sb-error">结果仍未确认；系统会继续核对，不会重复提交。</p><p v-if="result.result?.native_save_required">配置变更已准备好，需要继续保存。页面会自动带入本次操作依据。</p><VBtn v-if="result.result?.native_save_required" color="primary" @click="continueSave">继续保存设置</VBtn></template>
 <ul v-if="errors.length" role="alert" class="sb-error"><li v-for="e in errors" :key="e">{{e}}</li></ul><div class="sb-actions"><button v-if="attempted&&preview" :disabled="busy" @click="observe">核对本次结果</button><VBtn variant="text" :disabled="busy" @click="emit('close')">关闭</VBtn></div>
</div></template>
