<script setup>
import {ref} from 'vue';import LibraryPicker from './LibraryPicker.vue';import Destinations from './Destinations.vue';
const props=defineProps({modelValue:Object,api:Object,categories:Array,downloaders:Array,paths:Array,readonly:Boolean,section:{type:String,default:'all'}});const emit=defineEmits(['update:modelValue']);const name=ref('');
const update=patch=>emit('update:modelValue',{...props.modelValue,...patch});
function addName(){const value=name.value.trim();if(!value||props.readonly)return;update({meta_protected_names:[...new Set([...props.modelValue.meta_protected_names,value])]});name.value=''}
function auto(type,checked){update({auto_types:checked?[...new Set([...props.modelValue.auto_types,type])]:props.modelValue.auto_types.filter(t=>t!==type)})}
</script>
<template><section aria-label="基本设置与自动接管">
 <section v-if="['all','runtime'].includes(section)" class="sb-form-section"><h4>运行模式</h4><label class="sb-toggle-row"><span><strong>启用订阅追踪</strong><small>按已保存的策略接管、追踪作品。</small></span><input type="checkbox" :checked="modelValue.enabled" :disabled="readonly" @change="update({enabled:$event.target.checked})"></label><label class="sb-toggle-row"><span><strong>演练模式</strong><small>预演配置，不执行普通下载和交付；任务保护仍独立运行。</small></span><input type="checkbox" :checked="modelValue.dry_run" :disabled="readonly" @change="update({dry_run:$event.target.checked})"></label></section>
 <template v-if="['all','adoption'].includes(section)"><section class="sb-form-section"><h4>自动接管新订阅</h4><div class="sb-inline"><label v-for="type in ['电影','电视剧']" :key="type" class="sb-check"><input type="checkbox" :checked="modelValue.auto_types.includes(type)" :disabled="readonly" @change="auto(type,$event.target.checked)">{{type}}</label></div><p class="sb-muted">在 MoviePilot 中添加订阅后，符合范围的新订阅由插件接管。</p></section>
 <section class="sb-form-section"><h4>自动寻找更好版本的媒体库</h4><LibraryPicker :api="api" :model-value="modelValue.passive_libraries" :readonly="readonly" @update:model-value="update({passive_libraries:$event})"/><p class="sb-muted">仅对所选媒体库进行版本观察，仍需符合质量策略与交付权限。</p></section></template>
 <section v-if="['all','naming'].includes(section)" class="sb-form-section"><h4>解析修正</h4><label class="sb-check"><input type="checkbox" :checked="modelValue.enhance_host_meta" :disabled="readonly" @change="update({enhance_host_meta:$event.target.checked})">辅助 MoviePilot 识别含数字的片名</label><label class="sb-inline">保护的完整片名<input v-model="name" :disabled="readonly" maxlength="256" placeholder="输入完整片名，按回车添加" @keydown.enter.prevent="addName"><VBtn variant="text" :disabled="readonly||!name.trim()" @click="addName">添加片名</VBtn></label><ul class="sb-tags"><li v-for="title in modelValue.meta_protected_names" :key="title"><span>{{title}}</span><button type="button" :aria-label="'移除片名 '+title" :disabled="readonly" @click="update({meta_protected_names:modelValue.meta_protected_names.filter(v=>v!==title)})">×</button></li></ul><p class="sb-muted">完整匹配这些片名，避免把标题中的数字误识别为集数；不会改变已经保存的媒体身份。</p></section>
 <Destinations v-if="section==='all'" :model-value="modelValue.destination_templates" :categories="categories" :downloaders="downloaders" :paths="paths" :rules="modelValue.delivery?.rules||[]" :readonly="readonly" @update:model-value="update({destination_templates:$event})"/>
</section></template>
