// Deliberate domain navigation. Paths and bodies are checked against exported mounted DTOs.
export const views=[
 {id:'tasks',title:'目标与任务',note:'逐目标质量、缺集和在途在任务明细中。观察与冷却使用既有锚点；即时执行只越过等待。',resources:[['任务','/tasks'],['运行游标与结果','/health/runtime-records']],actions:[['纳管 / 一次性目标','/intents'],['调整任务范围与设置','/tasks/{task_id}/settings/preview'],['立即执行','/tasks/{task_id}/immediate'],['暂停 / 被动 / 停止','/tasks/{task_id}/state'],['恢复精确宿主壳','/tasks/{task_id}/recover'],['计划继续','/plans/{plan_id}/resume'],['整理对账','/plans/{plan_id}/organize/reconcile']]},
 {id:'candidates',title:'候选决策',note:'原始资源、实际准入、排序及排除依据分别保留。模拟不下载；刷新 / 搜索是明确的外部读取。',resources:[['候选资源','/candidates'],['不可变决策','/candidate-decisions'],['精确排除','/exclusions']],actions:[['有界搜索','/candidates/search'],['刷新原始候选','/candidates/{candidate_key}/refresh'],['评估候选','/candidates/evaluate'],['排除资源','/exclusions/preview'],['排除并换源','/candidates/{candidate_key}/change-source/preview'],['撤销排除','/exclusions/{exclusion_id}/revoke/preview']]},
 {id:'archive',title:'版本档案',note:'档案独立于订阅生命周期。资产页显示内容 Hash 与当前位置；失效档案不会删除媒体。映射测试逐步核实 STRM 与 CD2。',resources:[['档案目标','/archive/targets'],['档案扫描水位','/health/records/{section}',{section:'archive_scans'}]],actions:[['扫描 / 继续选定媒体库','/archive/refresh'],['测试两段映射','/archive/mapping-test'],['逻辑失效选定版本','/archive/invalidate/preview']]},
 {id:'delivery',title:'交付队列',note:'UNKNOWN 保留屏障和原始外部 ID。取消保留下载器任务与数据；清理必须单独预览精确归属对象。交付成功与 Emby 入库确认分开。',resources:[['交付组','/delivery/bundles'],['下载器对账','/health/records/{section}',{section:'downloads'}],['外部操作','/health/records/{section}',{section:'operations'}]],actions:[['重试选定阶段','/delivery/{bundle_id}/retry'],['取消交付并保留任务 / 数据','/delivery/{bundle_id}/cancel/preview'],['按独立权限清理','/delivery/{bundle_id}/cleanup/preview'],['下载器原始 ID 对账','/downloads/{downloader}/{infohash}/reconcile'],['交付 / 消费者对账','/health/reconcile']]},
 {id:'policy',title:'策略与预演',note:'分类绑定、准入、锁和维度来自实际配置。确定性预演不消耗观察时钟，不授予执行或删除权限。编辑通过配置预检与宿主 Save。',resources:[['当前分类策略','/policies'],['偏好与比较维度','/policies/catalog'],['真实决策重放依据','/candidate-decisions'],['迁移差异回执','/health/records/{section}',{section:'migration'}]],actions:[['确定性策略预演','/policies/simulate']]},
 {id:'health',title:'服务与健康',note:'配置或已构造能力不代表远端已探测。完整扫描水位、失败路径、消费者恢复和 backlog 单独显示。服务设置复用宿主。',resources:[['服务与兼容状态','/diagnostics'],['监控扫描','/health/records/{section}',{section:'local_scans'}],['档案扫描','/health/records/{section}',{section:'archive_scans'}],['运行记录 / 积压','/health/runtime-records'],['外部操作','/health/records/{section}',{section:'operations'}],['唯一处理者与冲突','/migration/owners']],actions:[['选定对象对账','/health/reconcile']]},
 {id:'discovery',title:'榜单发现',note:'使用配置中的本地 RSSHub 与服务器自带路由；评分来源以识别提供方为准。历史清理仅隐藏展示，不改变 STOPPED、排除或幂等记录。',resources:[['实际来源与预算','/discovery/sources'],['内置榜单路由','/discovery/catalog'],['发现历史','/discovery/records'],['分阶段统计','/discovery/statistics']],actions:[['仅抓取测试（不识别 / 提交）','/discovery/test'],['明确运行选定来源','/discovery/run'],['来源失败重试','/discovery/sources/retry'],['重新判定选定历史','/discovery/reprocess'],['隐藏选定历史','/discovery/history/cleanup/preview']]},
 {id:'ai',title:'解析与 AI',note:'打开、保存与确定性测试不请求模型。公共解析包装影响其他经过该入口的流程。',resources:[['AI 预算 / 提示词 / 兼容性','/ai'],['原文与重放样例','/parse/samples']],actions:[['确定性解析与差异','/parse'],['定向重放','/parse/replay'],['清理 AI 缓存','/ai/cache/clear/preview'],['预览恢复提示词','/ai/prompt/restore/preview']]},
 {id:'migration',title:'整合迁移',note:'SOURCE / IMPORT 进度与当前宿主 CUTOVER ACTIVE 分开。旧已添加历史不等于成功，旧分数 100 不等于质量，不恢复内存缓存或重放一次性开关。',resources:[['当前处理者与冲突','/migration/owners'],['迁移回执列表','/health/records/{section}',{section:'migration'}]],actions:[]},
];
export function links(path,row,values={}) {
 const pairs=[];const add=(title,route,values)=>pairs.push({title,route,values});
 if(path==='/tasks'){const v={task_id:row.id};add('逐目标 / 生命周期','/tasks/{task_id}',v);add('观察起点 / 截止 / 最后改善','/tasks/{task_id}/observations',v);add('机会计划 / 预算','/tasks/{task_id}/plans',v);add('解除纳管预览','/tasks/{task_id}/release-preview',v)}
 if(path==='/candidates'){const v={candidate_key:row.candidate_key};add('原始与身份依据','/candidates/{candidate_key}',v);for(const section of ['torrent_files','file_parse'])add(section==='torrent_files'?'原始文件表':'逐文件解析','/candidates/{candidate_key}/files/{section}',{...v,section});add('准入 / 排序 / 等待','/candidate-decisions',{candidate_key:row.candidate_key})}
 if(path==='/candidate-decisions'){add('完整不可变决策','/candidate-decisions/{decision_id}',{decision_id:row.id});add('实际计划','/candidate-decisions/{decision_id}/plans',{decision_id:row.id})}
 if(path==='/health/records/{section}'&&values.section==='archive_scans')add('扫描条目 / 映射测试对象','/archive/scans/{scan_id}/items',{scan_id:row.id});
 if(path==='/archive/targets')add('多版本档案','/archive/targets/{target_key}',{target_key:row.target_key});
 if(path.includes('/archive/targets/')&&row.id)add('内容 / 附件 / 位置 / Hash','/archive/versions/{version_id}',{version_id:row.id});
 if(path==='/delivery/bundles'){const v={bundle_id:row.id};add('逐文件 / 外部 ID / 归属','/delivery/bundles/{bundle_id}',v);for(const section of ['vector','assets','publication'])add({vector:'交付权与代次',assets:'冻结清单',publication:'发布条目'}[section],'/delivery/bundles/{bundle_id}/records/{section}',{...v,section})}
 if(path==='/policies')add('准入 / 覆盖 / 显式锁','/policies/{category_id}',{category_id:row.category_id});
 if(path==='/discovery/records')add('逐季关联任务','/discovery/records/{record_id}/targets',{record_id:row.id});
 if(path==='/parse/samples')add('原文 / 差异 / 解析 revision','/parse/samples/{sample_key}/history',{sample_key:row.id});
 if((path==='/tasks/{task_id}/plans'||path==='/candidate-decisions/{decision_id}/plans'||path==='/tasks/{task_id}'&&row.data?.authorization)&&row.id){const v={plan_id:row.id};add('真实文件清单','/plans/{plan_id}/files',v);for(const section of ['targets','actions','progress','organized','receipts'])add({targets:'目标授权',actions:'原始外部操作',progress:'测量字节 / 进度',organized:'整理回执',receipts:'历史回执'}[section],'/plans/{plan_id}/records/{section}',{...v,section})}
 if(row.data?.rule_id||path==='/health/records/{section}'&&values.section==='local_scans'&&String(row.id).startsWith('local:')){const rule_id=row.data?.rule_id||String(row.id).slice(6);for(const section of ['stack','directories','failed_paths'])add({stack:'待补扫目录',directories:'目录扫描水位',failed_paths:'失败路径'}[section],'/health/local-scans/{rule_id}/{section}',{rule_id,section})}
 if(path==='/health/records/{section}'&&values.section==='migration'||row.receipt_id)add('安全迁移回执','/migration/receipts/{receipt_id}',{receipt_id:row.receipt_id||row.id});
 return pairs;
}
