<script setup>
import {computed,onMounted,ref,watch} from 'vue';
import {fieldLabels,operatorLabels,referencedFields,sizeBytes,sizeDisplay} from './predicate-editor.mjs';
import {errorText} from './client.mjs';
const props=defineProps({client:Object,status:Object,policy:Object,expression:Object});
const mode=ref('candidate'),candidates=ref([]),candidate=ref(''),sample=ref({}),busy=ref(false),loading=ref(false),error=ref(''),result=ref(null);let request=0;
const sizeUnit=ref('GiB'),sizeRaw=ref('');
const fields=computed(()=>referencedFields(props.expression));
const numeric=new Set(['size','seeders','downloadvolumefactor','publish_minutes']);
const arrays=new Set(['labels','production_countries','origin_country','genre_ids']);
const statusText={PASS:'通过',FAIL:'不通过',MISSING:'缺少信息',ERROR:'表达式错误',NOT_RUN:'未执行'};
function invalidate(){request++;result.value=null;error.value=''}
watch(()=>props.expression,invalidate,{deep:true});
async function load(){loading.value=true;error.value='';try{const page=await props.client.get('/candidates',{params:{limit:25,offset:0}});candidates.value=page.items||[];if(!candidate.value)candidate.value=candidates.value[0]?.candidate_key||''}catch(e){error.value=errorText(e)}finally{loading.value=false}}
function edit(field,raw){const next={...sample.value};if(raw==='')delete next[field];else if(field==='size'){try{next[field]=sizeBytes(raw,sizeUnit.value)}catch{delete next[field]}}else if(arrays.has(field))next[field]=raw.split(',').map(value=>value.trim()).filter(Boolean);else if(numeric.has(field)){const value=Number(raw);if(Number.isFinite(value))next[field]=value;else delete next[field]}else next[field]=raw;sample.value=next;invalidate()}
function editSize(raw){sizeRaw.value=raw;edit('size',raw)}
function changeSizeUnit(next){if(sample.value.size!==undefined)sizeRaw.value=sizeDisplay(sample.value.size,next);sizeUnit.value=next;edit('size',sizeRaw.value)}
async function run(){if(busy.value||!props.status?.current?.value||!props.status?.health?.value)return;const signature=JSON.stringify([props.expression,mode.value,candidate.value,sample.value]),sequence=++request;busy.value=true;error.value='';result.value=null;try{const body={config_revision:props.status.current.value.revision,runtime_generation:props.status.health.value.generation,policy:{...props.policy,admission:props.expression},...(mode.value==='candidate'?{candidate_key:candidate.value}:{sample:sample.value})};const response=await props.client.post('/policies/admission-test',body);if(sequence===request&&signature===JSON.stringify([props.expression,mode.value,candidate.value,sample.value]))result.value=response.result}catch(e){if(sequence===request)error.value=errorText(e)}finally{if(sequence===request)busy.value=false}}
const rowText=row=>row.operator==='all'?'全部条件':row.operator==='any'?'任一条件':row.operator==='not'?'取反':row.operator==='literal'?'固定结果':row.operator==='registered'?'共享规则':`${fieldLabels[row.field]||row.field||''} ${operatorLabels[row.operator]||row.operator}`;
</script>

<template><section class="sb-condition-test" aria-label="测试这组条件"><div class="sb-heading"><div><h5>测试这组条件</h5><p class="sb-muted">只判断当前额外条件，不保存设置，也不会搜索、下载、上传或清理。</p></div></div><nav class="sb-segmented" aria-label="样本来源"><button :aria-current="mode==='candidate'?'page':undefined" @click="mode='candidate';invalidate()">已有候选</button><button :aria-current="mode==='manual'?'page':undefined" @click="mode='manual';invalidate()">手工样本</button></nav><label v-if="mode==='candidate'">已有候选<select aria-label="已有候选" :value="candidate" :disabled="loading||busy" @change="candidate=$event.target.value;invalidate()"><option value="">请选择候选</option><option v-for="item in candidates" :key="item.candidate_key" :value="item.candidate_key">{{item.title||item.candidate_key}}</option></select></label><div v-else class="sb-grid"><p v-if="!fields.length" class="sb-muted">当前条件只引用共享规则，建议使用已有候选测试。</p><label v-for="field in fields" :key="field">{{fieldLabels[field]||field}}<span v-if="field==='size'" class="sb-inline-quantity"><input type="number" inputmode="decimal" :value="sizeRaw" placeholder="留空表示缺少此信息" @input="editSize($event.target.value)"><select aria-label="资源大小单位" :value="sizeUnit" @change="changeSizeUnit($event.target.value)"><option v-for="unit in ['B','KiB','MiB','GiB','MB','GB']" :key="unit">{{unit}}</option></select></span><input v-else :type="numeric.has(field)?'number':'text'" :value="Array.isArray(sample[field])?sample[field].join(', '):sample[field]??''" :placeholder="arrays.has(field)?'多个值用逗号分隔':'留空表示缺少此信息'" @input="edit(field,$event.target.value)"></label></div><div class="sb-actions"><VBtn variant="tonal" :loading="busy" :disabled="busy||loading||(mode==='candidate'&&!candidate)" @click="run">开始测试</VBtn><VBtn v-if="mode==='candidate'" variant="text" :disabled="loading" @click="load">刷新候选</VBtn></div><p v-if="error" class="sb-error" role="alert">测试暂时无法完成：{{error}}</p><section v-if="result" class="sb-condition-test-result" aria-live="polite"><h5>{{result.status==='PASS'?'这组条件通过':result.status==='FAIL'?'这组条件不通过':result.status==='MISSING'?'信息不足，暂时无法判断':'条件执行失败'}}</h5><div v-for="row in result.trace" :key="row.path.join('.')" class="sb-condition-trace"><span>{{rowText(row)}}</span><strong :data-status="row.status">{{statusText[row.status]||row.status}}</strong><small v-if="row.status==='MISSING'&&row.field">缺少 {{fieldLabels[row.field]||row.field}}</small><small v-else-if="row.status==='NOT_RUN'">前面的条件已决定结果</small></div></section></section></template>
