<script setup>
import {computed} from 'vue';
import {durationDisplay,durationMinutes,fieldLabels,isConditionSupported,operatorLabels,operatorsForField,predicateSummary,sizeDisplay,sizeBytes} from './predicate-editor.mjs';
const props=defineProps({node:Object,readonly:Boolean,fields:Array,rules:Array,depth:{type:Number,default:0},path:{type:String,default:''},root:Boolean,errors:{type:Array,default:()=>[]}}),emit=defineEmits(['action']);
const rowErrors=computed(()=>props.errors.filter(error=>error.id===props.node.id));
const operators=computed(()=>operatorsForField(props.node.field));
const supported=computed(()=>isConditionSupported(props.node));
const excluded=computed(()=>props.node.kind==='not'&&props.node.child.kind==='group');
const group=computed(()=>excluded.value?props.node.child:props.node);
const groupDepth=computed(()=>props.depth+Number(excluded.value));
const groupId=computed(()=>`condition-group-${group.value.id}`);
const groupTitle=computed(()=>props.root?'匹配条件':`条件组 ${props.path}`);
const patch=value=>emit('action',{type:'patch',id:props.node.id,value});
function field(event){emit('action',{type:'field',id:props.node.id,value:event.target.value})}
function scalar(event){const raw=event.target.value;if(raw===''){patch({raw,incomplete:true});return}const value=Number(raw);patch(Number.isFinite(value)?{value,raw:'',incomplete:false}:{raw,incomplete:true})}
function size(event){const raw=event.target.value;try{patch({value:sizeBytes(raw,props.node.unit||'B'),raw:'',incomplete:false})}catch{patch({raw,incomplete:true})}}
function unit(event){const next=event.target.value;patch({unit:next,raw:sizeDisplay(props.node.value,next)})}
function duration(event){const raw=event.target.value;try{patch({value:durationMinutes(raw,props.node.unit||'分钟'),raw:'',incomplete:false})}catch{patch({raw,incomplete:true})}}
function durationUnit(event){const next=event.target.value;patch({unit:next,raw:durationDisplay(props.node.value,next)})}
function textValue(event){patch({value:event.target.value,raw:'',incomplete:event.target.value===''})}
function arrayValue(event){const values=event.target.value.split(',').map(value=>value.trim()).filter(Boolean);patch({value:values,incomplete:!values.length})}
</script>

<template>
 <fieldset v-if="group.kind==='group'" class="sb-condition-group" :class="{'sb-condition-not':excluded}" :style="{'--condition-depth':Math.min(depth,3)}">
  <legend>{{groupTitle}}<small v-if="!root">作为上一级的一项条件</small></legend><div class="sb-condition-toolbar"><select aria-label="匹配方式" :value="group.operator" :disabled="readonly" @change="emit('action',{type:'relation',id:group.id,value:$event.target.value})"><option value="all">满足以下所有条件</option><option value="any">满足以下任一条件</option></select><span>{{group.children.length}} 项条件</span><button type="button" :aria-expanded="String(!group.collapsed)" :aria-controls="groupId" @click="emit('action',{type:'collapse',id:group.id})">{{group.collapsed?'展开':'折叠'}}</button><button v-if="!root" type="button" :disabled="readonly" @click="emit('action',{type:'remove',id:node.id})">删除整组（{{group.children.length}} 项）</button></div>
  <label class="sb-check"><input type="checkbox" :checked="excluded" :disabled="readonly" @change="emit('action',{type:'negate',id:node.id})">排除符合这组条件的资源</label>
  <div :id="groupId" v-show="!group.collapsed" class="sb-condition-group-body">
   <template v-for="(child,index) in group.children" :key="child.id"><span v-if="index" class="sb-condition-join">{{group.operator==='all'?'并且':'或者'}}</span><ConditionNode :node="child" :readonly="readonly" :fields="fields" :rules="rules" :depth="groupDepth+1" :path="path?`${path}.${index+1}`:String(index+1)" :errors="errors" @action="emit('action',$event)"/></template>
   <div class="sb-condition-add"><button type="button" :disabled="readonly" @click="emit('action',{type:'add',id:group.id})">添加条件</button><button v-if="rules?.length" type="button" :disabled="readonly" @click="emit('action',{type:'reference',id:group.id})">引用共享规则</button><button type="button" :disabled="readonly||groupDepth>=13" @click="emit('action',{type:'add-group',id:group.id})">添加条件组</button></div>
  </div>
 </fieldset>
 <fieldset v-else-if="node.kind==='not'" class="sb-condition-group sb-condition-not"><legend>排除条件 {{path}}<button v-if="!root" type="button" :disabled="readonly" @click="emit('action',{type:'remove',id:node.id})">删除整组</button></legend><label class="sb-check"><input type="checkbox" :checked="true" :disabled="readonly" @change="emit('action',{type:'negate',id:node.id})">排除符合下列条件的资源</label><ConditionNode :node="node.child" :readonly="readonly" :fields="fields" :rules="rules" :depth="depth+1" :path="path" :errors="errors" @action="emit('action',$event)"/></fieldset>
 <div v-else-if="node.kind==='condition'&&!supported" class="sb-condition-row" :data-condition-id="node.id"><div class="sb-condition-advanced"><strong>旧条件暂不支持直接编辑</strong><span>{{predicateSummary(node)}}</span><span>该字段不支持这个判断关系，原配置没有被改写。</span></div><button type="button" :disabled="readonly" @click="emit('action',{type:'field',id:node.id,value:node.field})">改为常用条件</button><details v-if="!root" class="sb-condition-actions"><summary aria-label="条件的更多操作">更多</summary><div class="sb-condition-menu"><button type="button" :disabled="readonly" @click="emit('action',{type:'duplicate',id:node.id})">复制</button><button type="button" :disabled="readonly" @click="emit('action',{type:'wrap',id:node.id})">放入新条件组</button><button type="button" :disabled="readonly" @click="emit('action',{type:'remove',id:node.id})">删除</button></div></details><p v-for="error in rowErrors" :key="error.code" class="sb-condition-error" role="alert">{{error.message}}</p></div>
 <div v-else-if="node.kind==='condition'" class="sb-condition-row" :data-condition-id="node.id">
  <label><span class="sb-sr-only">字段</span><select aria-label="字段" :value="node.field" :disabled="readonly" @change="field"><option v-for="field in [...new Set([...(fields||[]),node.field])]" :key="field" :value="field">{{fieldLabels[field]||field}}</option></select></label>
  <label><span class="sb-sr-only">判断关系</span><select aria-label="判断关系" :value="node.operator" :disabled="readonly" @change="emit('action',{type:'operator',id:node.id,value:$event.target.value})"><option v-for="operator in operators" :key="operator" :value="operator">{{operatorLabels[operator]}}</option></select></label>
  <template v-if="node.field==='size'&&typeof node.value==='number'"><label class="sb-condition-value"><span class="sb-sr-only">比较值</span><input aria-label="比较值" inputmode="decimal" :value="node.incomplete&&node.raw===''?'':node.raw!==undefined&&node.raw!==''?node.raw:sizeDisplay(node.value,node.unit||'B')" :disabled="readonly" @input="size"></label><label class="sb-condition-unit"><span class="sb-sr-only">单位</span><select aria-label="单位" :value="node.unit||'B'" :disabled="readonly" @change="unit"><option v-for="name in ['B','KiB','MiB','GiB','MB','GB']" :key="name">{{name}}</option></select></label></template>
  <template v-else-if="node.field==='publish_minutes'&&typeof node.value==='number'"><label class="sb-condition-value"><span class="sb-sr-only">比较值</span><input aria-label="比较值" inputmode="decimal" :value="node.incomplete&&node.raw===''?'':node.raw!==undefined&&node.raw!==''?node.raw:durationDisplay(node.value,node.unit||'分钟')" :disabled="readonly" @input="duration"></label><label class="sb-condition-unit"><span class="sb-sr-only">单位</span><select aria-label="单位" :value="node.unit||'分钟'" :disabled="readonly" @change="durationUnit"><option v-for="name in ['分钟','小时','天']" :key="name">{{name}}</option></select></label></template>
  <template v-else-if="Array.isArray(node.value)"><label class="sb-condition-value"><span class="sb-sr-only">比较值</span><input aria-label="比较值" :value="node.value.join(', ')" :disabled="readonly" @input="arrayValue"></label></template>
  <template v-else-if="typeof node.value==='boolean'"><label class="sb-condition-value"><span class="sb-sr-only">比较值</span><select aria-label="比较值" :value="String(node.value)" :disabled="readonly" @change="patch({value:$event.target.value==='true'})"><option value="true">是</option><option value="false">否</option></select></label></template>
  <template v-else-if="node.value===null||typeof node.value==='object'"><span class="sb-condition-advanced">高级值：{{node.value===null?'空值':JSON.stringify(node.value)}}</span></template>
  <template v-else-if="typeof node.value==='number'"><label class="sb-condition-value"><span class="sb-sr-only">比较值</span><input aria-label="比较值" type="number" :value="node.incomplete&&node.raw===''?'':node.raw!==undefined&&node.raw!==''?node.raw:node.value" :disabled="readonly" @input="scalar"></label></template>
  <template v-else><label class="sb-condition-value"><span class="sb-sr-only">比较值</span><textarea v-if="node.operator==='regex'" aria-label="正则表达式" rows="1" :value="node.value" :disabled="readonly" @input="textValue"/><input v-else aria-label="比较值" :value="node.value" :disabled="readonly" @input="textValue"></label></template>
  <details v-if="!root" class="sb-condition-actions"><summary aria-label="条件的更多操作">更多</summary><div class="sb-condition-menu"><button type="button" :disabled="readonly" @click="emit('action',{type:'duplicate',id:node.id})">复制</button><button type="button" :disabled="readonly" @click="emit('action',{type:'wrap',id:node.id})">放入新条件组</button><button type="button" :disabled="readonly" @click="emit('action',{type:'remove',id:node.id})">删除</button></div></details>
  <p v-for="error in rowErrors" :key="error.code" class="sb-condition-error" role="alert">{{error.message}}</p>
 </div>
 <div v-else-if="node.kind==='registered'" class="sb-condition-row" :data-condition-id="node.id"><span>共享规则</span><select aria-label="共享规则" :value="node.name" :disabled="readonly" @change="patch({name:$event.target.value})"><option disabled value="">请选择共享规则</option><option v-for="name in [...new Set([...(rules||[]),node.name].filter(Boolean))]" :key="name">{{name}}</option></select><details v-if="!root" class="sb-condition-actions"><summary aria-label="条件的更多操作">更多</summary><div class="sb-condition-menu"><button type="button" :disabled="readonly" @click="emit('action',{type:'duplicate',id:node.id})">复制</button><button type="button" :disabled="readonly" @click="emit('action',{type:'wrap',id:node.id})">放入新条件组</button><button type="button" :disabled="readonly" @click="emit('action',{type:'remove',id:node.id})">删除</button></div></details><p v-for="error in rowErrors" :key="error.code" class="sb-condition-error" role="alert">{{error.message}}</p></div>
 <div v-else class="sb-condition-row" :data-condition-id="node.id"><span>固定结果</span><select aria-label="固定结果" :value="String(node.value)" :disabled="readonly" @change="patch({value:$event.target.value==='true'})"><option value="true">恒为通过</option><option value="false">恒为不通过</option></select><details v-if="!root" class="sb-condition-actions"><summary aria-label="条件的更多操作">更多</summary><div class="sb-condition-menu"><button type="button" :disabled="readonly" @click="emit('action',{type:'duplicate',id:node.id})">复制</button><button type="button" :disabled="readonly" @click="emit('action',{type:'wrap',id:node.id})">放入新条件组</button><button type="button" :disabled="readonly" @click="emit('action',{type:'remove',id:node.id})">删除</button></div></details></div>
</template>
