<script setup>
import {ref,onMounted,onBeforeUnmount,provide} from 'vue';
import {createClient,prepareSave,errorText,unwrap,readFollowup,clearFollowup,saveFollowup} from './client.mjs';
import {contract,clone,clean,validate,initial} from './schema.mjs';
import {label} from './labels.mjs';
import {useStatus} from './status.mjs';
import Status from './Status.vue';import Field from './Field.vue';
import './style.css';
import Destinations from './Destinations.vue';
import Policies from './Policies.vue';import Sources from './Sources.vue';import DeliverySettings from './DeliverySettings.vue';
const props=defineProps({api:{type:Object,required:true},pluginId:{type:String,required:true},sourcePluginId:String,initialConfig:{type:Object,default:()=>({})}});
const emit=defineEmits(['save','close','switch']);
const client=createClient(props.api,props.pluginId,props.sourcePluginId),status=useStatus(client);
const draftBase=ref(null),refreshing=ref(false),draft=ref(null),errors=ref([]),busy=ref(false),submitted=ref(false),group=ref('ownership'),catalog=ref(null),continuation=ref(null),continuationId=ref(''),continuationKind=ref('operation');let mounted=true;
const catalogs=ref({});provide('subscribetter:catalogs',catalogs);provide('subscribetter:api',props.api);
const downloaders=ref([]),paths=ref([]),catalogError=ref(''),policyDefaults=ref({}),sourceRoutes=ref([]);
async function readServices(){
 const results=await Promise.allSettled([props.api.get('download/clients',{feedback:'silent'}),props.api.get('download/paths',{feedback:'silent'})]);
 if(!mounted)return;catalogError.value='';
 for(const [i,r] of results.entries()){let data=null;try{data=r.status==='fulfilled'?unwrap(r.value):null}catch{};if(Array.isArray(data)){if(i===0)downloaders.value=data;else paths.value=data.filter(p=>(p.storage||'local')==='local')}else catalogError.value='部分宿主服务或目录暂不可用，现有设置已保留。可检查宿主配置后重新打开。'}
}
async function start(){const focus=readFollowup(props.pluginId)?.group;if(groups.some(g=>g[0]===focus))group.value=focus;await refresh();readServices();const followup=readFollowup(props.pluginId);if(followup?.operation){continuationId.value=followup.operation;await loadContinuation();if(errors.value.length)clearFollowup(props.pluginId)}}
const groups=[['ownership','纳管与宿主影响',['enabled','dry_run','auto_types','passive_libraries','destination_templates','enhance_host_meta','meta_protected_names']],['policy','独立策略',['policy']],['lifecycle','生命周期',['lifecycle']],['candidates','站点与搜索',['candidates']],['schedule','观察、冷却、抢占',['schedule']],['delivery','交付与映射',['delivery']],['recovery','扫描与恢复',['recovery']],['permissions','五项清理权限',['permissions']],['safety','安全与容量',['safety']],['discovery','榜单与 RSS',['discovery','history_view']],['ai','AI 名称辅助',['ai_assist']]];
async function refresh(){if(refreshing.value||busy.value)return;refreshing.value=true;try{const c=await status.refresh();if(c&&mounted){draftBase.value={revision:c.revision,digest:c.digest};draft.value=clean(contract.schemas.Config,clone(c.config));for(const [key,model] of [['delivery','DeliveryConfig'],['discovery','DiscoveryConfig']])draft.value[key]={...Object.fromEntries(Object.entries(contract.schemas[model].properties).map(([name,schema])=>[name,initial(schema)])),...draft.value[key]};continuation.value=null;submitted.value=false;errors.value=[];try{const [result,routes,policies]=await Promise.all([client.get('/configuration/categories'),client.get('/discovery/catalog'),client.get('/policies/catalog')]);if(mounted){catalog.value=result;sourceRoutes.value=routes.result?.routes||[];policyDefaults.value=policies.result?.default_templates||{};catalogs.value={route_key:(routes.result?.routes||[]).map(r=>({value:r.key,title:r.label+' · '+r.key}))};}}catch(e){if(mounted)errors.value=[errorText(e)];}}}finally{if(mounted)refreshing.value=false}}
async function loadContinuation(){if(refreshing.value||busy.value)return;busy.value=true;errors.value=[];try{let result;if(continuationKind.value==='operation'){const op=await client.get('/management/operations/'+encodeURIComponent(continuationId.value));const p=op.result?.configuration;if(op.state!=='APPLIED'||!op.result?.native_save_required||!p?.valid||p.revision!==status.current.value.revision)throw Error('STALE_OPERATION');result={config:p.config,base:status.current.value.digest,kind:'operation'};}else{const r=await client.get('/migration/receipts/'+encodeURIComponent(continuationId.value));if(r.state==='READY_CONFIG'&&r.base_digest===status.current.value.digest&&r.proposed_config){result={config:r.proposed_config,base:r.base_digest,kind:'cutover',receipt_id:r.receipt_id}}else if(r.state==='ROLLBACK_FENCED'){const change=r.next_changes.find(c=>c.instance_id===props.pluginId);if(!change||change.expected_digest!==status.current.value.digest)throw Error('STALE_ROLLBACK');const config=clone(status.current.value.config);for(const [key,value] of Object.entries(change.changes))config[key]=typeof value==='object'?{...config[key],...value}:value;draft.value=config;continuation.value=null;return;}else throw Error('CUTOVER_NOT_READY');}if(mounted){continuation.value=result;draft.value=clone(result.config);submitted.value=false;}}catch(e){if(mounted)errors.value=[errorText(e)]}finally{if(mounted)busy.value=false}}
async function save(){if(refreshing.value||busy.value||submitted.value||!draft.value||!draftBase.value||status.error.value)return;errors.value=validate(contract.schemas.Config,draft.value);if(errors.value.length)return;busy.value=true;
  try{if(continuation.value){const c=await client.get('/configuration');if(c.digest!==continuation.value.base)throw Error('STALE_CONFIGURATION');if(continuation.value.kind==='cutover'){const r=await client.get('/migration/receipts/'+encodeURIComponent(continuation.value.receipt_id));if(r.state!=='READY_CONFIG'||r.base_digest!==c.digest||JSON.stringify(r.proposed_config)!==JSON.stringify(continuation.value.config))throw Error('STALE_CUTOVER');}if(mounted){submitted.value=true;saveFollowup(props.pluginId,{receipt:continuation.value.config.configuration_receipt});emit('save',clone(continuation.value.config));}}else await prepareSave(client,draftBase.value,clean(contract.schemas.Config,draft.value),config=>{if(mounted){submitted.value=true;emit('save',config);}})}catch(e){if(mounted)errors.value=e.validationErrors||[errorText(e)];}finally{if(mounted)busy.value=false;}}
onMounted(start);onBeforeUnmount(()=>{mounted=false;draft.value=null;errors.value=[]});
</script>
<template><section class="sb-root sb-app sb-config" aria-label="subscriBetter 配置"><h2>subscriBetter 配置</h2><Status :status="status"/>
  <p class="sb-muted">选择现有服务，配置作品策略与交付范围。保存前会检查冲突、目录及权限。</p>
  <p>服务引用必须来自已有宿主配置。<a href="/#/setting">打开宿主设置</a> · 密钥在管理页的私密写入操作中配置。</p>
  <div class="sb-actions"><VBtn variant="tonal" :disabled="refreshing||busy" @click="refresh">刷新当前值（丢弃未保存编辑）</VBtn><VBtn variant="text" @click="emit('switch')">打开管理页</VBtn></div>
  <p v-if="continuation" class="sb-notice">已自动接续本次配置变更，请确认后保存。刷新当前值可放弃接续。</p>
  <details><summary>高级：手工恢复迁移回执</summary><p>已预检的配置保持不可修改，使用服务器原回执，不生成替代配置。</p><select v-model="continuationKind" aria-label="回执类型"><option value="operation">配置操作</option><option value="cutover">迁移 / 回退</option></select><input v-model="continuationId" aria-label="回执 ID"><button :disabled="refreshing||busy||!continuationId||!status.current.value" @click="loadContinuation">加载回执配置</button></details>
  <div class="sb-config-layout"><nav class="sb-config-nav" aria-label="配置分组"><button v-for="g in groups" :key="g[0]" :aria-current="group===g[0]" @click="group=g[0]">{{g[1]}}</button></nav>
  <div class="sb-config-content"><template v-if="draft"><div v-for="g in groups" :key="g[0]" v-show="group===g[0]"><h3>{{g[1]}}</h3><p v-if="g[0]==='policy'&&catalog" class="sb-muted">当前分类发布版本 {{catalog.revision}}；分类绑定只接受启用且类型匹配的真实 ID。</p><p v-if="g[0]==='permissions'">每项权限独立，默认关闭；同时需要对应规则的同名权限。取消交付本身不删除文件或下载器任务。</p><p v-if="g[0]==='delivery'">映射① Emby 路径 → MP 可读 STRM；映射② STRM 目标 → CD2 内部路径。保留 SSA / VTT / SUP / ZIP 与路径安全；不处理 IDX/SUB、独立字体或许可证附件。</p><template v-if="g[0]==='ownership'"><p v-if="catalogError" class="sb-error">{{catalogError}}</p><Destinations :model-value="draft.destination_templates" :categories="catalog?.categories||[]" :downloaders="downloaders" :paths="paths" :rules="draft.delivery?.rules||[]" :readonly="refreshing||busy||submitted||!!continuation" @update:model-value="draft.destination_templates=$event"/></template><Policies v-if="g[0]==='policy'" :model-value="draft.policy" :categories="catalog?.categories||[]" :defaults="policyDefaults" :revision="catalog?.revision" :readonly="refreshing||busy||submitted||!!continuation" @update:model-value="draft.policy=$event"/><DeliverySettings v-if="g[0]==='delivery'" :model-value="draft.delivery" :api="api" :categories="catalog?.categories||[]" :policies="draft.policy" :policy-names="Object.keys(policyDefaults)" :revision="catalog?.revision" :readonly="refreshing||busy||submitted||!!continuation" @update:model-value="draft.delivery=$event"/><Sources v-if="g[0]==='discovery'" :model-value="draft.discovery" :routes="sourceRoutes" :templates="draft.destination_templates" :readonly="refreshing||busy||submitted||!!continuation" @update:model-value="draft.discovery=$event"/><Field v-for="key in g[2].filter(k=>!['destination_templates','policy','discovery','delivery'].includes(k))" :key="key" :schema="contract.schemas.Config.properties[key]" :name="key" :model-value="draft[key]" :readonly="refreshing||busy||submitted||!!continuation" @update:model-value="draft[key]=$event"/></div></template></div></div>
  <ul v-if="errors.length" role="alert" class="sb-error"><li v-for="e in errors" :key="e">{{e}}</li></ul><p v-if="submitted" role="status">已提交给 MoviePilot，尚未确认生效。重新打开管理页后将自动核对保存结果。</p>
  <div class="sb-actions sb-save-bar"><VBtn color="primary" :loading="busy" :disabled="refreshing||busy||!draft||submitted||!!status.error.value" @click="save">{{continuation?'保存这次配置变更':'保存设置'}}</VBtn><VBtn variant="text" @click="emit('close')">关闭</VBtn></div>
</section></template>
