<script setup>
import {ref,computed,watch,onMounted,onBeforeUnmount,provide} from 'vue';
import {createClient,prepareSave,errorText,unwrap,readFollowup,clearFollowup,saveFollowup} from './client.mjs';
import {contract,clone,clean,validate,initial} from './schema.mjs';
import {canonical} from './legacy.mjs';
import {labels} from './labels.mjs';
import {useStatus} from './status.mjs';
import Field from './Field.vue';
import './style.css';
import PlanSetup from './PlanSetup.vue';
import {mergeDraft,planDraft,settingScopes} from './configuration-draft.mjs';
import LibraryPicker from './LibraryPicker.vue';
import BasicSettings from './BasicSettings.vue';import ScheduleSettings from './ScheduleSettings.vue';import OperationalSettings from './OperationalSettings.vue';import AISettings from './AISettings.vue';
import Policies from './Policies.vue';import Sources from './Sources.vue';
const props=defineProps({api:{type:Object,required:true},pluginId:{type:String,required:true},sourcePluginId:String,initialConfig:{type:Object,default:()=>({})},focus:{type:Object,default:()=>({group:'ownership'})}});
const emit=defineEmits(['save','close','switch','layout','configure','saved','migration','diagnostic','export','stay','context']);
const client=createClient(props.api,props.pluginId,props.sourcePluginId),status=useStatus(client);
const savedDraft=ref(null),draftBase=ref(null),refreshing=ref(false),draft=ref(null),errors=ref([]),busy=ref(false),submitted=ref(false),group=ref(props.focus.group||'ownership'),catalog=ref(null),continuation=ref(null),continuationId=ref(''),continuationKind=ref('operation');let mounted=true;
const credentialBusy=ref(false),credentialPending=ref(false),editing=ref({id:props.focus.id||'',name:'',step:0,scope:props.focus.scope||{}}),planSetup=ref(null),leave=ref(''),draftNotice=ref('');
const cacheKey='subscribetter:draft:'+props.pluginId+':'+group.value;
const childSaves=ref([]),conflicts=ref([]);
const scope=computed(()=>settingScopes[group.value]||[]);
const locked=computed(()=>refreshing.value||busy.value||submitted.value||!!continuation.value);
const title=computed(()=>editing.value.name||props.focus.label||({plans:'下载方案',policy:'质量策略',discovery:'榜单来源',ownership:'运行与自动管理',candidates:'搜索与等待',ai:'名称识别',recovery:'媒体库检查',safety:'维护与安全'}[group.value]||'设置'));
function readConfig(config){const value=clean(contract.schemas.Config,clone(config));for(const [key,model] of [['delivery','DeliveryConfig'],['discovery','DiscoveryConfig']])value[key]={...Object.fromEntries(Object.entries(contract.schemas[model].properties).map(([name,schema])=>[name,initial(schema)])),...value[key]};return value}
function conflictName(path){return path.map(key=>({policy:'质量策略',templates:'策略规则',locks:'所有策略的锁定条件',resolution:'分辨率',destination_templates:'下载方案',save_path:'下载保存到',delivery:'上传与整理',local_root:'从哪里上传'}[key]||labels[key]||draft.value?.destination_templates.find(p=>p.id===key)?.display_name||key)).join(' › ')}
function conflictValue(config,path){const value=path.reduce((v,k)=>Array.isArray(v)?v.find(row=>row.id===k):v?.[k],config);if(value===undefined)return '已移除';if(value===true)return '启用';if(value===false)return '关闭';if(Array.isArray(value)&&value.every(v=>typeof v==='string'))return value.map(v=>labels[v]||v).join(' → ');return typeof value==='object'?JSON.stringify(value):String(value)}
function acceptSaved(c,label){if(!draft.value)return;status.current.value=c;const merged=mergeDraft(savedDraft.value,draft.value,readConfig(c.config),scope.value,{keepLocal:true});draft.value=clean(contract.schemas.Config,merged.config);savedDraft.value=readConfig(c.config);draftBase.value={revision:c.revision,digest:c.digest};conflicts.value=merged.conflicts;if(label)childSaves.value=[...new Set([...childSaves.value,label])];status.refresh();}
function discard(){try{sessionStorage.removeItem(cacheKey)}catch{};draft.value=group.value==='plans'&&editing.value.id?planDraft(draft.value,savedDraft.value,editing.value.id,editing.value.scope):clone(savedDraft.value);performLeave(leave.value)}
function resolveConflicts(){const latest=status.current.value;draft.value=clean(contract.schemas.Config,mergeDraft(savedDraft.value,draft.value,readConfig(latest.config),scope.value,{keepLocal:true}).config);draftBase.value={revision:latest.revision,digest:latest.digest};savedDraft.value=readConfig(latest.config);conflicts.value=[];errors.value=[]}
defineExpose({acceptSaved,requestLeave});
const dirtyAll=computed(()=>!!draft.value&&canonical(draft.value)!==canonical(savedDraft.value||{}));
const dirty=computed(()=>group.value==='plans'&&editing.value.id&&draft.value&&savedDraft.value?canonical(planDraft(savedDraft.value,draft.value,editing.value.id,editing.value.scope))!==canonical(savedDraft.value):dirtyAll.value);
watch(dirty,value=>{if(value)status.saveState.value=''})
function protect(event){if(dirty.value||credentialPending.value||submitted.value){event.preventDefault();event.returnValue=''}}
function requestLeave(action){if(credentialBusy.value||busy.value)return;if(submitted.value){errors.value=['请先核对本次保存结果，再离开此页。'];return}if(dirty.value||credentialPending.value)leave.value=action;else performLeave(action)}
function performLeave(action){leave.value='';if(action==='refresh'){try{sessionStorage.removeItem(cacheKey)}catch{};refresh();}else emit(action)}
function exitPlan(){const component=Array.isArray(planSetup.value)?planSetup.value[0]:planSetup.value;component?.exit();editing.value={name:'',step:0}}
watch([draft,childSaves,editing],()=>{if(!draft.value||!draftBase.value||refreshing.value)return;try{if(dirtyAll.value)sessionStorage.setItem(cacheKey,JSON.stringify({base:draftBase.value,saved:savedDraft.value,draft:clean(contract.schemas.Config,draft.value),childSaves:childSaves.value,editing:editing.value}));else sessionStorage.removeItem(cacheKey)}catch{draftNotice.value='浏览器未能保留草稿，请在关闭前保存。'}},{deep:true});
async function confirmSaved(){const c=await status.refresh();if(c&&status.saveState.value==='设置已保存并确认生效'){draftBase.value={revision:c.revision,digest:c.digest};draft.value=clean(contract.schemas.Config,mergeDraft(savedDraft.value,draft.value,readConfig(c.config),Object.keys(draft.value),{keepLocal:true}).config);savedDraft.value=readConfig(c.config);submitted.value=false;errors.value=[];conflicts.value=[];emit('saved',c,title.value);try{sessionStorage.removeItem(cacheKey)}catch{};return true}errors.value=['保存结果尚未确认。请核对结果，不要再次提交。'];return false}
async function submitNative(config){submitted.value=true;if(typeof props.api.put!=='function'){emit('save',config);return false}const response=unwrap(await props.api.put('plugin/'+encodeURIComponent(props.pluginId),config,{feedback:'silent'}));if(response?.success===false){submitted.value=false;throw Error('宿主拒绝保存')}return confirmSaved()}

const catalogs=ref({});provide('subscribetter:catalogs',catalogs);provide('subscribetter:api',props.api);
const downloaders=ref([]),paths=ref([]),catalogError=ref(''),policyDefaults=ref({}),policyCatalog=ref({}),sourceRoutes=ref([]);
async function readServices(){
 const results=await Promise.allSettled([props.api.get('download/clients',{feedback:'silent'}),props.api.get('download/paths',{feedback:'silent'})]);
 if(!mounted)return;catalogError.value='';
 for(const [i,r] of results.entries()){let data=null;try{data=r.status==='fulfilled'?unwrap(r.value):null}catch{};if(Array.isArray(data)){if(i===0)downloaders.value=data;else paths.value=data.filter(p=>(p.storage||'local')==='local')}else catalogError.value='部分宿主服务或目录暂不可用，现有设置已保留。可检查宿主配置后重新打开。'}
}
async function start(){await refresh();try{const cached=JSON.parse(sessionStorage.getItem(cacheKey)||'null');if(cached?.draft&&cached.saved&&draft.value){const restored=mergeDraft(cached.saved,cached.draft,savedDraft.value,scope.value,{keepLocal:true});draft.value=clean(contract.schemas.Config,restored.config);conflicts.value=restored.conflicts;childSaves.value=Array.isArray(cached.childSaves)?cached.childSaves.filter(s=>typeof s==='string'):[];if(group.value==='plans'&&cached.editing?.id)editing.value=cached.editing;draftNotice.value='已恢复未保存的修改。'}}catch{}readServices();const followup=readFollowup(props.pluginId);if(followup?.operation||followup?.cutover){continuationKind.value=followup.cutover?'cutover':'operation';continuationId.value=followup.cutover||followup.operation;await loadContinuation();if(errors.value.length)clearFollowup(props.pluginId)}}
const permissionGroups=[{title:'成功交付后',fields:[['cleanup_success','清理本地已交付文件','仅清理已经确认成功且符合交付规则的本地文件。'],['cleanup_staging','清理云端暂存副本','仅处理暂存范围内、确认允许清理的副本。']]},{title:'放弃交付后',fields:[['cleanup_abandoned','清理已放弃文件','允许清理已放弃交付的授权文件。']]},{title:'下载器处理',fields:[['remove_downloader_task_enabled','移除下载器任务','允许移除任务记录；是否删除文件由下一项独立控制。'],['delete_downloader_data_enabled','删除下载器数据','允许删除任务关联的数据，请单独核对清理预览。']]}];
async function refresh(){if(refreshing.value||busy.value||credentialBusy.value)return;refreshing.value=true;try{const c=await status.refresh();if(c&&mounted){draftBase.value={revision:c.revision,digest:c.digest};draft.value=readConfig(c.config);savedDraft.value=clone(draft.value);continuation.value=null;submitted.value=!!readFollowup(props.pluginId)?.receipt;errors.value=[];try{const [result,routes,policies]=await Promise.all([client.get('/configuration/categories'),client.get('/discovery/catalog'),client.get('/policies/catalog')]);if(mounted){catalog.value=result;sourceRoutes.value=routes.result?.routes||[];policyCatalog.value=policies.result||{};policyDefaults.value=policyCatalog.value.default_templates||{};catalogs.value={route_key:(routes.result?.routes||[]).map(r=>({value:r.key,title:r.label+' · '+r.key}))};}}catch(e){if(mounted)errors.value=[errorText(e)];}}}finally{if(mounted)refreshing.value=false}}
async function loadContinuation(){if(refreshing.value||busy.value)return;busy.value=true;errors.value=[];try{let result;if(continuationKind.value==='operation'){const op=await client.get('/management/operations/'+encodeURIComponent(continuationId.value));const p=op.result?.configuration;if(op.state!=='APPLIED'||!op.result?.native_save_required||!p?.valid||p.revision!==status.current.value.revision)throw Error('STALE_OPERATION');result={config:p.config,base:status.current.value.digest,kind:'operation'};}else{const r=await client.get('/migration/receipts/'+encodeURIComponent(continuationId.value));if(r.state==='READY_CONFIG'&&r.base_digest===status.current.value.digest&&r.proposed_config){result={config:r.proposed_config,base:r.base_digest,kind:'cutover',receipt_id:r.receipt_id}}else if(r.state==='ROLLBACK_FENCED'){const change=r.next_changes.find(c=>c.instance_id===props.pluginId);if(!change||change.expected_digest!==status.current.value.digest)throw Error('STALE_ROLLBACK');const config=clone(status.current.value.config);for(const [key,value] of Object.entries(change.changes))config[key]=typeof value==='object'?{...config[key],...value}:value;draft.value=config;continuation.value=null;return;}else throw Error('CUTOVER_NOT_READY');}if(mounted){continuation.value=result;draft.value=clone(result.config);submitted.value=false;}}catch(e){if(mounted)errors.value=[errorText(e)]}finally{if(mounted)busy.value=false}}
async function save(){if(credentialBusy.value||credentialPending.value||refreshing.value||busy.value||submitted.value||!draft.value||!draftBase.value||status.error.value||conflicts.value.length)return;const local=group.value==='plans'&&editing.value.id?planDraft(savedDraft.value,draft.value,editing.value.id,editing.value.scope):draft.value;errors.value=validate(contract.schemas.Config,local);if(errors.value.length)return;busy.value=true;
  try{if(continuation.value){const c=await client.get('/configuration');if(c.digest!==continuation.value.base)throw Error('STALE_CONFIGURATION');if(continuation.value.kind==='cutover'){const r=await client.get('/migration/receipts/'+encodeURIComponent(continuation.value.receipt_id));if(r.state!=='READY_CONFIG'||r.base_digest!==c.digest||JSON.stringify(r.proposed_config)!==JSON.stringify(continuation.value.config))throw Error('STALE_CUTOVER');}if(mounted){submitted.value=true;saveFollowup(props.pluginId,{...readFollowup(props.pluginId),receipt:continuation.value.config.configuration_receipt});await submitNative(clone(continuation.value.config));}}else {const latest=await client.get('/configuration');const merged=mergeDraft(savedDraft.value,local,readConfig(latest.config),scope.value);conflicts.value=merged.conflicts;if(conflicts.value.length){status.current.value=latest;errors.value=['这些设置已被其他操作修改，请先核对冲突。'];return false}let prepared;await prepareSave(client,latest,clean(contract.schemas.Config,merged.config),config=>{prepared=config});if(mounted)return await submitNative(prepared)}}catch(e){if(mounted)errors.value=e.validationErrors||[errorText(e)];}finally{if(mounted)busy.value=false;}}
onMounted(()=>{emit('layout',{maxWidth:'1280px'});start();globalThis.window?.addEventListener('beforeunload',protect)});onBeforeUnmount(()=>{globalThis.window?.removeEventListener('beforeunload',protect);mounted=false;draft.value=null;errors.value=[]});
</script>
<template><section class="sb-editor" :aria-label="title">
  <header class="sb-editor-heading"><VBtn variant="text" :disabled="busy||credentialBusy" @click="requestLeave('close')">‹ {{focus.returnLabel||'返回'}}</VBtn><div><h2>{{title}}</h2><span v-if="dirty" class="sb-unsaved">未保存</span></div><VBtn v-if="editing.name" variant="text" :disabled="busy" @click="exitPlan">方案列表</VBtn></header>
  <p v-if="draftNotice" class="sb-notice" role="status">{{draftNotice}}</p>
  <p v-if="continuation" class="sb-notice">已接续本次变更，请确认后保存。</p>
  <p v-if="catalogError" class="sb-warning">{{catalogError}} <VBtn variant="text" @click="readServices">重新读取服务</VBtn></p>
  <p v-if="refreshing&&!draft" role="status">正在读取设置…</p>
  <p v-if="status.error.value" role="alert" class="sb-error">{{status.error.value}} <VBtn variant="text" @click="refresh">重新读取</VBtn></p>
  <div v-if="draft" class="sb-editor-content">
    <template v-if="group==='ownership'"><BasicSettings section="runtime" :model-value="draft" :api="api" :readonly="locked" @update:model-value="draft=$event"/><section class="sb-form-section"><h3>自动升级期限</h3><OperationalSettings group="lifecycle" :model-value="draft.lifecycle" :api="api" :readonly="locked" @update:model-value="draft.lifecycle=$event"/></section></template>
    <template v-else-if="group==='candidates'"><OperationalSettings group="candidates" :model-value="draft.candidates" :api="api" :readonly="locked" @update:model-value="draft.candidates=$event"/><ScheduleSettings :model-value="draft.schedule" :readonly="locked" @update:model-value="draft.schedule=$event"/></template>
    <template v-else-if="group==='ai'"><BasicSettings section="naming" :model-value="draft" :api="api" :readonly="locked" @update:model-value="draft=$event"/><AISettings :model-value="draft.ai_assist" :client="client" :base="draftBase" :status="status" :save-config="save" :saved="!dirty" :save-scope="['名称识别与片名保护设置']" :readonly="locked" @update:model-value="draft.ai_assist=$event" @busy="credentialBusy=$event" @pending="credentialPending=$event"/></template>
    <template v-else-if="group==='recovery'"><section class="sb-form-section"><h3>定期检查的媒体库</h3><LibraryPicker :api="api" :model-value="draft.delivery.libraries" :readonly="locked" @update:model-value="draft.delivery.libraries=$event"/></section><OperationalSettings group="recovery" :model-value="draft.recovery" :api="api" :readonly="locked" @update:model-value="draft.recovery=$event"/><p>单个方案的播放路径可在方案内选择样本检查，无需开启自动追踪。</p><VBtn variant="tonal" @click="emit('configure','plans',{returnLabel:'媒体库检查'})">选择方案检查路径</VBtn></template>
    <template v-else-if="group==='safety'"><section v-for="section in permissionGroups" :key="section.title" class="sb-form-section"><h3>{{section.title}}</h3><label v-for="[key,title,note] in section.fields" :key="key" class="sb-toggle-row"><span><strong>{{title}}</strong><small>{{note}}</small></span><input type="checkbox" :checked="draft.permissions[key]" :disabled="locked" @change="draft.permissions[key]=$event.target.checked"></label></section><OperationalSettings group="safety" :model-value="draft.safety" :api="api" :readonly="locked" @update:model-value="draft.safety=$event"/><section class="sb-form-section"><h3>备份与维护</h3><div class="sb-actions"><VBtn variant="tonal" @click="emit('export')">导出安全配置</VBtn><VBtn variant="tonal" @click="requestLeave('migration')">导入与迁移</VBtn><VBtn variant="text" @click="requestLeave('diagnostic')">高级诊断</VBtn></div></section></template>
    <Policies v-else-if="group==='policy'" :model-value="draft.policy" :client="client" :status="status" :focus="focus" :plans="draft.destination_templates" :archive-bindings="draft.delivery.policy_bindings" :categories="catalog?.categories||[]" :defaults="policyDefaults" :catalog="policyCatalog" @selection="emit('context',$event)" :revision="catalog?.revision" :readonly="locked" @update:model-value="draft.policy=$event"/>
    <PlanSetup v-else-if="group==='plans'" ref="planSetup" :focus="focus" :edit-scope="editing.scope" :baseline="savedDraft" :saving="busy" :submitted="submitted" :save-error="errors" :model-value="draft" :api="api" :client="client" :status="status" :base="draftBase" :categories="catalog?.categories||[]" :downloaders="downloaders" :paths="paths" :policy-names="Object.keys({...policyDefaults,...draft.policy.templates})" :revision="catalog?.revision" :readonly="locked" @editing="editing=$event;emit('context',{id:$event.id,step:$event.step,label:$event.name,scope:$event.scope})" @update:model-value="draft=$event" @save="save" @confirm="confirmSaved" @configure="(group,ctx)=>emit('configure',group,ctx)"/>
    <template v-else-if="group==='discovery'"><Sources :client="client" :saved="savedDraft.discovery" :model-value="draft.discovery" :routes="sourceRoutes" :templates="draft.destination_templates" :readonly="locked" @update:model-value="draft.discovery=$event"/><details class="sb-technical"><summary>历史结果显示</summary><Field name="history_view" :schema="contract.schemas.Config.properties.history_view" :model-value="draft.history_view" :readonly="locked" @update:model-value="draft.history_view=$event"/></details></template>
  </div>
  <section v-if="conflicts.length" class="sb-conflicts" role="alert"><h3>这些设置在编辑期间被修改</h3><p>你的输入仍然保留。确认后会以当前输入保存以下冲突项，其余设置保留最新值。</p><ul><li v-for="path in conflicts" :key="path.join('.')"><strong>{{conflictName(path)}}</strong><div>当前已保存：{{conflictValue(status.current.value?.config,path)}}</div><div>我的修改：{{conflictValue(draft,path)}}</div></li></ul><VBtn variant="tonal" @click="resolveConflicts">已核对，保留我的修改</VBtn></section>
  <ul v-if="errors.length&&!editing.name" role="alert" class="sb-error"><li v-for="e in errors" :key="e">{{e}}</li></ul>
  <footer v-if="!editing.name" class="sb-editor-footer"><span role="status">{{submitted?'保存结果待确认':busy?'正在保存…':dirty?'修改尚未保存':status.saveState.value||'与已保存设置一致'}}</span><VBtn v-if="submitted" variant="tonal" :disabled="busy" @click="confirmSaved">核对保存结果</VBtn><VBtn v-else-if="!['ai','plans'].includes(group)" color="primary" :loading="busy" :disabled="credentialBusy||credentialPending||refreshing||busy||!draft||!!status.error.value||!!conflicts.length" @click="save">{{continuation?'保存这次变更':'保存'+(group==='policy'?'策略':'设置')}}</VBtn></footer>
  <v-dialog :model-value="!!leave" max-width="520" persistent><section class="sb-root sb-dialog"><h2>保留这次修改吗？</h2><p>尚未保存的修改可以保留为本浏览器草稿，或放弃。</p><p v-if="credentialPending">本次未保存的地址和密钥不会保留。</p><p v-if="childSaves.length">本次已保存的{{childSaves.join('、')}}仍然生效，放弃这里的修改不会撤销它们。</p><div class="sb-actions"><VBtn color="primary" @click="leave='';emit('stay')">继续编辑</VBtn><VBtn variant="text" @click="performLeave(leave)">保留草稿并返回</VBtn><VBtn variant="text" @click="discard">放弃本页修改</VBtn></div></section></v-dialog>
</section></template>
