<script setup>
import {ref,computed,watch,onMounted,onBeforeUnmount,provide} from 'vue';
import {createClient,prepareSave,errorText,unwrap,readFollowup,clearFollowup,saveFollowup} from './client.mjs';
import {contract,clone,clean,validate,initial} from './schema.mjs';
import {canonical} from './legacy.mjs';
import {useStatus} from './status.mjs';
import Status from './Status.vue';import Field from './Field.vue';
import './style.css';
import PlanSetup from './PlanSetup.vue';
import {changedGroups} from './plan-flow.mjs';
import BasicSettings from './BasicSettings.vue';import ScheduleSettings from './ScheduleSettings.vue';import OperationalSettings from './OperationalSettings.vue';import AISettings from './AISettings.vue';
import Policies from './Policies.vue';import Sources from './Sources.vue';import DeliverySettings from './DeliverySettings.vue';
const props=defineProps({api:{type:Object,required:true},pluginId:{type:String,required:true},sourcePluginId:String,initialConfig:{type:Object,default:()=>({})}});
const emit=defineEmits(['save','close','switch','layout']);
const client=createClient(props.api,props.pluginId,props.sourcePluginId),status=useStatus(client);
const savedDraft=ref(null),draftBase=ref(null),refreshing=ref(false),draft=ref(null),errors=ref([]),busy=ref(false),submitted=ref(false),group=ref('ownership'),catalog=ref(null),continuation=ref(null),continuationId=ref(''),continuationKind=ref('operation');let mounted=true;
const content=ref(null),credentialBusy=ref(false),credentialPending=ref(false),editing=ref({name:'',step:0}),planSetup=ref(null),leave=ref(''),draftNotice=ref('');
const cacheKey='subscribetter:draft:'+props.pluginId;
const dirty=computed(()=>!!draft.value&&canonical(draft.value)!==canonical(savedDraft.value||{}));
function protect(event){if(dirty.value||credentialPending.value){event.preventDefault();event.returnValue=''}}
function requestLeave(action){if(credentialBusy.value||busy.value)return;if(dirty.value||credentialPending.value)leave.value=action;else performLeave(action)}
function performLeave(action){leave.value='';if(action==='refresh'){try{sessionStorage.removeItem(cacheKey)}catch{};refresh();}else emit(action)}
function exitPlan(){const component=Array.isArray(planSetup.value)?planSetup.value[0]:planSetup.value;component?.exit();editing.value={name:'',step:0}}
watch(draft,()=>{if(!draft.value||!draftBase.value||refreshing.value)return;try{if(dirty.value)sessionStorage.setItem(cacheKey,JSON.stringify({base:draftBase.value,draft:clean(contract.schemas.Config,draft.value)}));else sessionStorage.removeItem(cacheKey)}catch{draftNotice.value='浏览器未能保留草稿，请在关闭前保存。'}},{deep:true});
async function confirmSaved(){const c=await status.refresh();if(c&&status.saveState.value==='设置已保存并确认生效'){draftBase.value={revision:c.revision,digest:c.digest};draft.value=clean(contract.schemas.Config,clone(c.config));savedDraft.value=clone(draft.value);submitted.value=false;errors.value=[];try{sessionStorage.removeItem(cacheKey)}catch{};return true}errors.value=['保存结果尚未确认。请核对结果，不要再次提交。'];return false}
async function submitNative(config){submitted.value=true;if(typeof props.api.put!=='function'){emit('save',config);return false}const response=unwrap(await props.api.put('plugin/'+encodeURIComponent(props.pluginId),config,{feedback:'silent'}));if(response?.success===false){submitted.value=false;throw Error('宿主拒绝保存')}return confirmSaved()}

function selectGroup(key){group.value=key;if(content.value)content.value.scrollTop=0}
const catalogs=ref({});provide('subscribetter:catalogs',catalogs);provide('subscribetter:api',props.api);
const downloaders=ref([]),paths=ref([]),catalogError=ref(''),policyDefaults=ref({}),sourceRoutes=ref([]);
async function readServices(){
 const results=await Promise.allSettled([props.api.get('download/clients',{feedback:'silent'}),props.api.get('download/paths',{feedback:'silent'})]);
 if(!mounted)return;catalogError.value='';
 for(const [i,r] of results.entries()){let data=null;try{data=r.status==='fulfilled'?unwrap(r.value):null}catch{};if(Array.isArray(data)){if(i===0)downloaders.value=data;else paths.value=data.filter(p=>(p.storage||'local')==='local')}else catalogError.value='部分宿主服务或目录暂不可用，现有设置已保留。可检查宿主配置后重新打开。'}
}
async function start(){const focus=readFollowup(props.pluginId)?.group;if(groups.some(g=>g[0]===focus))group.value=focus;await refresh();try{const cached=JSON.parse(sessionStorage.getItem(cacheKey)||'null');if(cached?.draft&&cached.base?.digest===draftBase.value?.digest){draft.value=clean(contract.schemas.Config,cached.draft);draftNotice.value='已恢复此浏览器中的未保存草稿。'}else if(cached)draftNotice.value='发现旧草稿，但服务端配置已变化；未覆盖当前设置。'}catch{}readServices();const followup=readFollowup(props.pluginId);if(followup?.operation){continuationId.value=followup.operation;await loadContinuation();if(errors.value.length)clearFollowup(props.pluginId)}}
const permissionGroups=[{title:'成功交付后',fields:[['cleanup_success','清理本地已交付文件','仅清理已经确认成功且符合交付规则的本地文件。'],['cleanup_staging','清理云端暂存副本','仅处理暂存范围内、确认允许清理的副本。']]},{title:'放弃交付后',fields:[['cleanup_abandoned','清理已放弃文件','允许清理已放弃交付的授权文件。']]},{title:'下载器处理',fields:[['remove_downloader_task_enabled','移除下载器任务','允许移除任务记录；是否删除文件由下一项独立控制。'],['delete_downloader_data_enabled','删除下载器数据','允许删除任务关联的数据，请单独核对清理预览。']]}];
const groups=[['plans','下载与入库方案',[]],['ownership','基本设置与自动接管',['enabled','dry_run','auto_types','passive_libraries','destination_templates','enhance_host_meta','meta_protected_names']],['policy','独立策略',['policy']],['lifecycle','自动升级期限',['lifecycle']],['candidates','站点与搜索',['candidates']],['schedule','等待与更换版本',['schedule']],['delivery','媒体库与整理路径',['delivery']],['recovery','扫描与恢复',['recovery']],['permissions','清理权限',['permissions']],['safety','安全与容量',['safety']],['discovery','榜单与 RSS',['discovery','history_view']],['ai','AI 名称辅助',['ai_assist']]];
async function refresh(){if(refreshing.value||busy.value||credentialBusy.value)return;refreshing.value=true;try{const c=await status.refresh();if(c&&mounted){draftBase.value={revision:c.revision,digest:c.digest};draft.value=clean(contract.schemas.Config,clone(c.config));for(const [key,model] of [['delivery','DeliveryConfig'],['discovery','DiscoveryConfig']])draft.value[key]={...Object.fromEntries(Object.entries(contract.schemas[model].properties).map(([name,schema])=>[name,initial(schema)])),...draft.value[key]};savedDraft.value=clone(draft.value);continuation.value=null;submitted.value=false;errors.value=[];try{const [result,routes,policies]=await Promise.all([client.get('/configuration/categories'),client.get('/discovery/catalog'),client.get('/policies/catalog')]);if(mounted){catalog.value=result;sourceRoutes.value=routes.result?.routes||[];policyDefaults.value=policies.result?.default_templates||{};catalogs.value={route_key:(routes.result?.routes||[]).map(r=>({value:r.key,title:r.label+' · '+r.key}))};}}catch(e){if(mounted)errors.value=[errorText(e)];}}}finally{if(mounted)refreshing.value=false}}
async function loadContinuation(){if(refreshing.value||busy.value)return;busy.value=true;errors.value=[];try{let result;if(continuationKind.value==='operation'){const op=await client.get('/management/operations/'+encodeURIComponent(continuationId.value));const p=op.result?.configuration;if(op.state!=='APPLIED'||!op.result?.native_save_required||!p?.valid||p.revision!==status.current.value.revision)throw Error('STALE_OPERATION');result={config:p.config,base:status.current.value.digest,kind:'operation'};}else{const r=await client.get('/migration/receipts/'+encodeURIComponent(continuationId.value));if(r.state==='READY_CONFIG'&&r.base_digest===status.current.value.digest&&r.proposed_config){result={config:r.proposed_config,base:r.base_digest,kind:'cutover',receipt_id:r.receipt_id}}else if(r.state==='ROLLBACK_FENCED'){const change=r.next_changes.find(c=>c.instance_id===props.pluginId);if(!change||change.expected_digest!==status.current.value.digest)throw Error('STALE_ROLLBACK');const config=clone(status.current.value.config);for(const [key,value] of Object.entries(change.changes))config[key]=typeof value==='object'?{...config[key],...value}:value;draft.value=config;continuation.value=null;return;}else throw Error('CUTOVER_NOT_READY');}if(mounted){continuation.value=result;draft.value=clone(result.config);submitted.value=false;}}catch(e){if(mounted)errors.value=[errorText(e)]}finally{if(mounted)busy.value=false}}
async function save(){if(credentialBusy.value||credentialPending.value||refreshing.value||busy.value||submitted.value||!draft.value||!draftBase.value||status.error.value)return;errors.value=validate(contract.schemas.Config,draft.value);if(errors.value.length)return;busy.value=true;
  try{if(continuation.value){const c=await client.get('/configuration');if(c.digest!==continuation.value.base)throw Error('STALE_CONFIGURATION');if(continuation.value.kind==='cutover'){const r=await client.get('/migration/receipts/'+encodeURIComponent(continuation.value.receipt_id));if(r.state!=='READY_CONFIG'||r.base_digest!==c.digest||JSON.stringify(r.proposed_config)!==JSON.stringify(continuation.value.config))throw Error('STALE_CUTOVER');}if(mounted){submitted.value=true;saveFollowup(props.pluginId,{receipt:continuation.value.config.configuration_receipt});await submitNative(clone(continuation.value.config));}}else {let prepared;await prepareSave(client,draftBase.value,clean(contract.schemas.Config,draft.value),config=>{prepared=config});if(mounted)return await submitNative(prepared)}}catch(e){if(mounted)errors.value=e.validationErrors||[errorText(e)];}finally{if(mounted)busy.value=false;}}
onMounted(()=>{emit('layout',{maxWidth:'1280px'});start();globalThis.window?.addEventListener('beforeunload',protect)});onBeforeUnmount(()=>{globalThis.window?.removeEventListener('beforeunload',protect);mounted=false;draft.value=null;errors.value=[]});
</script>
<template><section class="sb-root sb-app sb-config" :class="{'sb-config-focused':editing.name}" aria-label="subscriBetter 配置"><header class="sb-heading"><div><small v-if="editing.name">下载与入库方案</small><h2>{{editing.name||'设置'}}</h2></div><Status :status="status"/><VBtn v-if="editing.name" variant="text" :disabled="busy||credentialBusy" @click="exitPlan">返回方案列表</VBtn><VBtn v-else variant="text" :disabled="credentialBusy" @click="requestLeave('switch')">返回工作台</VBtn></header>
  <main ref="content" class="sb-app-content"><details v-if="!editing.name" class="sb-technical"><summary>配置帮助与重新读取</summary><p>保存前会检查关联关系、目录和权限。<a href="/#/setting">打开 MoviePilot 服务设置</a>；AI 地址与密钥在 AI 名称辅助中配置。</p><VBtn variant="text" :disabled="credentialBusy||refreshing||busy" @click="requestLeave('refresh')">刷新当前值（丢弃未保存编辑）</VBtn></details>
  <p v-if="continuation" class="sb-notice">已自动接续本次配置变更，请确认后保存。刷新当前值可放弃接续。</p>
  <p v-if="draftNotice&&!editing.name" class="sb-notice">{{draftNotice}}</p><label v-if="!editing.name" class="sb-config-select">设置分组<select :value="group" @change="selectGroup($event.target.value)"><option v-for="g in groups" :key="g[0]" :value="g[0]">{{g[1]}}</option></select></label><div class="sb-config-layout"><nav v-if="!editing.name" class="sb-config-nav" aria-label="配置分组"><button v-for="g in groups" :key="g[0]" :aria-current="group===g[0]" @click="selectGroup(g[0])">{{g[1]}}</button></nav>
  <div class="sb-config-content"><template v-if="draft"><div v-for="g in groups" :key="g[0]" :hidden="group!==g[0]"><h3 v-if="g[0]!=='plans'">{{g[1]}}</h3><template v-if="g[0]==='ownership'"><p v-if="catalogError" class="sb-error">{{catalogError}}</p><VBtn variant="tonal" @click="selectGroup('plans')">连续配置下载与入库方案</VBtn><BasicSettings :model-value="draft" :api="api" :categories="catalog?.categories||[]" :downloaders="downloaders" :paths="paths" :readonly="refreshing||busy||submitted||!!continuation" @update:model-value="draft=$event"/></template><PlanSetup ref="planSetup" :baseline="savedDraft" :saving="busy" :submitted="submitted" :save-error="errors" @editing="editing=$event" v-if="g[0]==='plans'" :model-value="draft" :api="api" :client="client" :status="status" :base="draftBase" :categories="catalog?.categories||[]" :downloaders="downloaders" :paths="paths" :policy-names="Object.keys(policyDefaults)" :revision="catalog?.revision" :readonly="refreshing||busy||submitted||!!continuation" @update:model-value="draft=$event" @save="save" @configure="selectGroup"/><Policies v-if="g[0]==='policy'" :model-value="draft.policy" :categories="catalog?.categories||[]" :defaults="policyDefaults" :revision="catalog?.revision" :readonly="refreshing||busy||submitted||!!continuation" @update:model-value="draft.policy=$event"/><DeliverySettings v-if="g[0]==='delivery'" :model-value="draft.delivery" :api="api" :client="client" :status="status" :saved="canonical(draft.delivery)===canonical(status.current.value?.config.delivery||{})" :templates="draft.destination_templates" :categories="catalog?.categories||[]" :policies="draft.policy" :policy-names="Object.keys(policyDefaults)" :revision="catalog?.revision" :readonly="refreshing||busy||submitted||!!continuation" @update:model-value="draft.delivery=$event" @configure="selectGroup"/><Sources v-if="g[0]==='discovery'" :model-value="draft.discovery" :routes="sourceRoutes" :templates="draft.destination_templates" :readonly="refreshing||busy||submitted||!!continuation" @update:model-value="draft.discovery=$event"/><template v-if="g[0]==='permissions'"><p class="sb-muted">删除权限默认关闭；还需要交付规则授予同名权限。取消交付本身不会删除文件。</p><section v-for="section in permissionGroups" :key="section.title" class="sb-form-section"><h4>{{section.title}}</h4><label v-for="[key,title,note] in section.fields" :key="key" class="sb-toggle-row"><span><strong>{{title}}</strong><small>{{note}}</small></span><input type="checkbox" :checked="draft.permissions[key]" :disabled="refreshing||busy||submitted||!!continuation" @change="draft.permissions[key]=$event.target.checked"></label></section></template>
  <ScheduleSettings v-if="g[0]==='schedule'" :model-value="draft.schedule" :readonly="refreshing||busy||submitted||!!continuation" @update:model-value="draft.schedule=$event"/>
  <OperationalSettings v-if="['candidates','lifecycle','recovery','safety'].includes(g[0])" :group="g[0]" :model-value="draft[g[0]]" :api="api" :readonly="refreshing||busy||submitted||!!continuation" @update:model-value="draft[g[0]]=$event"/>
  <AISettings v-if="g[0]==='ai'" :model-value="draft.ai_assist" :client="client" :base="draftBase" :status="status" :save-config="save" :save-scope="changedGroups(savedDraft,draft).map(key=>groups.find(g=>g[2].includes(key))?.[1]||key)" :saved="canonical(draft.ai_assist)===canonical(status.current.value?.config.ai_assist||{})" :readonly="refreshing||busy||submitted||!!continuation" @update:model-value="draft.ai_assist=$event" @busy="credentialBusy=$event" @pending="credentialPending=$event"/>
  <details v-if="g[0]==='discovery'" class="sb-technical"><summary>历史显示选项</summary><Field name="history_view" :schema="contract.schemas.Config.properties.history_view" :model-value="draft.history_view" :readonly="refreshing||busy||submitted||!!continuation" @update:model-value="draft.history_view=$event"/></details></div></template></div></div>
  <details v-if="!editing.name"><summary>高级：手工恢复迁移回执</summary><p>已预检的配置保持不可修改，使用服务器原回执，不生成替代配置。</p><select v-model="continuationKind" aria-label="回执类型"><option value="operation">配置操作</option><option value="cutover">迁移 / 回退</option></select><input v-model="continuationId" aria-label="回执 ID"><button :disabled="refreshing||busy||!continuationId||!status.current.value" @click="loadContinuation">加载回执配置</button></details>
  <ul v-if="errors.length&&!editing.name" role="alert" class="sb-error"><li v-for="e in errors" :key="e">{{e}}</li></ul><p v-if="submitted&&!editing.name" role="status">已提交给 MoviePilot，等待确认生效。</p><VBtn v-if="submitted" variant="tonal" :disabled="busy" @click="confirmSaved">核对保存结果</VBtn>
  </main><div v-if="!editing.name" class="sb-actions sb-save-bar"><VBtn v-if="group!=='ai'" color="primary" :loading="busy" :disabled="credentialBusy||credentialPending||refreshing||busy||!draft||submitted||!!status.error.value" @click="save">{{continuation?'保存这次配置变更':'保存设置'}}</VBtn><VBtn variant="text" :disabled="credentialBusy" @click="requestLeave('close')">关闭</VBtn></div>
<v-dialog :model-value="!!leave" max-width="440" persistent><section class="sb-root sb-dialog"><h2>尚有未保存的修改</h2><p>{{draftNotice.includes('未能')?'当前浏览器无法保留草稿，离开会丢失修改。':'关闭后可在当前浏览器恢复普通配置草稿。'}}尚未保存的服务地址和密钥不会保留。</p><div class="sb-actions"><VBtn color="primary" @click="leave=''">继续编辑</VBtn><VBtn variant="text" @click="performLeave(leave)">{{leave==='refresh'?'放弃草稿并重新读取':'保留草稿并离开'}}</VBtn></div></section></v-dialog></section></template>
