<script setup>
import {ref,onMounted,onBeforeUnmount} from 'vue';import {contract,initial} from './schema.mjs';import {unwrap,errorText} from './client.mjs';import Field from './Field.vue';import LibraryPicker from './LibraryPicker.vue';import PathInput from './PathInput.vue';import MappingCheck from './MappingCheck.vue';
const props=defineProps({modelValue:Object,api:Object,client:Object,status:Object,saved:Boolean,templates:Array,categories:Array,policies:Object,policyNames:Array,revision:Number,readonly:Boolean});const emit=defineEmits(['update:modelValue']);const services=ref([]),plugins=ref([]),libraries=ref({}),busy=ref({}),errors=ref({}),category=ref(''),binding=ref(''),summaryPlan=ref('');let alive=true;
const savedMappingIds=new Set(props.modelValue.mappings.map(m=>m.id)),savedRuleIds=new Set(props.modelValue.rules.map(r=>r.id));
const adapters=source=>plugins.value.filter(p=>(p.source_plugin_id||p.id)===source);
const update=change=>emit('update:modelValue',{...props.modelValue,...change});
function next(items,prefix){let i=1;while(items.some(r=>r.id===prefix+i))i++;return prefix+i}
function change(section,index,key,value){const row={...props.modelValue[section][index],[key]:value};if(section==='mappings')row.revision='ui-'+Date.now();update({[section]:props.modelValue[section].map((r,i)=>i===index?row:r)})}
async function readLibraries(service){if(!service||busy.value[service])return;busy.value={...busy.value,[service]:true};errors.value={...errors.value,[service]:''};try{const data=unwrap(await props.api.get('mediaserver/library',{params:{server:service},feedback:'silent'}));if(!Array.isArray(data))throw Error('LIBRARY_LIST_UNAVAILABLE');if(alive)libraries.value={...libraries.value,[service]:data}}catch(e){if(alive)errors.value={...errors.value,[service]:errorText(e)}}finally{if(alive)busy.value={...busy.value,[service]:false}}}
async function start(){try{const rows=unwrap(await props.api.get('plugin/',{params:{state:'installed',max_results:200},feedback:'silent'}));if(alive&&Array.isArray(rows))plugins.value=rows.filter(p=>typeof p.id==='string')}catch{if(alive)errors.value={...errors.value,services:'插件实例暂不可用，已保存选择保留。'}};try{const data=unwrap(await props.api.get('mediaserver/clients',{feedback:'silent'}));if(!Array.isArray(data))throw Error('MEDIA_SERVICES_UNAVAILABLE');if(alive)services.value=data.filter(s=>String(s.type).toLowerCase()==='emby')}catch(e){if(alive)errors.value={...errors.value,services:errorText(e)}}if(alive)for(const name of new Set(props.modelValue.mappings.map(m=>m.emby_service).filter(Boolean)))readLibraries(name)}
function service(index,value){const rows=props.modelValue.mappings.map((r,i)=>i===index?{...r,emby_service:value,library_id:'',revision:'ui-'+Date.now()}:r);update({mappings:rows});readLibraries(value)}
function library(index,id){const row=props.modelValue.mappings[index],selected={...props.modelValue.libraries,[row.emby_service]:[...new Set([...(props.modelValue.libraries[row.emby_service]||[]),id])]};update({libraries:selected,mappings:props.modelValue.mappings.map((r,i)=>i===index?{...r,library_id:id,revision:'ui-'+Date.now()}:r)})}
function bind(){if(category.value&&binding.value)update({policy_bindings:{...props.modelValue.policy_bindings,[category.value]:binding.value},classification_revision:props.revision||props.modelValue.classification_revision})}
function unbind(key){const bindings={...props.modelValue.policy_bindings};delete bindings[key];update({policy_bindings:bindings})}
function scopeAdd(){const key=next(Object.keys(props.modelValue.cloud_scopes).map(id=>({id})),'云盘范围 ');update({cloud_scopes:{...props.modelValue.cloud_scopes,[key]:{...initial(contract.schemas.CloudScope),root:'/',allowed_prefixes:[],p115_parents:{}}}})}
function scopeChange(key,name,value){update({cloud_scopes:{...props.modelValue.cloud_scopes,[key]:{...props.modelValue.cloud_scopes[key],[name]:value}}})}
function scopeRemove(key){const scopes={...props.modelValue.cloud_scopes};delete scopes[key];update({cloud_scopes:scopes})}
function add(section,schema,prefix){update({[section]:[...props.modelValue[section],{...initial(contract.schemas[schema]),id:next(props.modelValue[section],prefix),...(section==='mappings'?{revision:'ui-'+Date.now()}: {})}]})}
onMounted(start);onBeforeUnmount(()=>{alive=false});
</script>
<template><section aria-label="媒体库与交付设置"><h3>媒体库与路径映射</h3><p class="sb-muted">方案连接下载器、交付规则和媒体库。下方修改共用同一份草稿，保存时检查关联关系。</p><p v-if="errors.services" class="sb-error">{{errors.services}} 已有设置保留。</p>
 <section v-if="templates?.length" class="sb-form-section"><h4>方案关联概览</h4><label>查看下载与入库方案<select v-model="summaryPlan"><option value="">请选择方案查看路径与关联</option><option v-for="t in templates" :key="t.id" :value="t.id">{{categories?.find(c=>c.id===t.category_id)?.name||'待选择分类'}} · {{t.id}}</option></select></label><div v-for="t in templates.filter(t=>t.id===summaryPlan)" :key="t.id" class="sb-plan-summary"><strong>{{categories?.find(c=>c.id===t.category_id)?.name||'待选择分类'}} · {{t.downloader}}</strong><small>方案：{{t.id}}</small><p class="sb-value">下载目录：{{t.save_path}}</p><template v-if="modelValue.rules.find(r=>r.id===t.organized_rule)"><p>交付规则：{{t.organized_rule}} · {{modelValue.rules.find(r=>r.id===t.organized_rule).enabled?'已启用':'未启用'}}</p><p class="sb-value">暂存：{{modelValue.rules.find(r=>r.id===t.organized_rule).staging_root}}<br>整理入口：{{modelValue.rules.find(r=>r.id===t.organized_rule).incoming_root}}</p><p>关联媒体库：{{modelValue.mappings.filter(m=>m.cloud_scope_id===modelValue.rules.find(r=>r.id===t.organized_rule).cloud_scope_id).map(m=>libraries[m.emby_service]?.find(l=>String(l.id)===m.library_id)?.name||'已保存的媒体库，名称暂不可用').join('、')||'尚未建立映射'}}</p></template><p v-else>尚未关联有效交付规则。请在“基本设置与自动接管”的同名方案中选择规则。</p></div></section><div class="sb-section-heading"><h3>1 · 云盘范围</h3><VBtn variant="tonal" :disabled="readonly" @click="scopeAdd">添加云盘范围</VBtn></div>
 <p v-if="!Object.keys(modelValue.cloud_scopes).length" class="sb-muted">尚未绑定 CD2 与 115 服务。</p><details v-for="(scope,key) in modelValue.cloud_scopes" :key="key" class="sb-setting-card"><summary>{{key}} · {{scope.root}}</summary><p class="sb-muted">这里引用已运行的 CD2 / 115 适配插件实例，不填写登录凭据。从对应类型的已安装实例中选择；保存和运行时会核实引用及适配能力。</p><div class="sb-grid"><label>CD2 插件实例<select :value="scope.cd2_plugin" :disabled="readonly" @change="scopeChange(key,'cd2_plugin',$event.target.value)"><option value="">选择已安装实例</option><option v-if="scope.cd2_plugin&&!adapters('CloudDriveDisk').some(p=>p.id===scope.cd2_plugin)" :value="scope.cd2_plugin">{{scope.cd2_plugin}}（暂不可用）</option><option v-for="p in adapters('CloudDriveDisk')" :key="p.id" :value="p.id">{{p.plugin_name||p.id}}</option></select></label><label>115 插件实例<select :value="scope.p115_plugin" :disabled="readonly" @change="scopeChange(key,'p115_plugin',$event.target.value)"><option value="">选择已安装实例</option><option v-if="scope.p115_plugin&&!adapters('P115Disk').some(p=>p.id===scope.p115_plugin)" :value="scope.p115_plugin">{{scope.p115_plugin}}（暂不可用）</option><option v-for="p in adapters('P115Disk')" :key="p.id" :value="p.id">{{p.plugin_name||p.id}}</option></select></label><PathInput label="云盘根目录（CD2 内部路径）" :model-value="scope.root" :readonly="readonly" @update:model-value="scopeChange(key,'root',$event)"/><label class="sb-wide">允许写入的路径（每行一个）<textarea :value="scope.allowed_prefixes.join('\n')" :disabled="readonly" @input="scopeChange(key,'allowed_prefixes',$event.target.value.split('\n').map(s=>s.trim()).filter(Boolean))"/></label></div><details class="sb-technical"><summary>115 父目录映射</summary><p class="sb-muted">云盘路径对应 115 文件夹编号；仅配置秒传需要的目标。</p><Field name="p115_parents" :schema="contract.schemas.CloudScope.properties.p115_parents" :model-value="scope.p115_parents" :readonly="readonly" @update:model-value="scopeChange(key,'p115_parents',$event)"/></details><VBtn color="error" variant="text" :disabled="readonly" @click="scopeRemove(key)">移除此范围</VBtn></details>
 <div class="sb-section-heading"><h3>2 · 媒体库与两段映射</h3><VBtn variant="tonal" :disabled="readonly" @click="add('mappings','Mapping','媒体库映射 ')">添加媒体库映射</VBtn></div>
 <details v-for="(m,index) in modelValue.mappings" :key="index" class="sb-setting-card"><summary>{{m.id}} · {{libraries[m.emby_service]?.find(l=>String(l.id)===m.library_id)?.name||m.emby_service||'选择媒体库'}}</summary><div class="sb-grid"><label>映射名称<input :value="m.id" :disabled="readonly||savedMappingIds.has(m.id)" @input="change('mappings',index,'id',$event.target.value)"></label><label>Emby 服务<select :value="m.emby_service" :disabled="readonly" @change="service(index,$event.target.value)"><option value="">选择服务</option><option v-if="m.emby_service&&!services.some(s=>s.name===m.emby_service)" :value="m.emby_service">{{m.emby_service}}（暂不可用）</option><option v-for="s in services" :key="s.name" :value="s.name">{{s.name}}</option></select></label><label>媒体库<select :value="m.library_id" :disabled="readonly||busy[m.emby_service]" @change="library(index,$event.target.value)"><option value="">{{busy[m.emby_service]?'正在读取…':'选择媒体库'}}</option><option v-if="m.library_id&&!libraries[m.emby_service]?.some(l=>String(l.id)===m.library_id)" :value="m.library_id">当前媒体库（暂不可用）</option><option v-for="l in libraries[m.emby_service]||[]" :key="l.id" :value="String(l.id)">{{l.name}}</option></select></label><label>云盘范围<select :value="m.cloud_scope_id" :disabled="readonly" @change="change('mappings',index,'cloud_scope_id',$event.target.value)"><option value="">选择范围</option><option v-for="(_,name) in modelValue.cloud_scopes" :key="name">{{name}}</option></select></label></div><p v-if="errors[m.emby_service]" class="sb-error">{{errors[m.emby_service]}} <VBtn variant="text" @click="readLibraries(m.emby_service)">重读媒体库</VBtn></p>
 <div class="sb-path-mapping"><PathInput label="Emby 中的 STRM 路径前缀" :model-value="m.emby_prefix" :readonly="readonly" @update:model-value="change('mappings',index,'emby_prefix',$event)"/><span class="sb-mapping-arrow" aria-hidden="true">→</span><PathInput label="MP 可以读取的 STRM 路径前缀" :browse="true" :model-value="m.local_strm_prefix" :readonly="readonly" @update:model-value="change('mappings',index,'local_strm_prefix',$event)"/></div><div class="sb-path-mapping"><PathInput label="STRM 内容中的播放路径前缀" :model-value="m.playback_prefix" :readonly="readonly" @update:model-value="change('mappings',index,'playback_prefix',$event)"/><span class="sb-mapping-arrow" aria-hidden="true">→</span><PathInput label="CD2 内部文件路径前缀" :model-value="m.cd2_prefix" :readonly="readonly" @update:model-value="change('mappings',index,'cd2_prefix',$event)"/></div><MappingCheck v-if="client&&status" :mapping="m" :client="client" :status="status" :saved="saved"/><details class="sb-technical"><summary>高级映射条件</summary><Field v-for="key in ['max_strm_bytes','allow_direct','media_source','episode_group']" :key="key" :name="key" :schema="contract.schemas.Mapping.properties[key]" :model-value="m[key]" :readonly="readonly" @update:model-value="change('mappings',index,key,$event)"/></details><VBtn variant="text" color="error" :disabled="readonly" @click="update({mappings:modelValue.mappings.filter((_,i)=>i!==index)})">移除此映射</VBtn></details>
 <section class="sb-form-section"><h3>媒体库扫描范围</h3><LibraryPicker :api="api" :model-value="modelValue.libraries" :readonly="readonly" @update:model-value="update({libraries:$event})"/><p class="sb-muted">取消勾选前请检查关联路径映射，保存时会核对引用。</p></section>
 <div class="sb-section-heading"><h3>3 · 本地文件 → 115 → 整理入口</h3><VBtn variant="tonal" :disabled="readonly" @click="add('rules','DeliveryRule','交付规则 ')">添加交付规则</VBtn></div><details v-for="(r,index) in modelValue.rules" :key="index" class="sb-setting-card"><summary>{{r.id}} · {{r.enabled?'已启用':'未启用'}}</summary><div class="sb-grid"><label>规则名称<input :value="r.id" :disabled="readonly||savedRuleIds.has(r.id)" @input="change('rules',index,'id',$event.target.value)"></label><label>云盘范围<select :value="r.cloud_scope_id" :disabled="readonly" @change="change('rules',index,'cloud_scope_id',$event.target.value)"><option value="">选择范围</option><option v-for="(_,name) in modelValue.cloud_scopes" :key="name">{{name}}</option></select></label><PathInput label="本地监控目录" :browse="true" :model-value="r.local_root" :readonly="readonly" @update:model-value="change('rules',index,'local_root',$event)"/><PathInput label="115 暂存目录（监控范围外）" :model-value="r.staging_root" :readonly="readonly" @update:model-value="change('rules',index,'staging_root',$event)"/><PathInput label="Symedia 接收入口" :model-value="r.incoming_root" :readonly="readonly" @update:model-value="change('rules',index,'incoming_root',$event)"/><label class="sb-wide">消费者监控范围（每行一个）<textarea :value="r.consumer_roots.join('\n')" :disabled="readonly" @input="change('rules',index,'consumer_roots',$event.target.value.split('\n').map(v=>v.trim()).filter(Boolean))"/></label></div><label class="sb-inline"><input type="checkbox" :checked="r.enabled" :disabled="readonly" @change="change('rules',index,'enabled',$event.target.checked)">启用规则</label><details class="sb-technical"><summary>扫描、普通上传、通知与独立清理权限</summary><Field v-for="key in Object.keys(contract.schemas.DeliveryRule.properties).filter(k=>!['id','enabled','cloud_scope_id','local_root','staging_root','incoming_root','consumer_roots'].includes(k))" :key="key" :name="key" :schema="contract.schemas.DeliveryRule.properties[key]" :model-value="r[key]" :readonly="readonly" @update:model-value="change('rules',index,key,$event)"/></details><VBtn color="error" variant="text" :disabled="readonly" @click="update({rules:modelValue.rules.filter((_,i)=>i!==index)})">移除此规则</VBtn></details>
 <section class="sb-setting-card"><h3>档案质量策略</h3><p class="sb-muted">档案与订阅使用各自的分类绑定。可复制当前订阅绑定，再检查是否适合归档规则。</p><VBtn variant="tonal" :disabled="readonly" @click="update({policy_bindings:{...policies.bindings},classification_revision:policies.classification_revision})">使用当前订阅分类绑定</VBtn><div v-for="(name,key) in modelValue.policy_bindings" :key="key" class="sb-binding-row"><div><strong>{{categories?.find(c=>c.id===key)?.name||key}}</strong><span class="sb-muted sb-block">{{name}}</span></div><VBtn variant="text" color="error" :disabled="readonly" @click="unbind(key)">移除绑定</VBtn></div><div class="sb-grid"><label>MoviePilot 分类<select v-model="category" :disabled="readonly"><option value="">选择分类</option><option v-for="c in categories||[]" :key="c.id" :value="c.id" :disabled="!c.enabled">{{c.name}}</option></select></label><label>档案策略<select v-model="binding" :disabled="readonly"><option value="">选择策略</option><option v-for="name in policyNames||[]" :key="name">{{name}}</option></select></label></div><VBtn variant="text" :disabled="readonly||!category||!binding" @click="bind">绑定档案分类</VBtn></section>
</section></template>
