<script setup>
import {ref,computed,onBeforeUnmount} from 'vue';import {useRead} from './read.mjs';import {dateText,stateLabel,reasonText,sourceTitle,sourceNotice} from './media.mjs';import {errorText,createReadGate} from './client.mjs';import Record from './Record.vue';import MediaCover from './MediaCover.vue';
const props=defineProps({client:Object,status:Object});const emit=defineEmits(['action','configure','diagnostic','work']);
const source=ref(''),view=ref('all'),offset=ref(0),sourceOffset=ref(0);
const targetRecord=ref(null),targetPage=ref(null),targetOffset=ref(0),targetError=ref(''),targetBusy=ref(false),targetGate=createReadGate();
onBeforeUnmount(()=>targetGate.close());
async function readTargets(record,offset=0){targetRecord.value=record;targetOffset.value=offset;const read=targetGate.begin();targetBusy.value=true;targetError.value='';targetPage.value=null;try{const result=await props.client.get('/discovery/records/'+record.id+'/targets',{params:{limit:20,offset},signal:read.signal});if(read.current())targetPage.value=result}catch(e){if(read.current())targetError.value=errorText(e)}finally{if(read.current())targetBusy.value=false}}
function closeTargets(){targetGate.begin();targetRecord.value=null}
const testing=ref(''),testResults=ref({});let alive=true;onBeforeUnmount(()=>{alive=false});
async function testSource(s){if(testing.value||busy.value||error.value||!savedSources.value.some(c=>c.id===s.source_id))return;testing.value=s.source_id;
 testResults.value={...testResults.value,[s.source_id]:{message:'正在读取这个已保存来源，不识别或创建订阅…'}};
 try{const r=await props.client.post('/discovery/test',{source_id:s.source_id});if(alive)testResults.value={...testResults.value,[s.source_id]:{message:r.state==='SUCCESS'&&Number.isInteger(r.items)?`抓取 ${r.items} 条；未识别或创建订阅。`:'抓取未成功：'+(reasonText(r.reason)||'请查看读取结果。'),error:r.state!=='SUCCESS',evidence:r}}}
 catch(e){if(alive)testResults.value={...testResults.value,[s.source_id]:{message:errorText(e),error:true}}}finally{if(alive)testing.value=''}
}
const {data,error,busy,refresh}=useRead(async signal=>{const [sources,catalog,records,statistics]=await Promise.all([
 props.client.get('/discovery/sources',{params:{limit:12,offset:sourceOffset.value},signal}),props.client.get('/discovery/catalog',{signal}),
 props.client.get('/discovery/records',{params:{limit:12,offset:offset.value,view:view.value,...(source.value?{source_id:source.value}:{})},signal}),props.client.get('/discovery/statistics',{params:source.value?{source_id:source.value}:{},signal})]);return {sources,catalog,records,statistics}},30000);
const membership=r=>({managed:r.managed_count<r.target_count?'已管理，部分收录记录待处理':'已由 subscriBetter 管理',native:'已交回 MoviePilot 管理',library:'媒体库中已有记录',not_added:'未加入',unrecognized:'等待识别'})[r.membership]||'收录结果待确认';
const routes=computed(()=>data.value?.catalog.result?.routes||[]);
const savedSources=computed(()=>props.status.current.value?.config.discovery?.sources||[]);
const sourceOptions=computed(()=>[...savedSources.value.map(config=>({...data.value?.sources.items.find(s=>s.source_id===config.id),source_id:config.id,config,configured:true})),...(data.value?.sources.items||[]).filter(s=>!savedSources.value.some(c=>c.id===s.source_id))]);
const title=s=>s?sourceTitle(s,routes.value):'来源信息未加载';
const recordSource=id=>sourceOptions.value.find(s=>s.source_id===id);
function filter(id){source.value=id;offset.value=0;refresh()}
function action(name,path,ctx,label,description){emit('action',[name,path],{...ctx,_bound:true,_label:label,_description:description})}
defineExpose({load:refresh});
</script>
<template><section aria-label="豆瓣榜单">
 <header class="sb-heading"><h2>榜单 <span v-if="data" class="sb-count">{{data.records.total}}</span></h2><VBtn variant="text" @click="emit('configure','discovery')">管理来源</VBtn></header>
 <p v-if="error" class="sb-error" role="alert">{{error}} <span v-if="data">以下保留上次结果，可能已过期。</span></p><p v-if="busy&&!data" role="status">正在读取榜单…</p>
 <template v-if="data">
 <div class="sb-search"><label class="sb-grow">榜单来源<select v-model="source" @change="offset=0;refresh()"><option value="">全部来源</option><option v-for="s in sourceOptions" :key="s.source_id" :value="s.source_id">{{title(s)}}</option><option v-if="source&&!sourceOptions.some(s=>s.source_id===source)" :value="source">已选来源（其他页）</option></select></label><label>处理结果<select v-model="view" @change="offset=0;refresh()"><option value="all">全部</option><option value="managed">已管理</option><option value="native">已交回 MP</option><option value="library">媒体库已有</option><option value="not_added">未加入</option><option value="unrecognized">等待识别</option></select></label><VBtn variant="text" :disabled="busy" @click="refresh">刷新</VBtn></div>
 <details class="sb-source-status"><summary>来源状态 · {{sourceOptions.length}} 个本页来源<span v-if="data.sources.items.some(s=>sourceNotice(s))"> · 本页有来源需要检查</span></summary>
 <div v-for="s in sourceOptions" :key="s.source_id" class="sb-source-row"><div><strong>{{title(s)}}</strong><small v-if="!s.configured"> · 历史来源（已移除）</small><span class="sb-muted sb-block">{{sourceNotice(s)||stateLabel(s.last_state)}} · 上次成功 {{dateText(s.last_success)}}</span></div><div class="sb-actions"><VBtn variant="text" @click="filter(s.source_id)">查看作品</VBtn><VBtn variant="text" :disabled="!s.configured||busy||!!error||!!testing" @click="testSource(s)">试读榜单</VBtn><VBtn variant="text" :disabled="!s.configured||busy||!!error" @click="action('运行这个来源','/discovery/run',{source_ids:[s.source_id]},title(s),'按已保存规则识别作品，并可能纳管或创建订阅。')">运行一次</VBtn></div><div v-if="testResults[s.source_id]" class="sb-source-result" role="status"><p :class="{'sb-error':testResults[s.source_id].error}">{{testResults[s.source_id].message}}</p><details v-if="testResults[s.source_id].evidence" class="sb-technical"><summary>读取结果详情</summary><Record :value="testResults[s.source_id].evidence"/></details></div><details class="sb-technical"><summary>读取依据</summary><Record :value="{状态:s.last_state,原因代码:s.last_reason,地址:s.config.url||s.config.route_key,下次可处理时间:s.next_due}"/></details></div>
 <div v-if="data.sources.total>12" class="sb-pagination"><VBtn :disabled="busy||!sourceOffset" @click="sourceOffset-=12;refresh()">上一页来源</VBtn><VBtn :disabled="busy||data.sources.next_offset===null" @click="sourceOffset=data.sources.next_offset;refresh()">下一页来源</VBtn></div>
 </details>
 <div v-if="!sourceOptions.length" class="sb-empty"><h3>添加一个豆瓣榜单</h3><p>接入自部署 RSSHub 后，发现的作品会显示在这里。</p><VBtn color="primary" @click="emit('configure','discovery')">配置来源</VBtn></div>
 <p v-else-if="!data.records.items.length" class="sb-empty">还没有符合条件的作品。运行来源后会形成发现记录。</p>
 <div class="sb-board-grid"><article v-for="r in data.records.items" :key="r.id" class="sb-board-card"><MediaCover :src="r.raw.poster"/><div class="sb-board-content"><small>{{title(recordSource(r.source_id))}}</small><h3>{{r.raw.title||r.raw.name||'未提供标题'}}</h3><span class="sb-membership" :data-state="r.membership">{{membership(r)}}</span><p v-if="r.reason">{{reasonText(r.reason)}}</p><div class="sb-actions"><VBtn v-for="target in r.targets?.filter(t=>t.task_id)||[]" :key="target.task_id" variant="tonal" @click="emit('work',{id:target.task_id,title:r.raw.title})">{{target.season!=null?'查看第 '+target.season+' 季':'查看作品'}}</VBtn><VBtn variant="text" :disabled="busy||!!error||!recordSource(r.source_id)?.configured" @click="action('重新检查收录条件','/discovery/reprocess',{record_ids:[r.id]},r.raw.title||'此作品','按当前规则重新识别并检查收录条件，可能创建或接管订阅。')">重新检查收录条件</VBtn></div><VBtn v-if="r.target_count>8" variant="text" @click="readTargets(r)">查看全部 {{r.target_count}} 个季度结果</VBtn><small>最近出现 {{dateText(r.last_seen)}}</small><details class="sb-technical"><summary>查看识别与收录依据</summary><p v-for="(target,index) in r.targets||[]" :key="index">{{target.season!=null?'第 '+target.season+' 季 · ':''}}{{stateLabel(target.task_state||target.state)}} {{reasonText(target.reason)}}</p><Record :value="r.evidence"/></details></div></article></div>
 <div v-if="data.records.total" class="sb-pagination"><VBtn :disabled="busy||!offset" @click="offset=Math.max(0,offset-12);refresh()">上一页作品</VBtn><span>共 {{data.records.total}} 条 · 第 {{Math.floor(offset/12)+1}} 页</span><VBtn :disabled="busy||data.records.next_offset===null" @click="offset=data.records.next_offset;refresh()">下一页作品</VBtn></div>
 <details class="sb-technical"><summary>统计与缓存详情</summary><Record :value="data.statistics.result"/></details>
 </template>
<v-dialog :model-value="!!targetRecord" max-width="700" @update:model-value="v=>{if(!v)closeTargets()}"><section class="sb-root sb-dialog"><h2>{{targetRecord?.raw.title}} · 全部季度</h2><p v-if="targetBusy" role="status">正在读取…</p><p v-if="targetError" role="alert">{{targetError}} <VBtn variant="text" @click="readTargets(targetRecord,targetOffset)">重新读取</VBtn></p><div v-for="row in targetPage?.items||[]" :key="row.id" class="sb-binding-row"><span>{{row.data.season!=null?'第 '+row.data.season+' 季':'电影'}} · {{stateLabel(row.state||row.data.state)}}<small class="sb-block">{{reasonText(row.data.reason)}}</small></span><VBtn v-if="row.data.task_id" variant="text" @click="emit('work',{id:row.data.task_id,title:targetRecord.raw.title});closeTargets()">查看作品</VBtn></div><div class="sb-pagination"><VBtn :disabled="targetBusy||!targetOffset" @click="readTargets(targetRecord,targetOffset-20)">上一页季度</VBtn><VBtn :disabled="targetBusy||!targetPage||targetPage.next_offset===null" @click="readTargets(targetRecord,targetPage.next_offset)">下一页季度</VBtn><VBtn variant="text" @click="closeTargets">关闭</VBtn></div></section></v-dialog></section></template>
