<script setup>
import {ref,computed} from 'vue';import {useRead} from './read.mjs';import {dateText,stateLabel,reasonText} from './media.mjs';import Record from './Record.vue';
const props=defineProps({client:Object,status:Object});const emit=defineEmits(['action','configure','diagnostic']);
const source=ref(''),view=ref('all'),offset=ref(0),sourceOffset=ref(0);
const {data,error,busy,refresh}=useRead(async signal=>{const [sources,catalog,records,statistics]=await Promise.all([
 props.client.get('/discovery/sources',{params:{limit:12,offset:sourceOffset.value},signal}),props.client.get('/discovery/catalog',{signal}),
 props.client.get('/discovery/records',{params:{limit:12,offset:offset.value,view:view.value,...(source.value?{source_id:source.value}:{})},signal}),props.client.get('/discovery/statistics',{params:source.value?{source_id:source.value}:{},signal})]);return {sources,catalog,records,statistics}},30000);
const routes=computed(()=>data.value?.catalog.result?.routes||[]);
function title(s){const route=routes.value.find(r=>r.key===s.config.route_key);if(route)return route.label;const config=props.status.current.value?.config.discovery?.sources?.find(c=>c.id===s.source_id);try{return '自定义榜单 · '+new URL(config?.url).pathname}catch{return s.config.legacy_rank_key||'历史来源'}}
function filter(id){source.value=id;offset.value=0;refresh()}
function action(name,path,ctx,label,description){emit('action',[name,path],{...ctx,_bound:true,_label:label,_description:description})}
defineExpose({load:refresh});
</script>
<template><section aria-label="豆瓣榜单">
 <header class="sb-heading"><div><p class="sb-eyebrow">发现作品</p><h2>豆瓣榜单</h2><p class="sb-muted">榜单抓取、身份识别与订阅结果分开查看。</p></div><VBtn color="primary" @click="emit('configure','discovery')">管理榜单来源</VBtn></header>
 <p v-if="error" class="sb-error" role="alert">{{error}} <span v-if="data">以下保留上次结果，可能已过期。</span></p><p v-if="busy&&!data" role="status">正在读取榜单…</p>
 <template v-if="data"><div v-if="!data.sources.total" class="sb-empty"><h3>接入你的 RSSHub</h3><p>配置自部署地址并选择豆瓣榜单；已有完整地址也可以直接粘贴。</p><VBtn variant="tonal" @click="emit('configure','discovery')">配置第一个来源</VBtn></div>
 <div class="sb-source-grid"><article v-for="s in data.sources.items" :key="s.source_id" class="sb-source-card" :class="{'sb-selected':source===s.source_id}"><div class="sb-heading"><h3>{{title(s)}}</h3><span class="sb-state" :data-state="s.last_state">{{stateLabel(s.last_state)}}</span></div><p class="sb-muted">{{s.config.enabled===false?'来源已停用':s.config.source_type_hint==='Movie'?'电影榜单':'影视榜单'}} · 上次成功 {{dateText(s.last_success)}}</p><p v-if="s.last_reason" class="sb-warning">{{reasonText(s.last_reason)}}</p><p class="sb-muted">{{s.next_due?'下次可处理时间 '+dateText(s.next_due*1000):'尚无下次处理时间'}}</p><div class="sb-actions"><VBtn variant="tonal" @click="filter(s.source_id)">查看作品</VBtn><VBtn variant="text" :disabled="busy||!!error" @click="action('测试榜单抓取','/discovery/test',{source_id:s.source_id},title(s),'仅抓取已保存的榜单，不识别媒体、不创建订阅。')">测试抓取</VBtn><VBtn variant="text" :disabled="busy||!!error" @click="action('运行这个来源','/discovery/run',{source_ids:[s.source_id]},title(s),'按已保存的来源规则识别作品，并可能纳管或创建订阅。')">运行一次</VBtn></div></article></div>
 <div v-if="data.sources.total>12" class="sb-pagination"><VBtn :disabled="busy||!sourceOffset" @click="sourceOffset-=12;refresh()">上一页来源</VBtn><span>共 {{data.sources.total}} 个来源</span><VBtn :disabled="busy||data.sources.next_offset===null" @click="sourceOffset=data.sources.next_offset;refresh()">下一页来源</VBtn></div>
 <div class="sb-section-heading"><div><h3>榜单中的作品</h3><span class="sb-muted">{{source?'当前来源':'全部来源'}} · 共 {{data.records.total}} 条记录</span></div><div class="sb-actions"><label>显示范围<select v-model="view" @change="offset=0;refresh()"><option value="all">全部</option><option value="recognized">已识别</option><option value="unrecognized">待识别</option></select></label><VBtn variant="text" :disabled="busy" @click="filter('')">全部来源</VBtn><VBtn variant="text" :disabled="busy" @click="refresh">刷新</VBtn></div></div>
 <p v-if="!data.records.items.length" class="sb-empty">这里还没有符合条件的作品。抓取测试只验证来源，运行来源后才会形成发现记录。</p>
 <div class="sb-discovery-grid"><article v-for="r in data.records.items" :key="r.id" class="sb-discovery-card"><p class="sb-eyebrow">{{data.sources.items.find(s=>s.source_id===r.source_id)?title(data.sources.items.find(s=>s.source_id===r.source_id)):'榜单记录'}}</p><h3>{{r.raw.title||r.raw.name||'未提供标题'}}</h3><span class="sb-state" :data-state="r.state">{{stateLabel(r.state)}}</span><p>{{reasonText(r.reason)}}</p><p class="sb-muted">最近出现 {{dateText(r.last_seen)}}</p><div class="sb-actions"><VBtn variant="text" :disabled="busy||!!error" @click="action('重新判定作品','/discovery/reprocess',{record_ids:[r.id]},r.raw.title||'此作品','清除本条记录的重试等待，按当前规则重新判定；不会保证订阅成功。')">重新判定</VBtn><VBtn variant="text" @click="emit('diagnostic','discovery',['关联的订阅','/discovery/records/{record_id}/targets',{record_id:r.id}])">关联订阅</VBtn></div><details class="sb-technical"><summary>识别与过滤依据</summary><Record :value="{原因代码:r.reason,识别依据:r.evidence}"/></details></article></div>
 <div v-if="data.records.total" class="sb-pagination"><VBtn :disabled="busy||!offset" @click="offset=Math.max(0,offset-12);refresh()">上一页作品</VBtn><span>第 {{Math.floor(offset/12)+1}} 页</span><VBtn :disabled="busy||data.records.next_offset===null" @click="offset=data.records.next_offset;refresh()">下一页作品</VBtn></div>
 <details class="sb-technical"><summary>查看分阶段统计与缓存依据</summary><Record :value="data.statistics.result"/></details>
 </template>
</section></template>
