export const labels={
 first_eligible_at:'首次合格观察',last_better_at:'最后实质改善',deadline:'观察截止',anchor_at:'期限起算锚点',quality:'当前质量',gaps:'缺集',missing:'缺失目标',inflight:'在途目标',bytes_downloaded:'已下载字节',remaining_seconds:'测量剩余秒数',sha1:'SHA-1',sha256:'SHA-256',hash:'内容 Hash',size:'内容字节',location:'当前位置证据',full_scan_watermark:'最近完整扫描水位',failed_paths:'失败目录',supersessions:'已用取代次数',publish_action_id:'原始发布操作 ID',last_ingest:'最后确认入库',observations:'逐目标观察时钟',last_better:'最后实质改善',original:'原始依据',corrected:'纠正结果',diff:'逐字段差异',compatibility:'宿主兼容性',

 enabled:'启用',dry_run:'只读 / dry-run',auto_types:'新订阅自动纳管类型',enhance_host_meta:'增强宿主公共解析',meta_protected_names:'明确保护的完整片名',ai_assist:'AI 名称辅助与聊天',discovery:'榜单与 RSS 发现',delivery:'交付、目录与两段映射',policy:'独立策略',lifecycle:'生命周期',candidates:'站点与候选预算',schedule:'观察、冷却与抢占',recovery:'对账与消费者恢复',safety:'安全与容量',permissions:'独立清理权限',passive_libraries:'授权被动媒体库',destination_templates:'目的目录模板',history_view:'历史显示方式',configuration_receipt:'配置回执',configuration_revision:'配置版本',
 cleanup_success:'成功交付后清理监控副本',cleanup_abandoned:'放弃 / 取代后清理监控副本',cleanup_staging:'清理未发布暂存',remove_downloader_task_enabled:'移除下载器任务',delete_downloader_data_enabled:'删除下载器源数据',
 movie_days:'电影期限（天，0 为不限制）',tv_days:'剧集期限（天，0 为不限制）',expiry_mode:'期限起算依据',completed_mode:'完结后逐集 / 整包',oneshot_seconds:'一次性机会时长（秒）',site_ids:'授权站点 ID',keywords:'搜索词数',keywords_limit:'搜索词上限',pages:'分页上限',concurrency:'并发数',results:'结果上限',requests:'请求上限',interval:'请求间隔（秒）',refresh_seconds:'刷新间隔（秒）',supplement_limit:'补充候选上限',query_scope:'搜索词范围',exclusion_scope:'排除范围',exclusion_seconds:'排除有效期（秒）',
 observation_enabled:'启用候选观察',base_seconds:'基础观察窗口（秒）',quiet_seconds:'最后改善后安静窗口（秒）',max_seconds:'最大观察窗口（秒）',goal_early_enabled:'达标提前执行',cooldown_enabled:'启用入库升级冷却',cooldown_seconds:'升级冷却（秒）',supersession_limit:'取代次数预算',supersession_seconds:'取代预算窗口（秒）',failure_limit:'失败预算',waiting_transfer_preemption:'等待秒传时允许抢占',normal_download_preemption:'下载中允许受控抢占',max_downloaded_bytes:'抢占已下载字节上限',min_remaining_seconds:'抢占最少剩余时间（秒）',
 startup_reconcile:'启动时对账',reconcile_seconds:'完整对账间隔（秒）',entries:'单次条目预算',seconds:'单次恢复预算（秒）',active_poll_seconds:'活跃目标轮询（秒）',watcher:'文件监听（当前合同仅关闭，周期扫描恢复）',consumer_recovery_ref:'已验证消费者恢复引用',test_roots:'授权试验根目录',worker_limit:'工作并发上限',network_timeout:'网络超时（秒）',minimum_free_bytes:'最少剩余磁盘字节',
 bindings:'分类 ID → 偏好',classification_revision:'宿主分类发布版本',overrides:'自定义条件 AST',admission:'准入条件 AST',locks:'显式锁',id:'标识',category_id:'当前分类 ID',downloader:'已配置下载器名称',save_path:'下载保存目录',organized_rule:'整理规则',sites:'站点 ID',custom_words:'自定义识别词',cloud_scopes:'云盘作用域',libraries:'Emby 服务 → 库 ID',policy_bindings:'交付分类偏好',mappings:'两段路径映射',rules:'监控与交付规则',
 revision:'版本',emby_service:'已配置 Emby 服务',library_id:'Emby 库 ID',cloud_scope_id:'云盘作用域 ID',local_strm_prefix:'MP 可读 STRM 前缀',emby_prefix:'Emby 路径前缀',playback_prefix:'STRM 目标前缀',cd2_prefix:'CD2 内部路径前缀',max_strm_bytes:'STRM 读取字节上限',allow_direct:'允许已核实的直连路径',media_source:'身份来源',episode_group:'剧集组',cd2_plugin:'CloudDrive 实例引用',p115_plugin:'115 实例引用',root:'云盘根目录',allowed_prefixes:'授权云盘前缀',p115_parents:'云盘前缀 → 115 父目录 ID',
 local_root:'监控根目录',staging_root:'隔离暂存根目录',incoming_root:'交付根目录',consumer_roots:'消费者根目录',excluded_local_roots:'排除本地根目录',read_roots:'授权读取根目录',scan_interval:'扫描间隔（秒）',stable_seconds:'稳定窗口（秒）',rapid_interval:'秒传尝试间隔（秒）',rapid_misses:'确认 MISS 次数 N',fallback:'启用 CD2 普通上传回退',unlimited:'回退不限制大小',fallback_gb:'回退大小上限（GB）',notify_success:'成功通知',notify_error:'错误通知',
 rsshub_base_url:'已配置本地 RSSHub 地址',allowed_private_ranges:'明确授权私网范围',cron:'发现计划（Cron）',request_budget:'发现请求预算',media_type_allowlist:'允许媒体类型',minimum_release_year:'最低发行年份',minimum_rating:'最低评分',rating_source:'评分来源',season_scope:'季范围',existing_media_action:'已有媒体处理方式',sources:'来源',kind:'种类',route_key:'内置 RSSHub 路由',url:'自定义 RSS 地址',source_type_hint:'原始类型提示',proxy:'使用宿主代理',legacy_rank_key:'旧榜单标识',legacy_original_text:'旧来源原文',import_diagnostics:'迁移诊断',
 name_assistance_enabled:'名称辅助',endpoint_ref:'私密端点引用',credential_refs:'有序密钥引用',model:'模型',profile:'请求 profile',compatible:'兼容传输',timeout:'请求超时（秒）',max_attempts:'尝试上限',max_concurrency:'AI 并发上限',queue_size:'队列上限',positive_ttl:'正缓存 TTL（秒）',negative_ttl:'负缓存 TTL（秒）',cache_size:'缓存容量',prompt:'当前提示词',prompt_backup:'提示词备份',prompt_previous_backup:'上一份提示词备份',notifications:'诊断通知',name_recognize_bridge:'可选 NameRecognize 桥接',chat_enabled:'独立普通聊天',chat_routes:'明确授权聊天路由',chat_input_limit:'聊天输入上限',chat_history_limit:'会话消息上限',chat_session_limit:'会话数上限',channel:'渠道',source:'来源',userid:'用户 ID',chat_id:'会话 ID',
 state:'状态',reason:'原因',generation:'代次',target_key:'目标键',target_keys:'精确目标范围',task_id:'任务 ID',opportunity_id:'机会 ID',candidate_key:'候选键',operation_id:'操作 ID',plan_id:'计划 ID',bundle_id:'交付组 ID',version_id:'版本 ID',version_ids:'档案版本范围',record_ids:'历史记录范围',source_ids:'发现来源范围',source_id:'来源 ID',simulation:'仅模拟',current:'已有版本',candidate:'候选样例',description:'原始描述',labels:'原始标签',title:'原始标题',sample_key:'重放样例键',sample_keys:'重放样例范围',
 objects:'不可变操作对象',revisions:'事实版本',blockers:'阻塞原因',expires_at:'到期时间',preview_id:'预览回执',preview_digest:'预览摘要',receipt_id:'回执 ID',digest:'摘要',total:'总数',next_offset:'下一页偏移',snapshot:'读取快照',high_watermark:'观察水位',runtime_generation:'运行代次',config_revision:'配置版本',
 task:'任务',units:'逐目标质量与交付权',current_facts:'当前质量事实',opportunities:'机会与模式',plans:'计划',effective:'实际范围与生效设置',facts:'当前事实',evidence:'决策证据',assets:'文件与附件',locations:'物理位置',versions:'历史与当前版本',files:'逐文件状态',actions:'外部操作',receipts:'成功与未知回执',authority:'交付权与取代',shared_references:'共享引用',cleanup:'清理依据',scans:'扫描水位',services:'服务与依赖',meta:'解析兼容性',runtime:'运行时预算与用量',fields:'逐字段迁移',steps:'切换步骤',next_changes:'待执行精确配置变更',diagnostics:'诊断',private_refs:'安全凭据引用',memory_cache_restored:'旧内存缓存恢复',cursor:'历史游标',history_count:'历史条数',time_basis:'原始时间依据',raw:'历史原文',
 owner_plan_id:'当前交付权计划',publish_phase:'发布屏障',last_ingest_confirmed_at:'最后确认入库',cooldown_until:'冷却截止',first_seen:'首次观察',updated_at:'最后更新',due:'下次尝试',failures:'失败预算已用',last_success:'最后成功',last_failure:'最后失败',next_due:'下次尝试',file_count:'文件数',consumer_pending:'等待 Emby',source_instance:'旧实例标识',source_version:'旧实例版本',source_timezone:'历史时区',phase:'重试阶段',expected_state:'预期当前状态',scope:'独立操作范围',
 offset:'分页偏移',limit:'每页数量',sort:'排序',active:'有效排除',view:'历史筛选',status:'结果状态',media_type:'媒体类型',media_id:'媒体 ID',name:'名称',year:'年份',season:'季',native_id:'宿主订阅 ID',adopt:'明确接管已有订阅',destination_template:'当前目录模板',mode:'持续 / 一次性',intent_key:'幂等意图键',confirm_adoption:'确认领养',task_generation:'任务代次',decision_digest:'原始决策摘要',scan_id:'扫描 ID',item_id:'实际 Emby 项目 ID',mapping_id:'当前映射 ID',component:'对账组件',object_id:'精确对象 ID',section:'明细类型',infohash:'原始 InfoHash',
 content_base64:'私密导入内容',value:'一次性私密输入',features:'期望新功能与路由',selected:'明确选择停止的旧功能',module:'功能模块',instance_id:'实例 ID',config_digest:'配置摘要',route_scope:'精确响应路由',whole_instance:'停止整个已验证榜单实例',all_capabilities:'已验证全部功能',configuration_receipt:'配置预览回执',endpoint_ref:'端点私密引用',credential_ref:'密钥私密引用',private_ranges:'授权目标私网范围',action:'回执步骤',
};
export const label=key=>labels[key]||key.replaceAll('_',' ');
