<script setup>
import {ref,watch,onBeforeUnmount} from 'vue';import {errorText} from './client.mjs';import Record from './Record.vue';
const props=defineProps({mapping:Object,client:Object,status:Object,saved:Boolean});const scans=ref([]),scan=ref(''),items=ref([]),item=ref(''),busy=ref(false),error=ref(''),result=ref(null),scanOffset=ref(0),nextScan=ref(null),itemOffset=ref(0),nextItem=ref(null);let alive=true,sequence=0;
watch(()=>JSON.stringify(props.mapping),()=>{sequence++;scans.value=[];scan.value='';items.value=[];item.value='';result.value=null;busy.value=false});watch(()=>props.saved,()=>{sequence++;result.value=null;busy.value=false});
async function loadScans(offset=0){const n=++sequence;busy.value=true;error.value='';try{const page=await props.client.get('/health/records/archive_scans',{params:{limit:100,offset}});if(alive&&n===sequence){scans.value=page.items.filter(r=>r.data.service===props.mapping.emby_service&&String(r.data.library)===props.mapping.library_id);scanOffset.value=offset;nextScan.value=page.next_offset;scan.value='';items.value=[];item.value='';result.value=null}}catch(e){if(alive&&n===sequence)error.value=errorText(e)}finally{if(alive&&n===sequence)busy.value=false}}
async function loadItems(offset=0){const n=++sequence;busy.value=true;error.value='';item.value='';result.value=null;try{const page=await props.client.get('/archive/scans/'+encodeURIComponent(scan.value)+'/items',{params:{limit:25,offset}});if(alive&&n===sequence){items.value=page.items;itemOffset.value=offset;nextItem.value=page.next_offset}}catch(e){if(alive&&n===sequence)error.value=errorText(e)}finally{if(alive&&n===sequence)busy.value=false}}
async function check(){if(busy.value||!props.saved||!item.value||props.status.error.value)return;const n=++sequence;busy.value=true;error.value='';result.value=null;try{const r=await props.client.post('/archive/mapping-test',{config_revision:props.status.current.value.revision,runtime_generation:props.status.health.value.generation,scan_id:scan.value,item_id:item.value,mapping_id:props.mapping.id});if(alive&&n===sequence)result.value=r}catch(e){if(alive&&n===sequence)error.value=errorText(e)}finally{if(alive&&n===sequence)busy.value=false}}
onBeforeUnmount(()=>{alive=false;sequence++});
</script>
<template><details class="sb-technical"><summary>用真实档案检查映射</summary><p>只读取已保存映射和扫描样本，不执行整理或上传。确认的是当前 STRM 路径转换，不等于云端文件或播放已验证。</p><p v-if="!saved">此处有未保存修改。先保存设置并重新打开，才能检查生效映射。</p><VBtn variant="tonal" :disabled="busy||!saved" @click="loadScans()">读取此媒体库的扫描样本</VBtn><template v-if="scans.length||nextScan!==null||scanOffset"><label>选择扫描记录<select v-model="scan" :disabled="busy||!saved" @change="loadItems()"><option value="">请选择</option><option v-for="s in scans" :key="s.id" :value="s.id">{{s.data.data?.started_at||s.data.started_at||s.data.created_at||'扫描记录'}} · {{s.state}}</option></select></label><div class="sb-pagination"><VBtn variant="text" :disabled="busy||!scanOffset" @click="loadScans(Math.max(0,scanOffset-100))">较早一页扫描</VBtn><VBtn variant="text" :disabled="busy||nextScan===null" @click="loadScans(nextScan)">下一页扫描</VBtn></div><label v-if="scan">真实作品<select v-model="item" :disabled="busy||!saved" @change="result=null"><option value="">请选择档案条目</option><option v-for="(i,index) in items" :key="i.id" :value="i.id">{{i.data.name||'名称未记录'}} · {{i.data.episode!=null?'第 '+i.data.episode+' 集':'第 '+(itemOffset+index+1)+' 条记录'}}</option></select></label><div v-if="scan" class="sb-pagination"><VBtn variant="text" :disabled="busy||!itemOffset" @click="loadItems(Math.max(0,itemOffset-25))">上页样本</VBtn><VBtn variant="text" :disabled="busy||nextItem===null" @click="loadItems(nextItem)">下页样本</VBtn></div><VBtn color="primary" :disabled="busy||!saved||!item||!!status.error.value" @click="check">检查这条映射</VBtn></template><p v-else-if="!busy&&nextScan===null&&scanOffset===0" class="sb-muted">尚未选择扫描样本；没有记录时需要先完成该媒体库的档案扫描。</p><p v-if="error" class="sb-error" role="alert">{{error}}</p><section v-if="result" role="status"><p>{{result.state==='MAPPING_VERIFIED'?'已读取实际 STRM，路径转换通过。':'未取得映射通过结果。'}}</p><div v-for="(step,index) in result.result?.locations||[]" :key="index" class="sb-path-current"><p>Emby：{{step.emby_path}}</p><p>MP 可读 STRM：{{step.local_strm_path||'直接文件，不读取 STRM'}}</p><p>CD2：{{step.cd2_path}}</p></div><details><summary>验证依据</summary><Record :value="result"/></details></section></details></template>
