<script setup>
import {ref,computed,onBeforeUnmount,onMounted} from 'vue';
import Field from './Field.vue';import Record from './Record.vue';import Resource from './Resource.vue';
import {bodySchema,initial,clone,contract,validate} from './schema.mjs';
import {receiptBody,errorText,id,saveFollowup,readFollowup} from './client.mjs';
import {saveLegacy} from './legacy.mjs';
const props=defineProps({client:Object,status:Object,nativeApi:Object});const emit=defineEmits(['changed','switch']);let mounted=true;
const rawJSONSupported=typeof JSON.rawJSON==='function'&&typeof JSON.isRawJSON==='function';
const nativeResult=ref(null),tab=ref('import'),endpoint=ref(''),token=ref('');
const receiptTitle=r=>({PREVIEW:'预览待确认',IMPORTING:'正在导入历史',IMPORTED:'导入完成',READ_DONE:'来源读取完成',WAIT_HOST_SAVE:'等待保存旧插件开关',WAIT_OWNER:'仍有功能冲突需要核对',READY_CONFIG:'可以保存新配置',ACTIVE:'切换已确认',ROLLBACK_FENCED:'已隔离新功能，等待回退',ROLLBACK_RESTORE:'正在恢复旧功能',ROLLED_BACK:'已回退'}[r.state]||'需要检查迁移记录');
const oldChoices=computed(()=>(owners.value?.plugins||[]).filter(p=>p.instance_id!==props.client.pluginId&&((p.source==='ChatGPTPlusUltra'&&p.version==='1.4.2')||(p.source==='DoubanRankPlusOptimized'&&p.version==='1.0.7'))));
function oldChoice(p,checked){selected.value=selected.value.filter(x=>x.instance_id!==p.instance_id);if(checked)selected.value.push({instance_id:p.instance_id,config_digest:p.config_digest,module:p.source==='ChatGPTPlusUltra'?'name_bridge':'discovery',whole_instance:p.source==='DoubanRankPlusOptimized',all_capabilities:p.source==='DoubanRankPlusOptimized'?['discovery']:[]})}
function continueConfig(){saveFollowup(props.client.pluginId,{cutover:receipt.value.receipt_id});emit('switch')}
onMounted(()=>{const saved=readFollowup(props.client.pluginId)?.cutover;if(saved){receiptId.value=saved;loadReceipt()}});
const source=ref({source_instance:'ChatGPTPlusUltra',source_version:'',source_timezone:null}),file=ref(null),fileControl=ref(null),receipt=ref(null),receiptId=ref(''),busy=ref(false),error=ref(''),confirm=ref(false),history=ref(false);
const selectedHistory=ref(null),taskId=ref(null),versionId=ref(''),linkConfirm=ref(false),linkedRow=ref(null),historyKey=ref(0);
const remote=ref(initial(bodySchema('/migration/source/preview'))),owners=ref(null),selected=ref([]),featureChoice=ref([]),configPreview=ref(null);
const featureOptions=computed(()=>{const c=props.status.current.value?.config;if(!c)return [];const options=[{key:'name_assistance',title:'资源名称辅助',module:'name_assistance',route_scope:'internal'},{key:'name_bridge',title:'辅助 MoviePilot 名称识别',module:'name_bridge',route_scope:{event:'NameRecognize'}}];for(const s of c.discovery.sources)options.push({key:'discovery:'+s.id,title:'豆瓣榜单 · '+(s.name||s.route_key||'自定义来源'),module:'discovery',route_scope:s.id});return options});
async function run(fn){if(busy.value)return;busy.value=true;error.value='';try{await fn()}catch(e){if(mounted)error.value=errorText(e)}finally{if(mounted)busy.value=false}}
async function loadReceipt(){return run(async()=>{const r=await props.client.get('/migration/receipts/'+encodeURIComponent(receiptId.value));if(mounted){receipt.value=r;confirm.value=false;history.value=false;selectedHistory.value=null;linkedRow.value=null}})}
async function importPreview(){return run(async()=>{try{if(!file.value||file.value.size>2097152)throw Error('BOUNDED_FILE_REQUIRED');const bytes=new Uint8Array(await file.value.arrayBuffer());let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);if(!mounted)return;const r=await props.client.post('/migration/preview',{...source.value,content_base64:btoa(binary)});if(mounted){receipt.value=r;receiptId.value=r.receipt_id;confirm.value=false;history.value=false}}finally{file.value=null;if(fileControl.value)fileControl.value.value=''}})}
async function remotePreview(){return run(async()=>{for(const [kind,value,field] of [['legacy_source',endpoint.value.trim(),'endpoint_ref'],['legacy_token',token.value.trim(),'credential_ref']]){if(!value)continue;try{const r=await props.client.post('/credentials',{revision:props.status.current.value.revision,digest:props.status.current.value.digest,operation_id:id(),kind,value});if(!/^secret:[a-f0-9]{32}$/.test(r.reference))throw Error('INVALID_CREDENTIAL_REFERENCE');remote.value[field]=r.reference;}finally{if(kind==='legacy_source')endpoint.value='';else token.value=''}}if(!mounted)return;const r=await props.client.post('/migration/source/preview',clone(remote.value));if(mounted){receipt.value=r;receiptId.value=r.receipt_id;confirm.value=false}})}
async function advance(action){if(!confirm.value)return;const saved=clone(receipt.value);const operation=id();return run(async()=>{let path,body=receiptBody(saved,operation);if(saved.kind==='IMPORT'){path='/migration/import';body={...body,cursor:saved.cursor,limit:100}}else if(saved.kind==='SOURCE')path='/migration/source/read';else{path='/migration/cutover';body.action=action}const r=await props.client.post(path,body);if(mounted){receipt.value=r;receiptId.value=r.receipt_id;confirm.value=false;emit('changed')}})}
async function readOwners(){return run(async()=>{const o=await props.client.get('/migration/owners');if(mounted){owners.value=o;selected.value=[]}})}
async function linkHistory(){if(!linkConfirm.value||!selectedHistory.value)return;return run(async()=>{const r=await props.client.post('/migration/history/link',{receipt_id:receipt.value.receipt_id,ordinal:selectedHistory.value.ordinal,digest:selectedHistory.value.digest,task_id:Number(taskId.value),version_id:versionId.value.trim()});if(mounted){linkedRow.value=r;selectedHistory.value=null;linkConfirm.value=false;historyKey.value++}})}
async function planCutover(){return run(async()=>{if(!featureChoice.value.length)throw Error('FEATURE_REQUIRED');const chosen=featureOptions.value.filter(x=>featureChoice.value.includes(x.key));const desired=clone(props.status.current.value.config);desired.enabled=true;desired.dry_run=false;desired.ai_assist.name_assistance_enabled=false;desired.ai_assist.name_recognize_bridge=false;desired.discovery.enabled=false;for(const s of desired.discovery.sources)s.enabled=false;for(const f of chosen){if(f.module==='discovery'){desired.discovery.enabled=true;desired.discovery.sources.find(s=>s.id===f.route_scope).enabled=true}else{desired.ai_assist.enabled=true;desired.ai_assist[{name_assistance:'name_assistance_enabled',name_bridge:'name_recognize_bridge'}[f.module]]=true}}const p=await props.client.post('/configuration/preview',{revision:props.status.current.value.revision,digest:props.status.current.value.digest,patch:desired});if(!p.valid)throw Error('INVALID_CONFIGURATION');if(!mounted)return;configPreview.value=p;const features=chosen.map(f=>({module:f.module,instance_id:props.client.pluginId,config_digest:p.feature_digests[f.module==='discovery'?'discovery':'ai_assist'],route_scope:f.route_scope}));const r=await props.client.post('/migration/cutover/preview',{configuration_receipt:p.receipt_id,features,selected:clone(selected.value)});if(mounted){receipt.value=r;receiptId.value=r.receipt_id;confirm.value=false}})}
async function nativeChange(change){if(!confirm.value)return;return run(async()=>{const fresh=await props.client.get('/migration/receipts/'+encodeURIComponent(receipt.value.receipt_id));const exact=fresh.next_changes.find(c=>c.instance_id===change.instance_id);if(!exact||JSON.stringify(exact)!==JSON.stringify(change))throw Error('STALE_CUTOVER');const step=fresh.steps.find(s=>s.instance_id===change.instance_id);const result=await saveLegacy(props.nativeApi,exact,step,()=>mounted);if(mounted){nativeResult.value=result;confirm.value=false;error.value='';receipt.value=fresh;emit('changed');}})}
onBeforeUnmount(()=>{mounted=false;endpoint.value='';token.value='';file.value=null;source.value={};remote.value={};selected.value=[];configPreview.value=null;selectedHistory.value=null;linkedRow.value=null});
</script>
<template><section class="sb-migration" aria-label="迁移旧插件"><header class="sb-heading"><h2>迁移旧插件</h2></header><p>先备份旧配置。导入会保留历史记录，下载和识别功能需要另外切换。</p>
 <nav class="sb-nav" aria-label="迁移方式"><button v-for="[key,title] in [['import','导入备份'],['source','读取旧榜单'],['cutover','切换功能']]" :key="key" :aria-current="tab===key" @click="tab=key">{{title}}</button></nav>
 <section v-if="tab==='import'" class="sb-form-section"><div class="sb-grid"><label>来源插件<input v-model="source.source_instance" maxlength="256" placeholder="例如 ChatGPTPlusUltra"/></label><label>原插件版本<input v-model="source.source_version" maxlength="128" placeholder="例如 1.4.2"/></label><label>原记录的时区<input :value="source.source_timezone||''" @input="source.source_timezone=$event.target.value||null" placeholder="未记录时可留空" maxlength="128"/></label></div><label>导出的 JSON 文件<input ref="fileControl" type="file" accept="application/json,.json" @change="file=$event.target.files[0]"/><small>最多 2 MiB；文件仅用于这次私密导入。</small></label><VBtn color="primary" :disabled="busy||!file||!source.source_version" @click="importPreview">预览导入内容</VBtn></section>
 <section v-if="tab==='source'" class="sb-form-section"><h3>DoubanRankPlusOptimized</h3><p>先预览读取范围，确认后仅请求配置与历史两个接口。</p><label>旧服务地址<input v-model="endpoint" type="password" autocomplete="off" maxlength="4096" :placeholder="remote.endpoint_ref?'已私密保存，留空保留':'输入旧榜单服务地址'"/></label><label>读取凭据<input v-model="token" type="password" autocomplete="new-password" maxlength="4096" :placeholder="remote.credential_ref?'已私密保存，留空保留':'输入旧服务的 API 凭据'"/></label><label>允许访问的内网网段<textarea :value="remote.private_ranges.join('\n')" rows="3" placeholder="每行一个 CIDR，例如 192.168.50.6/32" @input="remote.private_ranges=$event.target.value.split('\n').map(s=>s.trim()).filter(Boolean)"/></label><VBtn color="primary" :disabled="busy||!(endpoint||remote.endpoint_ref)||!(token||remote.credential_ref)" @click="remotePreview">保存连接并预览读取范围</VBtn><details class="sb-technical"><summary>高级：已有私密引用</summary><Field :schema="bodySchema('/migration/source/preview')" name="source" v-model="remote"/></details></section>
 <section v-if="tab==='cutover'" class="sb-form-section"><h3>选择接下来由谁处理</h3><p>先配置好新实例的 AI 与榜单。这里会停止选中的旧功能，并准备启用新功能；每次保存后均核对实际状态。</p><VBtn variant="tonal" :disabled="busy" @click="readOwners">读取当前插件</VBtn><fieldset v-if="owners"><legend>停止哪些旧功能</legend><p v-if="!oldChoices.length">没有发现支持直接切换的旧插件版本。其他实例仍需根据下方冲突信息处理。</p><label v-for="p in oldChoices" :key="p.instance_id" class="sb-check"><input type="checkbox" :checked="selected.some(s=>s.instance_id===p.instance_id)" :disabled="busy" @change="oldChoice(p,$event.target.checked)"/><span>{{p.source}} · {{p.version}} · {{p.instance_id}}<small>{{p.source==='ChatGPTPlusUltra'?'仅停止原生名称识别辅助':'停止此实例的全部榜单发现'}} · {{p.active?'当前启用':'当前关闭'}}</small></span></label></fieldset><fieldset><legend>启用哪些新功能</legend><label v-for="f in featureOptions" :key="f.key" class="sb-check"><input v-model="featureChoice" :value="f.key" type="checkbox" :disabled="busy"/>{{f.title}}</label></fieldset><p class="sb-warning">切换会启用插件并退出演练模式，仅启用所选功能。未选旧插件时仍检查冲突，不表示外部服务已停止。</p><VBtn color="primary" :disabled="busy||!featureChoice.length||!owners" @click="planCutover">预览切换范围</VBtn><details v-if="owners" class="sb-technical"><summary>插件与冲突详情</summary><Record :value="owners"/></details></section>
 <p v-if="busy" role="status">正在处理…</p><p v-if="error" role="alert" class="sb-error">{{error}}</p><p v-if="nativeResult" role="status">已提交旧插件设置，请继续核对切换状态。</p>
 <section v-if="receipt" class="sb-migration-review" aria-label="迁移预览与进度"><header class="sb-heading"><h3>{{receiptTitle(receipt)}}</h3><VBtn variant="text" :disabled="busy" @click="loadReceipt">刷新进度</VBtn></header>
 <template v-if="receipt.kind==='IMPORT'"><p>历史记录 {{receipt.cursor}} / {{receipt.history_count}} 条已导入。旧成功记录不会被当作当前已入库。</p><ul class="sb-mapping-fields"><li v-for="f in receipt.fields" :key="f.source+f.field"><strong>{{f.field}}</strong><span>{{({MAPPED:'可以导入',MISSING:'旧记录未提供',ACTION_NOT_REPLAYED:'一次性动作不重放',UNMAPPED_RETAINED:'保留原记录，需另行配置',HISTORICAL_ONLY:'仅保留历史',READBACK_REQUIRED:'保存后需要核对',SUPPORTED_REQUIRES_BINDING:'需要选择关联方案',EXPLICIT_EQUIVALENT_REQUIRED:'需要确认对应规则'})[f.status]}}</span></li></ul></template>
 <template v-if="receipt.kind==='SOURCE'"><p>读取服务：{{receipt.read_scope?.origin}}</p><ul><li v-for="path in receipt.read_scope?.paths||[]" :key="path">GET {{path}}</li></ul><VBtn v-if="receipt.result_receipt_id" color="primary" @click="receiptId=receipt.result_receipt_id;loadReceipt()">继续预览导入内容</VBtn></template>
 <template v-if="receipt.kind==='CUTOVER'"><ol class="sb-migration-steps"><li>停止选中的旧功能</li><li>保存新配置</li><li>核对新功能已独立运行</li></ol><p v-if="receipt.state==='WAIT_OWNER'" class="sb-warning">仍有功能重叠或无法确认的插件状态。请查看冲突详情后重新核对。</p><p v-if="!rawJSONSupported" class="sb-error">浏览器不支持无损 JSON 数值，无法安全保存旧插件配置，请更新浏览器。</p><VBtn v-if="['READY_CONFIG','ROLLBACK_FENCED'].includes(receipt.state)" color="primary" @click="continueConfig">继续保存配置</VBtn><div class="sb-actions"><VBtn v-for="change in receipt.next_changes.filter(c=>c.instance_id!==client.pluginId)" :key="change.instance_id" variant="tonal" :disabled="busy||!confirm||!rawJSONSupported" @click="nativeChange(change)">保存 {{change.instance_id}} 的已选开关</VBtn></div></template>
 <details class="sb-technical"><summary>完整迁移依据与冲突详情</summary><Record :value="receipt"/></details>
 <details v-if="receipt.kind==='IMPORT'" class="sb-technical"><summary>高级：核对并关联旧历史</summary><p>每次明确导入最多 100 条；当前游标 {{receipt.cursor}} / {{receipt.history_count}}。已完成操作幂等；之后的配置编辑不会被重复导入覆盖。</p><button @click="history=!history">{{history?'收起':'查看'}}逐历史映射</button><Resource v-if="history" :key="receipt.receipt_id+'-'+historyKey" :client="client" :resource="['原始历史映射','/migration/receipts/{receipt_id}/history',{receipt_id:receipt.receipt_id}]" @select="selectedHistory=$event;linkConfirm=false"/><section v-if="history&&selectedHistory?.ordinal!==undefined"><h4>核对并链接第 {{selectedHistory.ordinal}} 条旧历史</h4><p>先核对当前任务与媒体库版本；旧成功状态仍只作历史记录，不会触发订阅或下载。</p><Record :value="selectedHistory"/><div class="sb-inline"><label>当前任务 ID<input v-model.number="taskId" type="number" min="1"></label><label>当前库版本 ID<input v-model="versionId" autocomplete="off"></label></div><label class="sb-check"><input v-model="linkConfirm" type="checkbox">确认上述旧记录与当前任务、库版本为同一媒体</label><button :disabled="busy||!linkConfirm||!taskId||!versionId" @click="linkHistory">链接已核实的当前记录</button></section><Record v-if="linkedRow" :value="linkedRow.link"/></details>

 <label class="sb-check"><input v-model="confirm" type="checkbox" :disabled="busy"/>我已核对上方范围，同意执行本步骤</label><div class="sb-actions"><VBtn v-if="receipt.kind==='IMPORT'" color="primary" :disabled="busy||!confirm||receipt.state==='IMPORTED'" @click="advance()">导入下一批（最多 100 条）</VBtn><VBtn v-if="receipt.kind==='SOURCE'&&!receipt.result_receipt_id" color="primary" :disabled="busy||!confirm" @click="advance()">读取配置与历史</VBtn><VBtn v-if="receipt.kind==='CUTOVER'" color="primary" :disabled="busy||!confirm" @click="advance('activate')">核对切换状态</VBtn></div><details v-if="receipt.kind==='CUTOVER'" class="sb-technical"><summary>回退到旧功能</summary><p>先隔离新入口，再逐项恢复旧功能；失败时保留记录，不能视为回退完成。</p><VBtn variant="text" color="warning" :disabled="busy||!confirm" @click="advance('rollback')">开始回退</VBtn><VBtn variant="text" :disabled="busy||!confirm" @click="advance('rollback_readback')">核对回退进度</VBtn></details>
 </section><details class="sb-technical"><summary>恢复之前的迁移记录</summary><div class="sb-inline"><label>迁移记录编号<input v-model="receiptId" autocomplete="off"/></label><VBtn variant="tonal" :disabled="busy||!receiptId" @click="loadReceipt">恢复记录</VBtn></div></details>
</section></template>
