<script setup>
import {ref,computed,onBeforeUnmount} from 'vue';
import Field from './Field.vue';import Record from './Record.vue';import Resource from './Resource.vue';
import {bodySchema,initial,clone,contract,validate} from './schema.mjs';
import {receiptBody,errorText,id} from './client.mjs';
import {saveLegacy} from './legacy.mjs';
const props=defineProps({client:Object,status:Object,nativeApi:Object});const emit=defineEmits(['changed','switch']);let mounted=true;
const rawJSONSupported=typeof JSON.rawJSON==='function'&&typeof JSON.isRawJSON==='function';
const nativeResult=ref(null);
const source=ref({source_instance:'ChatGPTPlusUltra',source_version:'',source_timezone:null}),file=ref(null),fileControl=ref(null),receipt=ref(null),receiptId=ref(''),busy=ref(false),error=ref(''),confirm=ref(false),history=ref(false);
const remote=ref(initial(bodySchema('/migration/source/preview'))),owners=ref(null),selected=ref([]),featureChoice=ref([]),configPreview=ref(null);
const featureOptions=computed(()=>{const c=props.status.current.value?.config;if(!c)return [];const options=[{key:'name_assistance',title:'内部名称辅助',module:'name_assistance',route_scope:'internal'},{key:'name_bridge',title:'NameRecognize 事件桥接',module:'name_bridge',route_scope:{event:'NameRecognize'}}];for(const route of c.ai_assist.chat_routes)options.push({key:'chat:'+JSON.stringify(route),title:'聊天 '+route.channel+' / '+route.userid,module:'chat',route_scope:route});for(const s of c.discovery.sources)options.push({key:'discovery:'+s.id,title:'发现来源 '+s.id,module:'discovery',route_scope:s.id});return options});
async function run(fn){if(busy.value)return;busy.value=true;error.value='';try{await fn()}catch(e){if(mounted)error.value=errorText(e)}finally{if(mounted)busy.value=false}}
async function loadReceipt(){return run(async()=>{const r=await props.client.get('/migration/receipts/'+encodeURIComponent(receiptId.value));if(mounted){receipt.value=r;confirm.value=false;history.value=false}})}
async function importPreview(){return run(async()=>{try{if(!file.value||file.value.size>2097152)throw Error('BOUNDED_FILE_REQUIRED');const bytes=new Uint8Array(await file.value.arrayBuffer());let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);if(!mounted)return;const r=await props.client.post('/migration/preview',{...source.value,content_base64:btoa(binary)});if(mounted){receipt.value=r;receiptId.value=r.receipt_id;confirm.value=false;history.value=false}}finally{file.value=null;if(fileControl.value)fileControl.value.value=''}})}
async function remotePreview(){return run(async()=>{const r=await props.client.post('/migration/source/preview',clone(remote.value));if(mounted){receipt.value=r;receiptId.value=r.receipt_id;confirm.value=false}})}
async function advance(action){if(!confirm.value)return;const saved=clone(receipt.value);const operation=id();return run(async()=>{let path,body=receiptBody(saved,operation);if(saved.kind==='IMPORT'){path='/migration/import';body={...body,cursor:saved.cursor,limit:100}}else if(saved.kind==='SOURCE')path='/migration/source/read';else{path='/migration/cutover';body.action=action}const r=await props.client.post(path,body);if(mounted){receipt.value=r;receiptId.value=r.receipt_id;confirm.value=false;emit('changed')}})}
async function readOwners(){return run(async()=>{const o=await props.client.get('/migration/owners');if(mounted)owners.value=o})}
async function planCutover(){return run(async()=>{if(!featureChoice.value.length)throw Error('FEATURE_REQUIRED');const chosen=featureOptions.value.filter(x=>featureChoice.value.includes(x.key));const desired=clone(props.status.current.value.config);desired.enabled=true;desired.dry_run=false;desired.ai_assist.name_assistance_enabled=false;desired.ai_assist.name_recognize_bridge=false;desired.ai_assist.chat_enabled=false;desired.discovery.enabled=false;for(const s of desired.discovery.sources)s.enabled=false;for(const f of chosen){if(f.module==='discovery'){desired.discovery.enabled=true;desired.discovery.sources.find(s=>s.id===f.route_scope).enabled=true}else{desired.ai_assist.enabled=true;desired.ai_assist[{name_assistance:'name_assistance_enabled',name_bridge:'name_recognize_bridge',chat:'chat_enabled'}[f.module]]=true}}const p=await props.client.post('/configuration/preview',{revision:props.status.current.value.revision,digest:props.status.current.value.digest,patch:desired});if(!p.valid)throw Error('INVALID_CONFIGURATION');if(!mounted)return;configPreview.value=p;const features=chosen.map(f=>({module:f.module,instance_id:props.client.pluginId,config_digest:p.feature_digests[f.module==='discovery'?'discovery':'ai_assist'],route_scope:f.route_scope}));const r=await props.client.post('/migration/cutover/preview',{configuration_receipt:p.receipt_id,features,selected:clone(selected.value)});if(mounted){receipt.value=r;receiptId.value=r.receipt_id;confirm.value=false}})}
async function nativeChange(change){if(!confirm.value)return;return run(async()=>{const fresh=await props.client.get('/migration/receipts/'+encodeURIComponent(receipt.value.receipt_id));const exact=fresh.next_changes.find(c=>c.instance_id===change.instance_id);if(!exact||JSON.stringify(exact)!==JSON.stringify(change))throw Error('STALE_CUTOVER');const step=fresh.steps.find(s=>s.instance_id===change.instance_id);const result=await saveLegacy(props.nativeApi,exact,step,()=>mounted);if(mounted){nativeResult.value=result;confirm.value=false;error.value='';receipt.value=fresh;emit('changed');}})}
onBeforeUnmount(()=>{mounted=false;file.value=null;source.value={};remote.value={};selected.value=[];configPreview.value=null});
</script>
<template><section><h3>迁移与切换工作台</h3><p v-if="!rawJSONSupported" class="sb-error">此浏览器不支持无损 JSON 数值。旧实例保存需要更新浏览器；其他预览和只读状态仍可用。</p><Record v-if="nativeResult" :value="nativeResult"/><p>先备份原配置与历史。导入保持关闭 / dry-run；不开启旧一次性按钮，不把旧历史状态当成目标事实。无旧实例停止回执不能声称外部 V2 已停止。</p>
 <details><summary>导入用户明确选择的离线导出（最多 2 MiB）</summary><Field v-for="key in ['source_instance','source_version','source_timezone']" :key="key" :name="key" :schema="bodySchema('/migration/preview').properties[key]" v-model="source[key]"/><label>私密导出文件<input ref="fileControl" type="file" accept="application/json,.json" @change="file=$event.target.files[0]"></label><button :disabled="busy||!file" @click="importPreview">逐字段与历史预览</button></details>
 <details><summary>读取明确授权旧榜单服务</summary><p>仅使用先前写入的地址 / 凭据引用；预览列出两条只读路径，确认后才读取。无重定向或公共替代服务。</p><Field :schema="bodySchema('/migration/source/preview')" name="source" v-model="remote"/><button :disabled="busy" @click="remotePreview">预览只读来源</button></details>
 <details><summary>当前宿主唯一处理者切换</summary><p>先在配置页完成服务、模型和来源配置并保持关闭 / dry-run。下面明确选择期望开启的功能；预览才生成最终配置，不会保存。停止旧功能须精确选中其当前摘要。部分旧 AI 运行开关不可证实的情况保持 WAIT_OWNER / LEGACY_RUNTIME_FLAGS_UNVERIFIED。</p><button :disabled="busy" @click="readOwners">读取当前宿主实例与摘要</button><Record v-if="owners" :value="owners.plugins||owners"/>
 <fieldset><legend>期望启用的新功能</legend><label v-for="f in featureOptions" :key="f.key" class="sb-check"><input v-model="featureChoice" :value="f.key" type="checkbox">{{f.title}}</label></fieldset>
 <Field :schema="bodySchema('/migration/cutover/preview').properties.selected" name="selected" v-model="selected"/><p>空的旧功能选择仅表示检查当前宿主没有重叠，不证明任何外部旧服务已停止。预览将打开新实例 enabled、关闭 dry-run，并启用选中模块。</p><button :disabled="busy||!featureChoice.length" @click="planCutover">预检最终配置并预览切换</button></details>
 <div class="sb-inline"><label>已有回执 ID<input v-model="receiptId" autocomplete="off"></label><button :disabled="busy||!receiptId" @click="loadReceipt">读取 / 恢复回执</button></div>
 <p v-if="busy" role="status">正在处理明确请求…</p><p v-if="error" role="alert" class="sb-error">{{error}}</p>
 <template v-if="receipt"><h3>{{receipt.kind}} · {{receipt.state}}</h3><Record :value="receipt"/><p v-if="receipt.kind==='SOURCE'">此处只报告来源读取。读取完成后使用派生 IMPORT 回执处理历史，不等于切换完成。</p><button v-if="receipt.result_receipt_id" @click="receiptId=receipt.result_receipt_id;loadReceipt()">读取派生导入回执</button>
 <template v-if="receipt.kind==='IMPORT'"><p>每次明确导入最多 100 条；当前游标 {{receipt.cursor}} / {{receipt.history_count}}。已完成操作幂等；之后的配置编辑不会被重复导入覆盖。</p><button @click="history=!history">{{history?'收起':'查看'}}逐历史映射</button><Resource v-if="history" :key="receipt.receipt_id" :client="client" :resource="['原始历史映射','/migration/receipts/{receipt_id}/history',{receipt_id:receipt.receipt_id}]"/></template>
 <template v-if="receipt.kind==='CUTOVER'"><p>READY_CONFIG 仅表示允许保存所绑定配置；ACTIVE 才是当前宿主新模块唯一处理者。复制此回执 ID {{receipt.receipt_id}}，在配置页加载后执行宿主 Save，再返回本回执“核对 / 激活”。</p><button @click="emit('switch')">打开配置页提交已就绪配置</button><p v-if="receipt.next_changes.length">待执行旧实例配置变更如下。必须先精确验证完整原配置摘要，并只修改列出的布尔字段；保存后仍需本回执的实际读取确认。宿主 PUT 没有 CAS。</p></template>
 <div v-if="receipt.kind==='CUTOVER'" class="sb-actions"><button v-for="change in receipt.next_changes.filter(c=>c.instance_id!==client.pluginId)" :key="change.instance_id" :disabled="busy||!confirm||!rawJSONSupported" @click="nativeChange(change)">按精确摘要保存旧实例 {{change.instance_id}} 的已选开关</button></div>
 <label class="sb-check"><input v-model="confirm" type="checkbox">确认当前回执的精确对象、理由与权限</label><div class="sb-actions"><button v-if="receipt.kind==='IMPORT'" :disabled="busy||!confirm||receipt.state==='IMPORTED'" @click="advance()">导入下一页</button><button v-if="receipt.kind==='SOURCE'" :disabled="busy||!confirm" @click="advance()">执行两次授权只读请求</button><template v-if="receipt.kind==='CUTOVER'"><button :disabled="busy||!confirm" @click="advance('activate')">核对 / 激活当前回执</button><button :disabled="busy||!confirm" @click="advance('rollback')">开始回退，先隔离新入口</button><button :disabled="busy||!confirm" @click="advance('rollback_readback')">核对回退步骤</button></template></div></template>
</section></template>
