<script setup>
import Quantity from './Quantity.vue';import SitePicker from './SitePicker.vue';import Field from './Field.vue';import PathInput from './PathInput.vue';import {contract} from './schema.mjs';
const props=defineProps({group:String,modelValue:Object,api:Object,readonly:Boolean});const emit=defineEmits(['update:modelValue']);const set=(key,value)=>emit('update:modelValue',{...props.modelValue,[key]:value});
</script>
<template><section>
 <template v-if="group==='candidates'"><h4>搜索哪些站点</h4><SitePicker :api="api" :model-value="modelValue.site_ids" :readonly="readonly" @update:model-value="set('site_ids',$event)"/><p v-if="!modelValue.site_ids.length" class="sb-muted">尚未授权搜索站点。</p><section class="sb-form-section"><h4>搜索方式</h4><label>使用的名称<select :value="modelValue.query_scope" :disabled="readonly" @change="set('query_scope',$event.target.value)"><option value="trusted_aliases">原名与已经核实的别名</option><option value="original">仅原名</option></select></label><Quantity label="候选刷新间隔" :model-value="modelValue.refresh_seconds" :min="1" :max="86400" :readonly="readonly" @update:model-value="set('refresh_seconds',$event)"/></section><details class="sb-technical"><summary>搜索预算与排除设置</summary><div class="sb-grid"><Field v-for="key in ['keywords','pages','concurrency','results','requests','supplement_limit','exclusion_scope','exclusion_seconds']" :key="key" :name="key" :schema="contract.schemas.Candidates.properties[key]" :model-value="modelValue[key]" :readonly="readonly" @update:model-value="set(key,$event)"/><Quantity label="站点请求间隔" :model-value="modelValue.interval" :max="10" :readonly="readonly" @update:model-value="set('interval',$event)"/></div></details></template>
 <template v-if="group==='lifecycle'"><p class="sb-muted">追踪期限与一次性补集机会分别计时；0 天表示不限制追踪期限。</p><div class="sb-grid"><label v-for="[key,title] in [['movie_days','电影追踪期限（天）'],['tv_days','剧集追踪期限（天）']]" :key="key">{{title}}<input type="number" min="0" max="36500" step="1" :value="modelValue[key]" :disabled="readonly" @input="set(key,Number($event.target.value))"></label><label>期限从何时起算<select :value="modelValue.expiry_mode" :disabled="readonly" @change="set('expiry_mode',$event.target.value)"><option value="COMPLETE_COLLECTED">目标收集完成后</option><option value="LAST_INGEST">最后一次确认入库后</option></select></label><label>完结剧集的处理方式<select :value="modelValue.completed_mode" :disabled="readonly" @change="set('completed_mode',$event.target.value)"><option value="EPISODE">按集比较</option><option value="PACK">按整包比较</option></select></label><Quantity label="一次性机会时长" :model-value="modelValue.oneshot_seconds" :min="1" :readonly="readonly" @update:model-value="set('oneshot_seconds',$event)"/></div></template>
 <template v-if="group==='recovery'"><label class="sb-toggle-row"><span><strong>启动后核对未完成处理</strong><small>先读取实际状态，再决定是否继续，避免重复交付。</small></span><input type="checkbox" :checked="modelValue.startup_reconcile" :disabled="readonly" @change="set('startup_reconcile',$event.target.checked)"></label><div class="sb-grid"><Quantity v-for="[key,title] in [['reconcile_seconds','完整核对间隔'],['active_poll_seconds','在途目标检查间隔']]" :key="key" :label="title" :model-value="modelValue[key]" :min="1" :readonly="readonly" @update:model-value="set(key,$event)"/></div><label class="sb-check"><input type="checkbox" :checked="modelValue.watcher" :disabled="readonly" @change="set('watcher',$event.target.checked)">同时使用文件监听（定期核对仍保留）</label><details class="sb-technical"><summary>每轮核对预算与恢复依据</summary><div class="sb-grid"><Field v-for="key in ['pages','entries']" :key="key" :name="key" :schema="contract.schemas.Recovery.properties[key]" :model-value="modelValue[key]" :readonly="readonly" @update:model-value="set(key,$event)"/><Quantity label="每轮核对最多耗时" :model-value="modelValue.seconds" :min="0.1" :max="30" :readonly="readonly" @update:model-value="set('seconds',$event)"/></div><p>{{modelValue.consumer_recovery_ref?'已保留消费者恢复依据；此字段本身不能证明当前可恢复。':'尚无消费者恢复依据。'}} 普通设置不修改恢复引用。</p></details></template>
 <template v-if="group==='safety'"><div class="sb-grid"><Quantity kind="bytes" label="本地磁盘至少保留" note="这是剩余空间阈值，不是可写目录授权。" :model-value="modelValue.minimum_free_bytes" :readonly="readonly" @update:model-value="set('minimum_free_bytes',$event)"/><Quantity label="网络请求超时" :model-value="modelValue.network_timeout" :min="1" :max="120" :readonly="readonly" @update:model-value="set('network_timeout',$event)"/><label>同时运行的工作数<input type="number" min="1" max="8" step="1" :value="modelValue.worker_limit" :disabled="readonly" @input="set('worker_limit',Number($event.target.value))"></label></div><section class="sb-form-section"><h4>授权试验目录</h4><p class="sb-muted">仅填写已经允许用于试验的绝对路径；不会自动推导或扩大范围。</p><div v-for="(path,index) in modelValue.test_roots" :key="index" class="sb-path-item"><PathInput label="试验根目录" :model-value="path" :readonly="readonly" @update:model-value="set('test_roots',modelValue.test_roots.map((p,i)=>i===index?$event:p))"/><VBtn variant="text" color="error" :disabled="readonly" @click="set('test_roots',modelValue.test_roots.filter((_,i)=>i!==index))">移除目录</VBtn></div><VBtn variant="tonal" :disabled="readonly" @click="set('test_roots',[...modelValue.test_roots,''])">添加试验目录</VBtn></section></template>
</section></template>
