<script setup>
import {ref,computed} from 'vue';import {useRead} from './read.mjs';import {stateLabel,reasonText,dimensions,lockText} from './media.mjs';import {errorText} from './client.mjs';import {contract,clean} from './schema.mjs';import Record from './Record.vue';
const props=defineProps({client:Object,status:Object});const emit=defineEmits(['configure']);const offset=ref(0),candidateOffset=ref(0),category=ref(''),candidate=ref(''),current=ref(''),result=ref(null),simulating=ref(false),simError=ref('');let alive=true;
import {onBeforeUnmount} from 'vue';onBeforeUnmount(()=>{alive=false});
const {data,error,busy,refresh}=useRead(async signal=>{const [policies,categories,candidates]=await Promise.all([props.client.get('/policies',{params:{limit:20,offset:offset.value},signal}),props.client.get('/configuration/categories',{signal}),props.client.get('/candidates',{params:{limit:25,offset:candidateOffset.value},signal})]);if(!category.value&&policies.items.length)category.value=policies.items[0].category_id;return {policies,categories,candidates}});
const selected=computed(()=>data.value?.policies.items.find(p=>p.category_id===category.value)||data.value?.policies.items[0]);
const categoryName=id=>data.value?.categories.categories?.find(c=>c.id===id)?.name||id;

function reset(){result.value=null;simError.value=''}
async function simulate(){if(simulating.value||busy.value||error.value||!category.value||!candidate.value||props.status.error.value)return;simulating.value=true;reset();
 try{const selected=data.value.candidates.items.find(c=>c.candidate_key===candidate.value),baseline=data.value.candidates.items.find(c=>c.candidate_key===current.value);if(!selected)return;
 const body={config_revision:props.status.current.value.revision,runtime_generation:props.status.health.value.generation,category_id:category.value,candidate:clean(contract.schemas.PolicySample,selected.evidence),current:baseline?[{version_id:baseline.candidate_key,raw:clean(contract.schemas.PolicySample,baseline.evidence),active:true,reliable:true}]:[]};
 const r=await props.client.post('/policies/simulate',body);if(alive)result.value=r}
 catch(e){if(alive)simError.value=errorText(e)}finally{if(alive)simulating.value=false}}
defineExpose({load:refresh});
</script>
<template><section aria-label="质量策略"><header class="sb-heading"><h2>质量策略</h2><VBtn color="primary" @click="emit('configure','policy')">编辑策略</VBtn></header>
 <p v-if="error" class="sb-error" role="alert">{{error}} 以下结果可能已过期。</p><p v-if="busy&&!data" role="status">正在读取策略…</p>
 <template v-if="data"><p v-if="!data.policies.items.length" class="sb-empty">尚未绑定分类策略。先为 MoviePilot 分类选择策略，再纳管作品。</p><div class="sb-policy-workspace"><nav aria-label="策略分类" class="sb-policy-nav"><button v-for="p in data.policies.items" :key="p.category_id" :aria-current="selected?.category_id===p.category_id" @click="category=p.category_id;reset()"><strong>{{categoryName(p.category_id)}}</strong><small>{{p.binding}}</small></button><div v-if="data.policies.total>20" class="sb-pagination"><VBtn :disabled="busy||!offset" @click="offset-=20;category='';refresh()">上页</VBtn><VBtn :disabled="busy||data.policies.next_offset===null" @click="offset=data.policies.next_offset;category='';refresh()">下页</VBtn></div></nav><div v-if="selected" class="sb-policy-detail"><h3>{{categoryName(selected.category_id)}}</h3>
 <p class="sb-muted">使用「{{selected.binding}}」策略 · 修改后影响绑定该策略的分类。</p><p v-if="!selected.policy_revision" class="sb-warning">当前为已保存规则，运行策略尚未就绪。</p>
 <section class="sb-form-section"><h4>收录条件</h4><div class="sb-rule-summary"><span>允许分辨率</span><strong>{{selected.summary?.resolutions?.map(r=>r+'p').join('、')||'等待规则信息'}}</strong><span>发布组</span><span>{{selected.summary?.group||'等待规则信息'}}</span><span>片源</span><span>{{selected.summary?.source||'等待规则信息'}}</span></div><p class="sb-muted">还需通过身份、范围、中文音轨或字幕及基础过滤检查；资料不全会等待补充。</p></section>
 <details v-if="selected.summary?.rule_details?.length" class="sb-rule-reference"><summary>发布组与片源的具体条件</summary><dl class="sb-rule-explanations"><template v-for="r in selected.summary.rule_details" :key="r.name"><dt>{{r.title||r.name}}</dt><dd>{{r.summary}}<details class="sb-technical"><summary>精确匹配表达式</summary><p class="sb-value">{{r.explanation}}</p></details></dd></template></dl></details><section class="sb-form-section"><h4>优先顺序</h4><p class="sb-muted">按以下顺序比较，第一个不同的条件决定优劣。</p><ol class="sb-rank-rules"><li v-for="row in selected.summary?.comparison||[]" :key="row.dimension"><strong>{{dimensions[row.dimension]||row.dimension}}</strong><span>{{row.order.join(' › ')}}<small v-if="row.note">{{row.note}}</small></span></li></ol></section>
 <section class="sb-form-section"><h4>锁定与额外条件</h4><p v-if="!Object.keys(selected.configuration.locks||{}).length" class="sb-muted">没有额外锁定条件。</p><div v-for="(value,key) in selected.configuration.locks" :key="key" class="sb-binding-row"><span>{{dimensions[key]||({group:'发布组',platform:'平台',season:'季'})[key]||key}}</span><strong>{{lockText(key,value)}}</strong></div><p v-if="selected.configuration.admission||Object.keys(selected.configuration.overrides||{}).length" class="sb-warning">存在自定义准入或识别规则，请结合下方真实候选预演核对结果。</p><details class="sb-technical"><summary>高级规则与版本依据</summary><Record :value="{自定义: selected.configuration.overrides,准入:selected.configuration.admission,版本:selected.policy_revision}"/></details></section>
 <section class="sb-form-section"><h4>用真实候选预演</h4><p class="sb-muted">比较已保存规则，不执行下载。对照资源仅用作本次样本。</p><div class="sb-grid"><label>分类<select v-model="category" :disabled="simulating" @change="reset"><option value="">选择分类</option><option v-for="p in data.policies.items" :key="p.category_id" :value="p.category_id">{{categoryName(p.category_id)}}</option></select></label><label>待比较资源<select v-model="candidate" :disabled="simulating" @change="reset"><option value="">选择已有候选</option><option v-for="c in data.candidates.items" :key="c.candidate_key" :value="c.candidate_key">{{c.title}}</option></select></label><label>对照资源<select v-model="current" :disabled="simulating" @change="reset"><option value="">无对照，仅检查准入</option><option v-for="c in data.candidates.items" :key="c.candidate_key" :value="c.candidate_key">{{c.title}}</option></select></label></div>
 <p v-if="!data.candidates.items.length" class="sb-muted">尚无真实候选。正常订阅搜索后会积累候选记录。</p><div class="sb-actions"><VBtn color="primary" :disabled="busy||simulating||!!error||!category||!candidate||!!status.error.value" @click="simulate">{{simulating?'正在比较…':'预演当前策略'}}</VBtn><VBtn :disabled="busy||simulating||!candidateOffset" variant="text" @click="candidateOffset-=25;candidate='';current='';reset();refresh()">上一页候选</VBtn><VBtn :disabled="busy||simulating||data.candidates.next_offset===null" variant="text" @click="candidateOffset=data.candidates.next_offset;candidate='';current='';reset();refresh()">下一页候选</VBtn></div><p v-if="simError" role="alert" class="sb-error">{{simError}}</p>
 <div v-if="result" class="sb-comparison"><h3>{{stateLabel(result.evidence?.evaluation?.status||result.status)}}</h3><p>{{reasonText(result.evidence?.evaluation?.reason)}}</p><Record :value="result.evidence?.evaluation?.decisions?.simulation||result.evidence?.comparisons||{}"/><details class="sb-technical"><summary>完整比较依据</summary><Record :value="result.evidence"/></details></div></section>
 </div></div></template></section></template>
