<script setup>
import {ref,computed,watch,onMounted,nextTick} from 'vue';
import PredicateEditor from './PredicateEditor.vue';
import PolicySummary from './PolicySummary.vue';
import PolicySimulation from './PolicySimulation.vue';
import {usePanelPosition} from './panel.mjs';
const props=defineProps({modelValue:Object,saved:Object,categories:Array,defaults:Object,revision:Number,readonly:Boolean,focus:Object,plans:Array,client:Object,status:Object,catalog:Object,archiveBindings:Object});const emit=defineEmits(['update:modelValue','selection']);
const category=ref(props.focus?.category||Object.keys(props.modelValue.bindings)[0]||''),binding=ref(''),ruleName=ref(''),selected=ref(props.focus?.policy||props.modelValue.bindings[category.value]||Object.keys(props.defaults||{})[0]||''),view=ref(['rules','trial','scope','global'].includes(props.focus?.tab)?props.focus.tab:'rules'),selector=ref(null),position=usePanelPosition();
watch([selected,category,view],()=>emit('selection',{policy:selected.value,category:category.value,tab:view.value,label:selected.value}),{immediate:true});
const categoriesUsing=computed(()=>[...new Set([...Object.entries(props.archiveBindings||{}),...Object.entries(props.modelValue.bindings)].filter(([,name])=>name===selected.value).map(([id])=>id))]);
const effectivePolicy=computed(()=>category.value?props.saved?.bindings?.[category.value]||'':'');
const draftPolicy=computed(()=>category.value?props.modelValue.bindings[category.value]||'':'');
const categoryName=computed(()=>props.categories?.find(c=>c.id===category.value)?.name||'分类名称暂不可用');
const policyNames=computed(()=>Object.keys({...props.defaults,...props.modelValue.templates}));
const namesUsing=computed(()=>categoriesUsing.value.map(id=>props.categories?.find(c=>c.id===id)?.name||'已保存分类（名称暂不可用）'));
const plansUsing=computed(()=>(props.plans||[]).filter(plan=>categoriesUsing.value.includes(plan.category_id)).map(plan=>plan.display_name||plan.id));
const ruleNames=computed(()=>[...new Set([...(props.catalog?.predicate_rules||[]),...Object.keys(props.modelValue.overrides)])]);
const trialPolicy=computed(()=>({...props.modelValue,bindings:{...props.modelValue.bindings,...(category.value&&selected.value?{[category.value]:selected.value}:{})}}));
watch(()=>props.defaults,defaults=>{if(!selected.value)selected.value=Object.keys(defaults||{})[0]||''});
async function revealSelected(){await nextTick();const list=selector.value,item=list?.querySelector?.('[aria-current="page"]');if(!item||!list.clientWidth)return;const left=item.offsetLeft,right=left+item.offsetWidth;if(left<list.scrollLeft)list.scrollLeft=left;else if(right>list.scrollLeft+list.clientWidth)list.scrollLeft=right-list.clientWidth}
watch(selected,revealSelected);onMounted(revealSelected);
function choose(name){selected.value=name;category.value=Object.keys(props.modelValue.bindings).find(id=>props.modelValue.bindings[id]===name)||''}
function show(value){view.value=value;position.top()}
const dimensions={resolution:'分辨率',picture:'画质 / HDR',special:'特效字幕',source:'片源',hq:'高码率',audio:'音轨',anime:'动画资源偏好'};
const template=computed(()=>props.modelValue.templates?.[selected.value]||props.defaults?.[selected.value]);
const update=value=>emit('update:modelValue',{...props.modelValue,...value});
function bind(){if(!category.value||!binding.value)return;update({bindings:{...props.modelValue.bindings,[category.value]:binding.value},classification_revision:props.revision||props.modelValue.classification_revision});selected.value=binding.value}
function remove(categoryId){const bindings={...props.modelValue.bindings};delete bindings[categoryId];update({bindings})}
function edit(key,value){if(!template.value)return;update({templates:{...props.modelValue.templates,[selected.value]:{...template.value,[key]:value}}})}
function move(index,delta){const list=[...template.value.dimensions],next=index+delta;if(next<0||next>=list.length)return;[list[index],list[next]]=[list[next],list[index]];edit('dimensions',list)}
function rule(name,expr){const rules={...props.modelValue.overrides};if(expr===null)delete rules[name];else rules[name]=expr;update({overrides:rules})}
function addRule(){const name=ruleName.value.trim();if(!name||Object.hasOwn(props.modelValue.overrides,name))return;rule(name,{regex:['title','']});ruleName.value=''}
function reset(){const templates={...props.modelValue.templates};delete templates[selected.value];update({templates})}
function lock(key,value){const locks={...props.modelValue.locks};if(value===null||value==='')delete locks[key];else locks[key]=value;update({locks})}
const lockChoices={resolution:[[1080,'1080p'],[2160,'2160p']],picture:[[0,'普通画质'],[1,'HDR'],[2,'Dolby Vision']],source:[['web','WEB'],['bluray','Blu-ray'],['remux','REMUX']],audio:[[0,'基础音轨'],[1,'Dolby Digital Plus'],[2,'沉浸式音轨'],[3,'无损音轨']],hq:[[false,'非 HQ'],[true,'HQ']]};
</script>

<template><section aria-label="分类质量策略" class="sb-policy-editor"><nav ref="selector" class="sb-policy-selector" aria-label="策略列表"><button v-for="name in policyNames" :key="name" :aria-current="selected===name?'page':undefined" @click="choose(name)"><strong>{{name}}</strong><span>{{Object.values(modelValue.bindings).filter(v=>v===name).length}} 个分类使用</span></button></nav><div class="sb-policy-edit-body"><nav class="sb-settings-tabs" aria-label="策略功能"><button :aria-current="view==='rules'?'page':undefined" @click="show('rules')">规则</button><button :aria-current="view==='trial'?'page':undefined" @click="show('trial')">试算</button><button :aria-current="view==='scope'?'page':undefined" @click="show('scope')">使用范围</button><button :aria-current="view==='global'?'page':undefined" @click="show('global')">全局限制</button></nav>
 <div v-if="view==='scope'" class="sb-policy-rules"><section class="sb-form-section"><h3>使用范围</h3><p>{{namesUsing.join('、')||'尚未绑定分类'}}<span v-if="plansUsing.length"> · {{plansUsing.join('、')}}</span></p></section><section class="sb-form-section"><h3>分类使用的策略</h3><div v-for="(name,categoryId) in modelValue.bindings" :key="categoryId" class="sb-binding-row"><strong>{{categories?.find(c=>c.id===categoryId)?.name||'已保存分类（名称暂不可用）'}}</strong><span>{{name}}</span><VBtn variant="text" :disabled="readonly" @click="remove(categoryId)">移除绑定</VBtn></div><div class="sb-grid"><VSelect v-model="category" label="MoviePilot 分类" :items="(categories||[]).map(c=>({...c,props:{disabled:!c.enabled}}))" item-title="name" item-value="id" :disabled="readonly" variant="outlined"/><VSelect v-model="binding" label="质量策略" :items="Object.keys({...defaults,...modelValue.templates})" :disabled="readonly" variant="outlined"/></div><VBtn variant="tonal" :disabled="readonly||!category||!binding" @click="bind">应用到此分类</VBtn></section></div>

 <div v-else-if="view==='rules'" class="sb-policy-rules"><template v-if="template"><div class="sb-heading"><h3>{{selected}}</h3><VBtn variant="text" :disabled="readonly||!modelValue.templates?.[selected]" @click="reset">恢复默认</VBtn></div><p class="sb-muted">修改在保存后生效；试算页使用当前草稿。</p><fieldset :disabled="readonly"><legend>允许的分辨率</legend><label v-for="r in [2160,1080]" :key="r" class="sb-inline"><input type="checkbox" :checked="template.resolutions.includes(r)" @change="edit('resolutions',$event.target.checked?[...template.resolutions,r]:template.resolutions.filter(v=>v!==r))">{{r}}p</label></fieldset><div class="sb-grid"><label>发布组准入<select :value="template.group" :disabled="readonly" @change="edit('group',$event.target.value)"><option value="any">不限制发布组</option><option value="official">官方发布组规则</option><option value="anime">动画发布组规则</option><option value="hhweb">HHWEB 规则</option></select></label><label>片源准入<select :value="template.source" :disabled="readonly" @change="edit('source',$event.target.value)"><option value="any">不额外限制片源</option><option value="movie">影视片源规则</option><option value="web">仅 WEB</option></select></label></div><h3>比较顺序</h3><p class="sb-muted">从上到下比较，第一个不同的维度决定优劣。不是加权总分。</p><ol class="sb-dimension-list"><li v-for="(d,index) in template.dimensions" :key="d"><strong>{{index+1}}. {{dimensions[d]}}</strong><div class="sb-actions"><VBtn variant="text" :aria-label="'上移'+dimensions[d]" :disabled="readonly||index===0" @click="move(index,-1)">上移</VBtn><VBtn variant="text" :aria-label="'下移'+dimensions[d]" :disabled="readonly||index===template.dimensions.length-1" @click="move(index,1)">下移</VBtn><VBtn variant="text" :disabled="readonly||template.dimensions.length===1" @click="edit('dimensions',template.dimensions.filter(v=>v!==d))">移除</VBtn></div></li></ol><div class="sb-actions"><VBtn v-for="d in Object.keys(dimensions).filter(d=>!template.dimensions.includes(d))" :key="d" variant="tonal" :disabled="readonly" @click="edit('dimensions',[...template.dimensions,d])">＋ {{dimensions[d]}}</VBtn></div></template></div>
  <section v-else-if="view==='global'" class="sb-global-policy"><h3>所有策略的限制</h3><p class="sb-muted">以下条件影响所有已绑定分类和使用它们的方案。</p><h4>明确锁定条件</h4><div class="sb-grid"><label v-for="(choices,key) in lockChoices" :key="key">{{dimensions[key]}}<select :value="modelValue.locks[key]===undefined?'':String(modelValue.locks[key])" :disabled="readonly" @change="lock(key,$event.target.value===''?null:choices.find(v=>String(v[0])===$event.target.value)[0])"><option value="">不锁定</option><option v-for="[value,title] in choices" :key="String(value)" :value="String(value)">{{title}}</option></select></label><label v-for="[key,title] in [['group','发布组'],['platform','平台']]" :key="key">{{title}}<input :value="modelValue.locks[key]||''" :disabled="readonly" placeholder="不锁定" @input="lock(key,$event.target.value)"></label><label>只接收指定季度<input type="number" min="0" max="999" placeholder="不锁定" :value="modelValue.locks.season??''" :disabled="readonly" @input="lock('season',$event.target.value===''?null:Number($event.target.value))"></label></div><section class="sb-form-section"><h4>额外收录条件</h4><label class="sb-inline"><input type="checkbox" :checked="!!modelValue.admission" :disabled="readonly" @change="update({admission:$event.target.checked?{literal:true}:null})">启用额外收录条件</label><PredicateEditor v-if="modelValue.admission" :model-value="modelValue.admission" :readonly="readonly" :fields="catalog?.predicate_fields||[]" :rules="ruleNames" @update:model-value="update({admission:$event})"/></section><section><h4>自定义匹配规则</h4><p>修改同名规则会影响所有引用该规则的策略。</p><section v-for="(expression,name) in modelValue.overrides" :key="name" class="sb-form-section"><h5>{{name}}</h5><PredicateEditor :model-value="expression" :readonly="readonly" :fields="catalog?.predicate_fields||[]" :rules="ruleNames.filter(n=>n!==name)" @update:model-value="rule(name,$event)"/><VBtn variant="text" :disabled="readonly" @click="rule(name,null)">移除自定义条件</VBtn></section><div class="sb-actions"><label>规则名称<input v-model="ruleName" maxlength="80" :disabled="readonly" :list="'sb-rule-names-'+selected"></label><datalist :id="'sb-rule-names-'+selected"><option v-for="name in catalog?.predicate_rules||[]" :key="name" :value="name"/></datalist><VBtn variant="tonal" :disabled="readonly||!ruleName.trim()||Object.hasOwn(modelValue.overrides,ruleName.trim())" @click="addRule">添加规则</VBtn></div></section></section>

 <div v-else class="sb-policy-test-column"><VSelect v-model="category" label="试算分类" :items="(categories||[]).filter(c=>c.enabled)" item-title="name" item-value="id" variant="outlined"/><p v-if="!category" class="sb-notice">请选择试算分类，避免把上一份策略的分类当成当前上下文。</p><p v-else-if="draftPolicy!==effectivePolicy" class="sb-notice">此分类当前生效的是“{{effectivePolicy||'未绑定策略'}}”；本次草稿将改为“{{draftPolicy||'未绑定策略'}}”。保存前，两者分别试算。</p><p v-else-if="effectivePolicy!==selected" class="sb-notice">此分类当前生效的是“{{effectivePolicy||'未绑定策略'}}”；下方可试算“{{selected}}”的本次修改，不能将它当成当前生效策略。</p><PolicySummary v-if="client&&status&&category" :policy="trialPolicy" :category="category" :client="client" :status="status"/><PolicySimulation v-if="client&&status" :client="client" :status="status" :policy="trialPolicy" :category="category" :category-name="categoryName" :policy-name="selected" :current-policy-name="effectivePolicy" :effective="!!category&&effectivePolicy===selected"/></div>
</div></section></template>
