<script setup>
import {ref,computed,watch} from 'vue';
import PredicateEditor from './PredicateEditor.vue';
import PolicySummary from './PolicySummary.vue';
import PolicySimulation from './PolicySimulation.vue';
const props=defineProps({modelValue:Object,categories:Array,defaults:Object,revision:Number,readonly:Boolean,focus:Object,plans:Array,client:Object,status:Object,catalog:Object,archiveBindings:Object});const emit=defineEmits(['update:modelValue','selection']);
const category=ref(props.focus?.category||Object.keys(props.modelValue.bindings)[0]||''),binding=ref(''),ruleName=ref(''),selected=ref(props.focus?.policy||props.modelValue.bindings[category.value]||Object.keys(props.defaults||{})[0]||'');
watch([selected,category],()=>emit('selection',{policy:selected.value,category:category.value,label:selected.value}),{immediate:true});
const categoriesUsing=computed(()=>[...new Set([...Object.entries(props.archiveBindings||{}),...Object.entries(props.modelValue.bindings)].filter(([,name])=>name===selected.value).map(([id])=>id))]);
const namesUsing=computed(()=>categoriesUsing.value.map(id=>props.categories?.find(c=>c.id===id)?.name||'已保存分类（名称暂不可用）'));
const plansUsing=computed(()=>(props.plans||[]).filter(plan=>categoriesUsing.value.includes(plan.category_id)).map(plan=>plan.display_name||plan.id));
const ruleNames=computed(()=>[...new Set([...(props.catalog?.predicate_rules||[]),...Object.keys(props.modelValue.overrides)])]);
const trialPolicy=computed(()=>({...props.modelValue,bindings:{...props.modelValue.bindings,...(category.value&&selected.value?{[category.value]:selected.value}:{})}}));
watch(()=>props.defaults,defaults=>{if(!selected.value)selected.value=Object.keys(defaults||{})[0]||''});
function choose(name){selected.value=name;const id=Object.keys(props.modelValue.bindings).find(id=>props.modelValue.bindings[id]===name);if(id)category.value=id}

const dimensions={resolution:'分辨率',picture:'画质 / HDR',special:'特效字幕',source:'片源',hq:'高码率',audio:'音轨',anime:'动画资源偏好'};
const template=computed(()=>props.modelValue.templates?.[selected.value]||props.defaults?.[selected.value]);
const update=value=>emit('update:modelValue',{...props.modelValue,...value});
function bind(){if(!category.value||!binding.value)return;update({bindings:{...props.modelValue.bindings,[category.value]:binding.value},classification_revision:props.revision||props.modelValue.classification_revision});selected.value=binding.value}
function remove(categoryId){const bindings={...props.modelValue.bindings};delete bindings[categoryId];update({bindings})}
function edit(key,value){if(!template.value)return;update({templates:{...props.modelValue.templates,[selected.value]:{...template.value,[key]:value}}})}
function move(index,delta){const list=[...template.value.dimensions],next=index+delta;if(next<0||next>=list.length)return;[list[index],list[next]]=[list[next],list[index]];edit('dimensions',list)}
function rule(name,expr){const rules={...props.modelValue.overrides};if(expr===null)delete rules[name];else rules[name]=expr;update({overrides:rules})}
function addRule(){const name=ruleName.value.trim();if(!name||Object.hasOwn(props.modelValue.overrides,name))return;rule(name,{regex:['title','']});ruleName.value=''}
function reset(){const templates={...props.modelValue.templates};delete templates[selected.value];update({templates})}
function lock(key,value){const locks={...props.modelValue.locks};if(value===null||value==='')delete locks[key];else locks[key]=value;update({locks})}
const lockChoices={resolution:[[1080,'1080p'],[2160,'2160p']],picture:[[0,'普通画质'],[1,'HDR'],[2,'Dolby Vision']],source:[['web','WEB'],['bluray','Blu-ray'],['remux','REMUX']],audio:[[0,'基础音轨'],[1,'Dolby Digital Plus'],[2,'沉浸式音轨'],[3,'无损音轨']],hq:[[false,'非 HQ'],[true,'HQ']]};
</script>
<template><section aria-label="分类质量策略" class="sb-policy-editor"><nav class="sb-policy-selector" aria-label="策略列表"><button v-for="name in Object.keys({...defaults,...modelValue.templates})" :key="name" :aria-current="selected===name?'page':undefined" @click="choose(name)"><strong>{{name}}</strong><span>{{Object.values(modelValue.bindings).filter(v=>v===name).length}} 个分类使用</span></button></nav><div class="sb-policy-edit-body"><div class="sb-policy-rules">
 <details class="sb-policy-scope"><summary><strong>使用范围</strong> {{namesUsing.length}} 个分类<span v-if="plansUsing.length"> · {{plansUsing.length}} 个方案</span></summary><p>{{namesUsing.join('、')||'尚未绑定分类'}}<span v-if="plansUsing.length"> · {{plansUsing.join('、')}}</span></p></details>
 <details class="sb-form-section"><summary>分类使用的策略</summary><div v-for="(name,categoryId) in modelValue.bindings" :key="categoryId" class="sb-binding-row"><strong>{{categories?.find(c=>c.id===categoryId)?.name||'已保存分类（名称暂不可用）'}}</strong><span>{{name}}</span><VBtn variant="text" :disabled="readonly" @click="remove(categoryId)">移除绑定</VBtn></div><div class="sb-grid"><VSelect v-model="category" label="MoviePilot 分类" :items="(categories||[]).map(c=>({...c,props:{disabled:!c.enabled}}))" item-title="name" item-value="id" :disabled="readonly" variant="outlined"/><VSelect v-model="binding" label="质量策略" :items="Object.keys({...defaults,...modelValue.templates})" :disabled="readonly" variant="outlined"/></div><VBtn variant="tonal" :disabled="readonly||!category||!binding" @click="bind">应用到此分类</VBtn></details>
  <template v-if="template"><div class="sb-heading"><h3>{{selected}}</h3><VBtn variant="text" :disabled="readonly||!modelValue.templates?.[selected]" @click="reset">恢复默认</VBtn></div><p class="sb-muted">调整规则后，可在旁边试算本次修改；保存后才影响实际处理。</p>
   <fieldset :disabled="readonly"><legend>允许的分辨率</legend><label v-for="r in [2160,1080]" :key="r" class="sb-inline"><input type="checkbox" :checked="template.resolutions.includes(r)" @change="edit('resolutions',$event.target.checked?[...template.resolutions,r]:template.resolutions.filter(v=>v!==r))">{{r}}p</label></fieldset>
   <div class="sb-grid"><label>发布组准入<select :value="template.group" :disabled="readonly" @change="edit('group',$event.target.value)"><option value="any">不限制发布组</option><option value="official">官方发布组规则</option><option value="anime">动画发布组规则</option><option value="hhweb">HHWEB 规则</option></select></label><label>片源准入<select :value="template.source" :disabled="readonly" @change="edit('source',$event.target.value)"><option value="any">不额外限制片源</option><option value="movie">影视片源规则</option><option value="web">仅 WEB</option></select></label></div>
   <h3>比较顺序</h3><p class="sb-muted">从上到下比较，第一个不同的维度决定优劣。不是加权总分。</p>
   <ol class="sb-dimension-list"><li v-for="(d,index) in template.dimensions" :key="d"><strong>{{index+1}}. {{dimensions[d]}}</strong><div class="sb-actions"><VBtn variant="text" :aria-label="'上移'+dimensions[d]" :disabled="readonly||index===0" @click="move(index,-1)">上移</VBtn><VBtn variant="text" :aria-label="'下移'+dimensions[d]" :disabled="readonly||index===template.dimensions.length-1" @click="move(index,1)">下移</VBtn><VBtn variant="text" :disabled="readonly||template.dimensions.length===1" @click="edit('dimensions',template.dimensions.filter(v=>v!==d))">移除</VBtn></div></li></ol>
   <div class="sb-actions"><VBtn v-for="d in Object.keys(dimensions).filter(d=>!template.dimensions.includes(d))" :key="d" variant="tonal" :disabled="readonly" @click="edit('dimensions',[...template.dimensions,d])">＋ {{dimensions[d]}}</VBtn></div>
  </template>
 <section class="sb-global-policy"><h3>所有策略的限制</h3><p class="sb-muted">以下条件影响所有已绑定分类和使用它们的方案。</p><h4>明确锁定条件</h4><p class="sb-muted">锁定条件优先于质量比较；选择“不锁定”会移除该条件。</p><div class="sb-grid"><label v-for="(choices,key) in lockChoices" :key="key">{{dimensions[key]}}<select :value="modelValue.locks[key]===undefined?'':String(modelValue.locks[key])" :disabled="readonly" @change="lock(key,$event.target.value===''?null:choices.find(v=>String(v[0])===$event.target.value)[0])"><option value="">不锁定</option><option v-for="[value,title] in choices" :key="String(value)" :value="String(value)">{{title}}</option></select></label><label v-for="[key,title] in [['group','发布组'],['platform','平台']]" :key="key">{{title}}<input :value="modelValue.locks[key]||''" :disabled="readonly" placeholder="不锁定" @input="lock(key,$event.target.value)"></label></div>
 <details class="sb-technical"><summary>季范围与自定义准入</summary><label>只接收指定季度<input type="number" min="0" max="999" placeholder="不锁定" :value="modelValue.locks.season??''" :disabled="readonly" @input="lock('season',$event.target.value===''?null:Number($event.target.value))"></label>
 <section class="sb-form-section"><h4>额外收录条件</h4><label class="sb-inline"><input type="checkbox" :checked="!!modelValue.admission" :disabled="readonly" @change="update({admission:$event.target.checked?{literal:true}:null})">启用额外收录条件</label><PredicateEditor v-if="modelValue.admission" :model-value="modelValue.admission" :readonly="readonly" :fields="catalog?.predicate_fields||[]" :rules="ruleNames" @update:model-value="update({admission:$event})"/></section>
 <section><h4>自定义匹配规则</h4><p>修改同名规则会覆盖它的默认条件，所有引用该规则的策略都会受影响。</p><details v-for="(expression,name) in modelValue.overrides" :key="name"><summary>{{name}}</summary><PredicateEditor :model-value="expression" :readonly="readonly" :fields="catalog?.predicate_fields||[]" :rules="ruleNames.filter(n=>n!==name)" @update:model-value="rule(name,$event)"/><VBtn variant="text" :disabled="readonly" @click="rule(name,null)">移除自定义条件</VBtn></details><div class="sb-actions"><label>规则名称<input v-model="ruleName" maxlength="80" :disabled="readonly" :list="'sb-rule-names-'+selected"></label><datalist :id="'sb-rule-names-'+selected"><option v-for="name in catalog?.predicate_rules||[]" :key="name" :value="name"/></datalist><VBtn variant="tonal" :disabled="readonly||!ruleName.trim()||Object.hasOwn(modelValue.overrides,ruleName.trim())" @click="addRule">添加规则</VBtn></div></section></details>
</section></div><div class="sb-policy-test-column"><PolicySummary v-if="client&&status&&category" :policy="trialPolicy" :category="category" :client="client" :status="status"/><PolicySimulation v-if="client&&status" :client="client" :status="status" :policy="trialPolicy" :category="category"/></div></div></section></template>
