<script setup>
import {ref} from 'vue';import {useRead} from './read.mjs';import {stateLabel,reasonText,dimensions} from './media.mjs';import {errorText} from './client.mjs';import {contract,clean} from './schema.mjs';import Record from './Record.vue';
const props=defineProps({client:Object,status:Object});const emit=defineEmits(['configure']);const offset=ref(0),candidateOffset=ref(0),category=ref(''),candidate=ref(''),current=ref(''),result=ref(null),simulating=ref(false),simError=ref('');let alive=true;
import {onBeforeUnmount} from 'vue';onBeforeUnmount(()=>{alive=false});
const {data,error,busy,refresh}=useRead(async signal=>{const [policies,categories,candidates]=await Promise.all([props.client.get('/policies',{params:{limit:20,offset:offset.value},signal}),props.client.get('/configuration/categories',{signal}),props.client.get('/candidates',{params:{limit:25,offset:candidateOffset.value},signal})]);return {policies,categories,candidates}});
const categoryName=id=>data.value?.categories.categories?.find(c=>c.id===id)?.name||id;
function reset(){result.value=null;simError.value=''}
async function simulate(){if(simulating.value||busy.value||error.value||!category.value||!candidate.value||props.status.error.value)return;simulating.value=true;reset();
 try{const selected=data.value.candidates.items.find(c=>c.candidate_key===candidate.value),baseline=data.value.candidates.items.find(c=>c.candidate_key===current.value);if(!selected)return;
 const body={config_revision:props.status.current.value.revision,runtime_generation:props.status.health.value.generation,category_id:category.value,candidate:clean(contract.schemas.PolicySample,selected.evidence),current:baseline?[{version_id:baseline.candidate_key,raw:clean(contract.schemas.PolicySample,baseline.evidence),active:true,reliable:true}]:[]};
 const r=await props.client.post('/policies/simulate',body);if(alive)result.value=r}
 catch(e){if(alive)simError.value=errorText(e)}finally{if(alive)simulating.value=false}}
defineExpose({load:refresh});
</script>
<template><section aria-label="质量策略"><header class="sb-heading"><div><p class="sb-eyebrow">选择更合适的版本</p><h2>质量策略</h2><p class="sb-muted">按分类决定准入和比较顺序，第一个不同的维度决定优劣。</p></div><VBtn color="primary" @click="emit('configure','policy')">编辑策略</VBtn></header>
 <p v-if="error" class="sb-error" role="alert">{{error}} 以下结果可能已过期。</p><p v-if="busy&&!data" role="status">正在读取策略…</p>
 <template v-if="data"><p v-if="!data.policies.items.length" class="sb-empty">尚未绑定分类策略。先为 MoviePilot 分类选择策略，再纳管作品。</p><div class="sb-policy-grid"><article v-for="p in data.policies.items" :key="p.category_id" class="sb-policy-card"><div class="sb-heading"><h3>{{categoryName(p.category_id)}}</h3><span class="sb-muted">{{p.binding}}</span></div><ol class="sb-priority-flow"><li v-for="d in p.dimensions" :key="d">{{dimensions[d]||d}}</li></ol><p class="sb-muted">{{p.policy_revision?'运行策略已构建':'运行策略尚未就绪'}}</p><details class="sb-technical"><summary>准入与锁定条件</summary><Record :value="{锁定:p.configuration.locks,准入:p.configuration.admission,自定义:p.configuration.overrides}"/></details></article></div>
 <div v-if="data.policies.total>20" class="sb-pagination"><VBtn :disabled="busy||!offset" @click="offset-=20;refresh()">上一页分类</VBtn><VBtn :disabled="busy||data.policies.next_offset===null" @click="offset=data.policies.next_offset;refresh()">下一页分类</VBtn></div>
 <section class="sb-setting-card"><h3>用真实候选预演</h3><p class="sb-muted">使用当前已保存的策略。不会下载资源，也不会把预演结果当作实际入库；“对照资源”只是本次比较样本。</p><div class="sb-grid"><label>分类<select v-model="category" :disabled="simulating" @change="reset"><option value="">选择分类</option><option v-for="p in data.policies.items" :key="p.category_id" :value="p.category_id">{{categoryName(p.category_id)}}</option></select></label><label>待比较资源<select v-model="candidate" :disabled="simulating" @change="reset"><option value="">选择已有候选</option><option v-for="c in data.candidates.items" :key="c.candidate_key" :value="c.candidate_key">{{c.title}}</option></select></label><label>对照资源<select v-model="current" :disabled="simulating" @change="reset"><option value="">无对照，仅检查准入</option><option v-for="c in data.candidates.items" :key="c.candidate_key" :value="c.candidate_key">{{c.title}}</option></select></label></div>
 <p v-if="!data.candidates.items.length" class="sb-muted">尚无真实候选。正常订阅搜索后会积累候选记录。</p><div class="sb-actions"><VBtn color="primary" :disabled="busy||simulating||!!error||!category||!candidate||!!status.error.value" @click="simulate">{{simulating?'正在比较…':'预演当前策略'}}</VBtn><VBtn :disabled="busy||simulating||!candidateOffset" variant="text" @click="candidateOffset-=25;candidate='';current='';reset();refresh()">上一页候选</VBtn><VBtn :disabled="busy||simulating||data.candidates.next_offset===null" variant="text" @click="candidateOffset=data.candidates.next_offset;candidate='';current='';reset();refresh()">下一页候选</VBtn></div><p v-if="simError" role="alert" class="sb-error">{{simError}}</p>
 <div v-if="result" class="sb-comparison"><h3>{{stateLabel(result.evidence?.evaluation?.status||result.status)}}</h3><p>{{reasonText(result.evidence?.evaluation?.reason)}}</p><Record :value="result.evidence?.evaluation?.decisions?.simulation||result.evidence?.comparisons||{}"/><details class="sb-technical"><summary>完整比较依据</summary><Record :value="result.evidence"/></details></div></section>
 </template></section></template>
