<script setup>
import {ref,computed,watch,onMounted,nextTick} from 'vue';
import PredicateEditor from './PredicateEditor.vue';
import ConditionTest from './ConditionTest.vue';
import {astToDraft,predicateSummary} from './predicate-editor.mjs';
import PolicySummary from './PolicySummary.vue';
import PolicySimulation from './PolicySimulation.vue';
import {usePanelPosition} from './panel.mjs';
const props=defineProps({modelValue:Object,saved:Object,categories:Array,defaults:Object,revision:Number,readonly:Boolean,focus:Object,plans:Array,client:Object,status:Object,catalog:Object,archiveBindings:Object});const emit=defineEmits(['update:modelValue','selection','validation']);
const copy=value=>value==null?value:JSON.parse(JSON.stringify(value));
const category=ref(props.focus?.category||Object.keys(props.modelValue.bindings)[0]||''),binding=ref(''),ruleName=ref(''),selected=ref(props.focus?.policy||props.modelValue.bindings[category.value]||Object.keys(props.defaults||{})[0]||''),view=ref(['rules','trial','scope','global'].includes(props.focus?.tab)?props.focus.tab:'rules'),selector=ref(null),position=usePanelPosition();
const admissionEnabled=ref(!!props.modelValue.admission),admissionDraft=ref(copy(props.modelValue.admission)),admissionErrors=ref([]),testExpression=ref(null),editingRule=ref(''),ruleErrors=ref({});let admissionCache=copy(props.modelValue.admission),pendingAdmission='';
const editorErrors=computed(()=>[...(admissionEnabled.value?admissionErrors.value:[]),...Object.values(ruleErrors.value).flat()]);
watch(editorErrors,value=>emit('validation',value.map(error=>error.message||String(error))),{immediate:true,deep:true});
watch(()=>props.modelValue.admission,value=>{const encoded=JSON.stringify(value);if(encoded===pendingAdmission){pendingAdmission='';return}admissionEnabled.value=!!value;admissionDraft.value=copy(value);admissionCache=copy(value);admissionErrors.value=[]},{deep:true});
watch([selected,category,view],()=>emit('selection',{policy:selected.value,category:category.value,tab:view.value,label:view.value==='global'?'全局限制':selected.value}),{immediate:true});
const categoriesUsing=computed(()=>[...new Set([...Object.entries(props.archiveBindings||{}),...Object.entries(props.modelValue.bindings)].filter(([,name])=>name===selected.value).map(([id])=>id))]);
const effectivePolicy=computed(()=>category.value?props.saved?.bindings?.[category.value]||'':'');
const draftPolicy=computed(()=>category.value?props.modelValue.bindings[category.value]||'':'');
const categoryName=computed(()=>props.categories?.find(c=>c.id===category.value)?.name||'分类名称暂不可用');
const policyNames=computed(()=>Object.keys({...props.defaults,...props.modelValue.templates}));
const namesUsing=computed(()=>categoriesUsing.value.map(id=>props.categories?.find(c=>c.id===id)?.name||'已保存分类（名称暂不可用）'));
const plansUsing=computed(()=>(props.plans||[]).filter(plan=>categoriesUsing.value.includes(plan.category_id)).map(plan=>plan.display_name||plan.id));
const ruleNames=computed(()=>[...new Set([...(props.catalog?.predicate_rules||[]),...Object.keys(props.modelValue.overrides)])]);
const trialPolicy=computed(()=>({...props.modelValue,bindings:{...props.modelValue.bindings,...(category.value&&selected.value?{[category.value]:selected.value}:{})}}));
watch(()=>props.defaults,defaults=>{if(!selected.value)selected.value=Object.keys(defaults||{})[0]||''});
async function revealSelected(){await nextTick();const list=selector.value,item=list?.querySelector?.('[aria-current="page"]');if(!item||!list.clientWidth)return;const left=item.offsetLeft,right=left+item.offsetWidth;if(left<list.scrollLeft)list.scrollLeft=left;else if(right>list.scrollLeft+list.clientWidth)list.scrollLeft=right-list.clientWidth}
watch(selected,revealSelected);onMounted(revealSelected);
function choose(name){selected.value=name;category.value=Object.keys(props.modelValue.bindings).find(id=>props.modelValue.bindings[id]===name)||'';if(view.value==='global')view.value='rules'}
function show(value){view.value=value;position.top()}
const dimensions={resolution:'分辨率',picture:'画质 / HDR',special:'特效字幕',source:'片源',hq:'高码率',audio:'音轨',anime:'动画资源偏好'};
const template=computed(()=>props.modelValue.templates?.[selected.value]||props.defaults?.[selected.value]);
const update=value=>emit('update:modelValue',{...props.modelValue,...value});
function writeAdmission(value){pendingAdmission=JSON.stringify(value);update({admission:value})}
function toggleAdmission(enabled){if(!enabled){if(props.modelValue.admission)admissionCache=copy(props.modelValue.admission);admissionEnabled.value=false;admissionErrors.value=[];writeAdmission(null);return}admissionEnabled.value=true;if(admissionCache){admissionDraft.value=copy(admissionCache);writeAdmission(copy(admissionCache))}else{admissionDraft.value={all:[]};admissionErrors.value=[{code:'EMPTY_GROUP',message:'请至少添加一条条件。'}]}}
function editAdmission(value){admissionDraft.value=copy(value);admissionCache=copy(value);testExpression.value=null;writeAdmission(value)}
function clearAdmission(){if(props.modelValue.admission)admissionCache=copy(props.modelValue.admission);admissionDraft.value={all:[]};admissionErrors.value=[{code:'EMPTY_GROUP',message:'请至少添加一条条件。'}];writeAdmission(null)}
function restoreAdmission(){if(!admissionCache)return;admissionEnabled.value=true;admissionDraft.value=copy(admissionCache);admissionErrors.value=[];writeAdmission(copy(admissionCache))}
function bind(){if(!category.value||!binding.value)return;update({bindings:{...props.modelValue.bindings,[category.value]:binding.value},classification_revision:props.revision||props.modelValue.classification_revision});selected.value=binding.value}
function remove(categoryId){const bindings={...props.modelValue.bindings};delete bindings[categoryId];update({bindings})}
function edit(key,value){if(!template.value)return;update({templates:{...props.modelValue.templates,[selected.value]:{...template.value,[key]:value}}})}
function move(index,delta){const list=[...template.value.dimensions],next=index+delta;if(next<0||next>=list.length)return;[list[index],list[next]]=[list[next],list[index]];edit('dimensions',list)}
function rule(name,expr){const rules={...props.modelValue.overrides};if(expr===null){delete rules[name];delete ruleErrors.value[name];if(editingRule.value===name)editingRule.value=''}else rules[name]=expr;update({overrides:rules})}
function addRule(){const name=ruleName.value.trim();if(!name||Object.hasOwn(props.modelValue.overrides,name))return;rule(name,{all:[]});editingRule.value=name;ruleName.value='';ruleErrors.value={...ruleErrors.value,[name]:[{code:'EMPTY_GROUP',message:'请至少添加一条条件。'}]}}
function summary(expression){try{return predicateSummary(astToDraft(expression))||'尚未添加条件'}catch{return '高级条件，原样保留'}}
function reset(){const templates={...props.modelValue.templates};delete templates[selected.value];update({templates})}
function lock(key,value){const locks={...props.modelValue.locks};if(value===null||value==='')delete locks[key];else locks[key]=value;update({locks})}
const lockChoices={resolution:[[1080,'1080p'],[2160,'2160p']],picture:[[0,'普通画质'],[1,'HDR'],[2,'Dolby Vision']],source:[['web','WEB'],['bluray','Blu-ray'],['remux','REMUX']],audio:[[0,'基础音轨'],[1,'Dolby Digital Plus'],[2,'沉浸式音轨'],[3,'无损音轨']],hq:[[false,'非 HQ'],[true,'HQ']]};
</script>

<template><section aria-label="分类质量策略" class="sb-policy-editor"><nav ref="selector" class="sb-policy-selector" aria-label="策略列表"><button class="sb-policy-global" :aria-current="view==='global'?'page':undefined" @click="show('global')"><strong>全局限制</strong><span>全部分类与方案共用</span></button><button v-for="name in policyNames" :key="name" :aria-current="view!=='global'&&selected===name?'page':undefined" @click="choose(name)"><strong>{{name}}</strong><span>{{Object.values(modelValue.bindings).filter(v=>v===name).length}} 个分类使用</span></button></nav><div class="sb-policy-edit-body"><nav v-if="view!=='global'" class="sb-settings-tabs" aria-label="策略功能"><button :aria-current="view==='rules'?'page':undefined" @click="show('rules')">规则</button><button :aria-current="view==='trial'?'page':undefined" @click="show('trial')">试算</button><button :aria-current="view==='scope'?'page':undefined" @click="show('scope')">使用范围</button></nav>
 <div v-if="view==='scope'" class="sb-policy-rules"><section class="sb-form-section"><h3>使用范围</h3><p>{{namesUsing.join('、')||'尚未绑定分类'}}<span v-if="plansUsing.length"> · {{plansUsing.join('、')}}</span></p></section><section class="sb-form-section"><h3>分类使用的策略</h3><div v-for="(name,categoryId) in modelValue.bindings" :key="categoryId" class="sb-binding-row"><strong>{{categories?.find(c=>c.id===categoryId)?.name||'已保存分类（名称暂不可用）'}}</strong><span>{{name}}</span><VBtn variant="text" :disabled="readonly" @click="remove(categoryId)">移除绑定</VBtn></div><div class="sb-grid"><VSelect v-model="category" label="MoviePilot 分类" :items="(categories||[]).map(c=>({...c,props:{disabled:!c.enabled}}))" item-title="name" item-value="id" :disabled="readonly" variant="outlined"/><VSelect v-model="binding" label="质量策略" :items="Object.keys({...defaults,...modelValue.templates})" :disabled="readonly" variant="outlined"/></div><VBtn variant="tonal" :disabled="readonly||!category||!binding" @click="bind">应用到此分类</VBtn></section></div>

 <div v-else-if="view==='rules'" class="sb-policy-rules"><template v-if="template"><div class="sb-heading"><h3>{{selected}}</h3><VBtn variant="text" :disabled="readonly||!modelValue.templates?.[selected]" @click="reset">恢复默认</VBtn></div><p class="sb-muted">修改在保存后生效；试算页使用当前草稿。</p><fieldset :disabled="readonly"><legend>允许的分辨率</legend><label v-for="r in [2160,1080]" :key="r" class="sb-inline"><input type="checkbox" :checked="template.resolutions.includes(r)" @change="edit('resolutions',$event.target.checked?[...template.resolutions,r]:template.resolutions.filter(v=>v!==r))">{{r}}p</label></fieldset><div class="sb-grid"><label>发布组准入<select :value="template.group" :disabled="readonly" @change="edit('group',$event.target.value)"><option value="any">不限制发布组</option><option value="official">官方发布组规则</option><option value="anime">动画发布组规则</option><option value="hhweb">HHWEB 规则</option></select></label><label>片源准入<select :value="template.source" :disabled="readonly" @change="edit('source',$event.target.value)"><option value="any">不额外限制片源</option><option value="movie">影视片源规则</option><option value="web">仅 WEB</option></select></label></div><h3>比较顺序</h3><p class="sb-muted">从上到下比较，第一个不同的维度决定优劣。不是加权总分。</p><ol class="sb-dimension-list"><li v-for="(d,index) in template.dimensions" :key="d"><strong>{{index+1}}. {{dimensions[d]}}</strong><div class="sb-actions"><VBtn variant="text" :aria-label="'上移'+dimensions[d]" :disabled="readonly||index===0" @click="move(index,-1)">上移</VBtn><VBtn variant="text" :aria-label="'下移'+dimensions[d]" :disabled="readonly||index===template.dimensions.length-1" @click="move(index,1)">下移</VBtn><VBtn variant="text" :disabled="readonly||template.dimensions.length===1" @click="edit('dimensions',template.dimensions.filter(v=>v!==d))">移除</VBtn></div></li></ol><div class="sb-actions"><VBtn v-for="d in Object.keys(dimensions).filter(d=>!template.dimensions.includes(d))" :key="d" variant="tonal" :disabled="readonly" @click="edit('dimensions',[...template.dimensions,d])">＋ {{dimensions[d]}}</VBtn></div></template></div>
  <section v-else-if="view==='global'" class="sb-global-policy"><h3>质量策略 / 全局限制</h3><p class="sb-muted">这里的限制由全部分类和下载方案共用，不属于左侧某一份策略。</p><h4>明确锁定条件</h4><div class="sb-grid"><label v-for="(choices,key) in lockChoices" :key="key">{{dimensions[key]}}<select :value="modelValue.locks[key]===undefined?'':String(modelValue.locks[key])" :disabled="readonly" @change="lock(key,$event.target.value===''?null:choices.find(v=>String(v[0])===$event.target.value)[0])"><option value="">不锁定</option><option v-for="[value,title] in choices" :key="String(value)" :value="String(value)">{{title}}</option></select></label><label v-for="[key,title] in [['group','发布组'],['platform','平台']]" :key="key">{{title}}<input :value="modelValue.locks[key]||''" :disabled="readonly" placeholder="不锁定" @input="lock(key,$event.target.value)"></label><label>只接收指定季度<input type="number" min="0" max="999" placeholder="不锁定" :value="modelValue.locks.season??''" :disabled="readonly" @input="lock('season',$event.target.value===''?null:Number($event.target.value))"></label></div>
   <section class="sb-form-section"><div class="sb-heading"><div><h4>额外收录条件</h4><p class="sb-muted">全局：所有候选共用此条件。通过后仍需满足分类策略及其他检查；不会立即下载。</p></div><label class="sb-inline"><input type="checkbox" :checked="admissionEnabled" :disabled="readonly" @change="toggleAdmission($event.target.checked)">启用额外收录条件</label></div><PredicateEditor v-if="admissionEnabled" testable :model-value="admissionDraft" :readonly="readonly" :fields="catalog?.predicate_fields||[]" :rules="ruleNames" @validity="admissionErrors=$event" @test="testExpression=$event.expression" @update:model-value="editAdmission"/><ConditionTest v-if="testExpression&&client&&status" :client="client" :status="status" :policy="modelValue" :expression="testExpression"/><div v-if="admissionEnabled" class="sb-actions"><VBtn variant="text" :disabled="readonly" @click="clearAdmission">清空条件</VBtn><VBtn v-if="!modelValue.admission&&admissionCache" variant="text" :disabled="readonly" @click="restoreAdmission">撤销清空</VBtn></div><p v-else-if="admissionCache" class="sb-muted">条件已停用；本次会话中重新启用会恢复原条件。</p></section>
   <section class="sb-form-section"><h4>共享匹配规则</h4><p class="sb-muted">规则可被额外条件或系统质量识别引用。修改同名规则会影响所有引用位置。</p><div v-if="!Object.keys(modelValue.overrides).length" class="sb-empty">尚未自定义共享规则。</div><div v-for="(expression,name) in modelValue.overrides" :key="name" class="sb-rule-list-row"><div><strong>{{name}}</strong><p>{{summary(expression)}}</p><small>{{(catalog?.predicate_rules||[]).includes(name)?'覆盖内置规则，存在系统引用':'共享规则，引用范围以实际配置为准'}}</small></div><div class="sb-actions"><VBtn variant="text" @click="editingRule=editingRule===name?'':name">{{editingRule===name?'收起编辑':'编辑规则'}}</VBtn><VBtn variant="text" :disabled="readonly" @click="rule(name,null)">移除</VBtn></div></div><section v-if="editingRule&&modelValue.overrides[editingRule]" class="sb-shared-rule-editor"><div class="sb-heading"><h5>编辑共享规则：{{editingRule}}</h5><VBtn variant="text" @click="editingRule=''">返回规则列表</VBtn></div><PredicateEditor :model-value="modelValue.overrides[editingRule]" :readonly="readonly" :fields="catalog?.predicate_fields||[]" :rules="ruleNames.filter(name=>name!==editingRule)" @validity="ruleErrors={...ruleErrors,[editingRule]:$event}" @update:model-value="rule(editingRule,$event)"/></section><div class="sb-actions"><label>规则名称<input v-model="ruleName" maxlength="80" :disabled="readonly" :list="'sb-rule-names-global'"></label><datalist id="sb-rule-names-global"><option v-for="name in catalog?.predicate_rules||[]" :key="name" :value="name"/></datalist><VBtn variant="tonal" :disabled="readonly||!ruleName.trim()||Object.hasOwn(modelValue.overrides,ruleName.trim())" @click="addRule">添加共享规则</VBtn></div></section></section>

 <div v-else class="sb-policy-test-column"><VSelect v-model="category" label="试算分类" :items="(categories||[]).filter(c=>c.enabled)" item-title="name" item-value="id" variant="outlined"/><p v-if="!category" class="sb-notice">请选择试算分类，避免把上一份策略的分类当成当前上下文。</p><p v-else-if="draftPolicy!==effectivePolicy" class="sb-notice">此分类当前生效的是“{{effectivePolicy||'未绑定策略'}}”；本次草稿将改为“{{draftPolicy||'未绑定策略'}}”。保存前，两者分别试算。</p><p v-else-if="effectivePolicy!==selected" class="sb-notice">此分类当前生效的是“{{effectivePolicy||'未绑定策略'}}”；下方可试算“{{selected}}”的本次修改，不能将它当成当前生效策略。</p><PolicySummary v-if="client&&status&&category" :policy="trialPolicy" :category="category" :client="client" :status="status"/><PolicySimulation v-if="client&&status" :client="client" :status="status" :policy="trialPolicy" :category="category" :category-name="categoryName" :policy-name="selected" :current-policy-name="effectivePolicy" :effective="!!category&&effectivePolicy===selected"/></div>
</div></section></template>
