<script setup>
import {computed} from 'vue';import Field from './Field.vue';
const props=defineProps({modelValue:Object,readonly:Boolean,rules:{type:Array,default:()=>[]},fields:{type:Array,default:()=>[]},depth:{type:Number,default:0}}),emit=defineEmits(['update:modelValue']);
const operators={all:'满足全部条件',any:'满足任一条件',not:'不满足以下条件',literal:'固定结果',registered:'使用已有规则',regex:'符合正则表达式',eq:'等于',ne:'不等于',gt:'大于',ge:'大于或等于',lt:'小于',le:'小于或等于',in:'属于以下值',intersects:'包含任一值'};
const labels={text:'标题与说明',title:'标题',description:'发布说明',subtitle_description:'字幕说明',labels:'资源标签',original_language:'原始语言',production_countries:'制作地区',origin_country:'出品地区',genre_ids:'类型编号',media_type:'媒体类型',size:'大小（字节）',seeders:'做种人数',downloadvolumefactor:'下载系数',publish_minutes:'发布时长（分钟）'};
const op=computed(()=>Object.keys(props.modelValue||{})[0]||'literal'),args=computed(()=>props.modelValue?.[op.value]);
const set=value=>emit('update:modelValue',value),value=next=>set({[op.value]:next});
function operator(next){set({[next]:['all','any'].includes(next)?[props.modelValue||{literal:true}]:next==='not'?(props.modelValue||{literal:true}):next==='literal'?true:next==='registered'?(props.rules[0]||''):['title',['in','intersects'].includes(next)?[]:next==='regex'?'':0]})}
function child(index,next){value(args.value.map((v,i)=>i===index?next:v))}
function scalar(event){const raw=event.target.value,previous=args.value[1];value([args.value[0],typeof previous==='number'?(raw===''?null:Number(raw)):raw])}
function type(next){value([args.value[0],next==='number'?0:next==='boolean'?false:next==='null'?null:''])}
</script>
<template><div class="sb-condition"><label class="sb-sr-only">条件关系</label><select aria-label="条件关系" :value="op" :disabled="readonly" @change="operator($event.target.value)"><option v-for="(title,key) in operators" :key="key" :value="key" :disabled="depth>=14&&['all','any','not'].includes(key)">{{title}}</option></select>
 <template v-if="['all','any'].includes(op)"><div v-for="(item,index) in args" :key="index" class="sb-condition-child"><PredicateEditor :model-value="item" :readonly="readonly" :rules="rules" :fields="fields" :depth="depth+1" @update:model-value="child(index,$event)"/><VBtn variant="text" :disabled="readonly||args.length===1" @click="value(args.filter((_,i)=>i!==index))">移除条件</VBtn></div><VBtn variant="text" :disabled="readonly||args.length>=512||depth>=14" @click="value([...args,{regex:['title','']}])">添加条件</VBtn></template>
 <PredicateEditor v-else-if="op==='not'" :model-value="args" :readonly="readonly" :rules="rules" :fields="fields" :depth="depth+1" @update:model-value="value"/>
 <select v-else-if="op==='literal'" aria-label="固定结果" :value="String(args)" :disabled="readonly" @change="value($event.target.value==='true')"><option value="true">符合</option><option value="false">不符合</option></select>
 <select v-else-if="op==='registered'" aria-label="使用的规则" :value="args" :disabled="readonly" @change="value($event.target.value)"><option v-for="name in rules" :key="name">{{name}}</option></select>
 <template v-else><select aria-label="比较内容" :value="args[0]" :disabled="readonly" @change="value([$event.target.value,args[1]])"><option v-for="field in fields" :key="field" :value="field">{{labels[field]||field}}</option></select>
  <template v-if="['in','intersects'].includes(op)"><div v-for="(item,index) in args[1]" :key="index" class="sb-condition-values"><Field v-if="item!==null&&typeof item==='object'" name="比较值（高级）" :model-value="item" :readonly="readonly" @update:model-value="value([args[0],args[1].map((v,i)=>i===index?$event:v)])"/><select v-else-if="typeof item==='boolean'" :value="String(item)" aria-label="比较值" :disabled="readonly" @change="value([args[0],args[1].map((v,i)=>i===index?$event.target.value==='true':v)])"><option value="true">是</option><option value="false">否</option></select><span v-else-if="item===null">空值</span><input v-else :type="typeof item==='number'?'number':'text'" :aria-label="'值 '+(index+1)" :value="item" :disabled="readonly" @input="value([args[0],args[1].map((v,i)=>i===index?(typeof v==='number'?Number($event.target.value):$event.target.value):v)])"><VBtn variant="text" :disabled="readonly" @click="value([args[0],args[1].filter((_,i)=>i!==index)])">移除值</VBtn></div><div class="sb-actions"><VBtn variant="text" :disabled="readonly||args[1].length>=256" @click="value([args[0],[...args[1],'']])">添加文字</VBtn><VBtn variant="text" :disabled="readonly||args[1].length>=256" @click="value([args[0],[...args[1],0]])">添加数值</VBtn></div></template>
  <template v-else><select v-if="op!=='regex'" aria-label="值的类型" :value="args[1]===null?'null':typeof args[1]" :disabled="readonly" @change="type($event.target.value)"><option value="string">文字</option><option value="number">数值</option><option value="boolean">是或否</option><option value="null">空值</option><option v-if="args[1]!==null&&typeof args[1]==='object'" value="object">复杂值（高级）</option></select><select v-if="typeof args[1]==='boolean'" aria-label="比较值" :value="String(args[1])" :disabled="readonly" @change="value([args[0],$event.target.value==='true'])"><option value="true">是</option><option value="false">否</option></select><Field v-else-if="args[1]!==null&&typeof args[1]==='object'" name="比较值（高级）" :model-value="args[1]" :readonly="readonly" @update:model-value="value([args[0],$event])"/><input v-else-if="args[1]!==null" :type="typeof args[1]==='number'?'number':'text'" :aria-label="op==='regex'?'正则表达式':'比较值'" :value="args[1]" :disabled="readonly" @input="scalar"></template>
 </template>
</div></template>
