<script setup>
import {computed,nextTick,ref,toRaw,watch} from 'vue';
import ConditionNode from './ConditionNode.vue';
import {addCondition,addGroup,astToDraft,draftToAst,duplicateNode,predicateSummary,removeNode,restoreSnapshot,setConditionOperator,setGroupOperator,toggleNot,updateNode,validateDraft,wrapNode} from './predicate-editor.mjs';
const props=defineProps({modelValue:Object,readonly:Boolean,testable:Boolean,rules:{type:Array,default:()=>[]},fields:{type:Array,default:()=>[]}}),emit=defineEmits(['update:modelValue','validity','test']);
const tree=ref(astToDraft(props.modelValue)),history=ref([]),last=ref(JSON.stringify(props.modelValue)),editor=ref(null);
const errors=computed(()=>validateDraft(tree.value));
const unplacedErrors=computed(()=>errors.value.filter(error=>!['condition','registered'].includes(find(tree.value,error.id)?.kind)));
watch(()=>props.modelValue,value=>{const encoded=JSON.stringify(value);if(encoded===last.value)return;tree.value=astToDraft(value);history.value=[];last.value=encoded},{deep:true});
watch(errors,value=>emit('validity',value),{immediate:true,deep:true});
function ids(node,result=[]){result.push(node.id);if(node.kind==='group')node.children.forEach(child=>ids(child,result));if(node.kind==='not')ids(node.child,result);return result}
function focus(id){if(!id)return;nextTick(()=>editor.value?.querySelector(`[data-condition-id="${id}"] select, #condition-group-${id} select`)?.focus())}
function apply(next,focusId){history.value.push(structuredClone(toRaw(tree.value)));tree.value=next;const found=validateDraft(next);emit('validity',found);if(!found.length){const value=draftToAst(next);last.value=JSON.stringify(value);emit('update:modelValue',value)}focus(focusId)}
function find(node,id){if(node.id===id)return node;if(node.kind==='group')for(const child of node.children){const result=find(child,id);if(result)return result}if(node.kind==='not')return find(node.child,id)}
function action(event){let next=tree.value,focusId='';const before=ids(next,[]);if(event.type==='relation')next=setGroupOperator(next,event.id,event.value);else if(event.type==='operator')next=setConditionOperator(next,event.id,event.value);else if(event.type==='patch')next=updateNode(next,event.id,event.value);else if(event.type==='add'||event.type==='add-group'){next=event.type==='add'?addCondition(next,event.id):addGroup(next,event.id);focusId=ids(next,[]).find(id=>!before.includes(id))}else if(event.type==='duplicate'){next=duplicateNode(next,event.id);focusId=ids(next,[]).find(id=>!before.includes(id))}else if(event.type==='wrap'){next=wrapNode(next,event.id);focusId=event.id}else if(event.type==='remove'){const index=before.indexOf(event.id);next=removeNode(next,event.id);const after=ids(next,[]);focusId=after[Math.min(index,after.length-1)]}else if(event.type==='collapse'){tree.value=updateNode(next,event.id,{collapsed:!find(next,event.id)?.collapsed});return}else if(event.type==='negate')next=toggleNot(next,event.id);apply(next,focusId)}
function undo(){if(!history.value.length)return;const before=ids(tree.value,[]);tree.value=restoreSnapshot(tree.value,history.value.pop());const found=validateDraft(tree.value);emit('validity',found);if(!found.length){const value=draftToAst(tree.value);last.value=JSON.stringify(value);emit('update:modelValue',value)}focus(ids(tree.value,[]).find(id=>!before.includes(id)))}

</script>

<template><section ref="editor" class="sb-predicate-editor" aria-label="条件编辑器"><ConditionNode :node="tree" root :readonly="readonly" :rules="rules" :fields="fields" :errors="errors" @action="action"/><section class="sb-condition-summary" aria-label="规则摘要"><h5>规则摘要</h5><p>{{predicateSummary(tree)}}</p></section><div class="sb-actions"><VBtn variant="text" :disabled="readonly||!history.length" @click="undo">撤销上一步</VBtn><VBtn v-if="testable" variant="tonal" :disabled="!!errors.length" @click="emit('test',{expression:draftToAst(tree)})">测试这组条件</VBtn></div><ul v-if="unplacedErrors.length" class="sb-error" role="alert"><li v-for="error in unplacedErrors" :key="error.id+error.code">{{error.message}}</li></ul></section></template>
