<script setup>
import {computed,ref,onMounted,onBeforeUnmount} from 'vue';
import Field from './Field.vue';import Record from './Record.vue';
import Detail from './Detail.vue';
import {parameters,initial,resolve} from './schema.mjs';import {label} from './labels.mjs';
import {createReadGate,errorText,pathFor} from './client.mjs';import {links} from './catalog.mjs';
const props=defineProps({resource:Array,client:Object,status:Object});const emit=defineEmits(['open','select','action']);
const route=props.resource[1],values={...props.resource[2]},query=ref({}),data=ref(null),busy=ref(false),error=ref('');const gate=createReadGate();
const queryParams=parameters(route).filter(p=>p.in==='query'&&!['offset','limit'].includes(p.name));
const pageable=parameters(route).some(p=>p.name==='limit');const offset=ref(0),limit=ref(25);
const pathParams=parameters(route).filter(p=>p.in==='path');const pathValues=ref(Object.fromEntries(pathParams.map(p=>[p.name,values[p.name]??initial(p.schema)])));
for(const p of queryParams)if(values[p.name]!==undefined)query.value[p.name]=values[p.name];else if(p.schema.default!==undefined)query.value[p.name]=p.schema.default;
const rows=computed(()=>data.value?.items||data.value?.rows||null);
const columns=computed(()=>{const candidates=['id','target_key','candidate_key','category_id','source_id','title','media_type','media_id','season','state','status','generation','revision','binding','reason','due','updated_at'];return candidates.filter(k=>rows.value?.some(r=>r[k]!==undefined)).slice(0,8)});
const nested=computed(()=>Object.entries(data.value||{}).filter(([_,v])=>v&&typeof v==='object'&&Array.isArray(v.items)));
const header=computed(()=>Object.fromEntries(Object.entries(data.value||{}).filter(([_,v])=>!v||typeof v!=='object'||!Array.isArray(v.items))));
async function load(reset=false){if(reset)offset.value=0;const read=gate.begin();const expected=props.status?{revision:props.status.current.value?.revision,generation:props.status.health.value?.generation}:null;busy.value=true;error.value='';
 try{const params={...Object.fromEntries(Object.entries(query.value).filter(([_,v])=>v!==null&&v!==''))};if(pageable){params.limit=limit.value;params.offset=offset.value;}const r=await props.client.get(pathFor(route,pathValues.value),{params,signal:read.signal});if(read.current()){if(expected&&(expected.revision!==props.status.current.value?.revision||expected.generation!==props.status.health.value?.generation||r.snapshot&&(r.snapshot.config_revision!==expected.revision||r.snapshot.runtime_generation!==expected.generation)))throw Error('STALE_READ_REFRESH_REQUIRED');data.value=r;}}catch(e){if(read.current()){data.value=null;error.value=errorText(e)}}finally{if(read.current())busy.value=false}}
function open(link){emit('select',context(null));emit('open',[link.title,link.route,link.values]);}
function context(row){let base={...values,...pathValues.value};const task=data.value?.task;if(task)base={...base,task_id:task.id,generation:task.generation};if(data.value?.bundle)base={...base,bundle_id:data.value.bundle.id,revision:data.value.bundle.revision,expected_state:data.value.bundle.state,plan_id:data.value.bundle.plan_id};if(data.value?.units?.items)base.target_keys=data.value.units.items.map(u=>u.target_key);if(data.value?.opportunities?.items?.[0])base.opportunity_id=data.value.opportunities.items[0].id;if(data.value?.effective)base={...base,...data.value.effective};if(row){base={...base,...row,...row.data};if(row.target_key)base.target_keys=[row.target_key];if(route==='/tasks/{task_id}/plans'||route==='/candidate-decisions/{decision_id}/plans'||route==='/tasks/{task_id}'&&row.data?.authorization){base.plan_id=row.id;base.decision_digest=row.data?.snapshot?.decision_digest;}if(route==='/archive/targets/{target_key}')base.version_ids=[row.id];if(route==='/health/records/{section}'&&pathValues.value.section==='archive_scans')base.scan_id=row.id;if(route==='/archive/scans/{scan_id}/items')base.item_id=row.id;if(route==='/tasks')base.task_id=row.id;if(route==='/delivery/bundles'){base.bundle_id=row.id;base.expected_state=row.state}if(route==='/exclusions')base.exclusion_id=row.id;if(route==='/discovery/records')base.record_ids=[row.id];if(route==='/discovery/sources'){base.source_id=row.source_id;base.source_ids=[row.source_id]}if(route==='/parse/samples'){base.sample_key=row.id;base.sample_keys=[row.id]}}return base}
defineExpose({load});onMounted(()=>load());onBeforeUnmount(()=>gate.close());
</script>
<template><section :aria-label="resource[0]"><h3>{{resource[0]}}</h3>
 <form class="sb-grid" @submit.prevent="load(true)"><Field v-for="p in pathParams" :key="p.name" :name="p.name" :schema="p.schema" v-model="pathValues[p.name]"/><Field v-for="p in queryParams" :key="p.name" :name="p.name" :schema="{...p.schema,anyOf:p.schema.anyOf||[p.schema,{type:'null'}]}" :model-value="query[p.name]??null" @update:model-value="query[p.name]=$event"/><button type="submit" :disabled="busy">筛选 / 刷新</button></form>
 <p v-if="busy" role="status">正在读取…</p><p v-else-if="error" class="sb-error" role="alert">{{error}}</p>
 <template v-else-if="data"><Detail :data="data"/><p v-if="data.snapshot" class="sb-muted">配置 {{data.snapshot.config_revision}} / 运行代次 {{data.snapshot.runtime_generation}} / 水位 {{data.snapshot.high_watermark}}。翻页是新的观察快照。</p>
 <template v-if="rows"><p v-if="!rows.length">当前筛选下没有记录。</p><div v-else class="sb-table-scroll"><table><caption>{{resource[0]}} · {{data.total??'当前页'}} 条</caption><thead><tr><th v-for="key in columns" :key="key" scope="col">{{label(key)}}</th><th scope="col">依据与操作范围</th></tr></thead><tbody><tr v-for="(row,index) in rows" :key="row.id||row.target_key||row.candidate_key||index"><td v-for="key in columns" :key="key"><Record :value="row[key]??null"/></td><td><button @click="emit('select',context(row))">选为操作对象</button><details><summary>展开当前依据</summary><Record :value="row"/></details><div class="sb-actions"><button v-for="link in links(route,row,pathValues)" :key="link.title" @click="emit('select',context(row));emit('open',[link.title,link.route,link.values])">{{link.title}}</button></div></td></tr></tbody></table></div></template>
 <template v-else><section v-if="route==='/diagnostics'&&data.services?.local_rules"><h3>本地扫描规则 · 当前运行 revision</h3><p v-if="!data.services.local_rules.length">当前没有运行规则。</p><div v-for="rule in data.services.local_rules" :key="rule.id" class="sb-actions"><span>{{rule.id}} · {{rule.revision}} · {{rule.enabled?'启用':'停用'}}</span><button @click="emit('action',['本地规则对账','/health/reconcile'],{component:'local',object_id:rule.id,revision:rule.revision})">对账此规则</button></div></section><button @click="emit('select',context(null))">选用此明细的当前对象与代次</button><Record :value="header"/><button v-if="route==='/tasks/{task_id}/release-preview'" @click="emit('action',['解除纳管并恢复原生控制','/tasks/{task_id}/release'],{task_id:data.task_id,revision:data.revision})">确认此解除纳管预览</button>
 <section v-for="[key,page] in nested" :key="key"><h3>{{label(key)}} · {{page.total}} 条</h3><p v-if="page.truncated" class="sb-muted">此处仅显示当前页；使用独立明细翻页查看完整范围，不能把当前页当作全部授权范围。</p><details v-for="(row,index) in page.items" :key="row.id||row.target_key||index"><summary>{{row.title||row.id||row.target_key||index+1}}</summary><Record :value="row"/><button @click="emit('select',context(row))">选为操作对象</button><div class="sb-actions"><button v-for="link in links(route,row,pathValues)" :key="link.title" @click="open(link)">{{link.title}}</button></div></details></section></template>
 <div v-if="pageable" class="sb-actions"><button :disabled="busy||offset===0" @click="offset=Math.max(0,offset-limit);load()">上一页</button><span>偏移 {{offset}}</span><button :disabled="busy||(rows?data.next_offset===null||(!data.next_offset&&rows.length<limit):!nested.some(([_,p])=>p.next_offset!==null))" @click="offset=data.next_offset??offset+limit;load()">下一页</button></div>
 </template></section></template>
