<script setup>
import Quantity from './Quantity.vue';
const props=defineProps({modelValue:Object,readonly:Boolean,section:{type:String,default:'all'}});
const emit=defineEmits(['update:modelValue']);
const set=(key,value)=>emit('update:modelValue',{...props.modelValue,[key]:value});
</script>

<template><section aria-label="搜索与调度设置">
 <section v-if="['all','observation'].includes(section)" class="sb-form-section"><label class="sb-toggle-row"><span><strong>候选观察期</strong><small>首次发现符合条件的资源后，暂缓下载并收集后续候选。达到设定时限后重新比较。</small></span><input type="checkbox" :checked="modelValue.observation_enabled" :disabled="readonly" @change="set('observation_enabled',$event.target.checked)"></label><div v-if="modelValue.observation_enabled" class="sb-grid"><Quantity v-for="[key,title,note] in [['base_seconds','初始观察时长','首次发现候选后至少观察多久。'],['quiet_seconds','候选稳定时长','出现更好候选后继续观察多久。'],['max_seconds','最长观察时长','必填且大于 0；初始观察时长不能超过此值。']]" :key="key" :label="title" :note="note" :model-value="modelValue[key]" :readonly="readonly" @update:model-value="set(key,$event)"/><label class="sb-check"><input type="checkbox" :checked="modelValue.goal_early_enabled" :disabled="readonly" @change="set('goal_early_enabled',$event.target.checked)">达到偏好后允许提前结束观察</label></div><p v-else class="sb-muted">不设置额外观察时间；候选仍需满足质量策略和执行权限。</p></section>

 <section v-if="['all','replacement'].includes(section)" class="sb-form-section"><h4>资源替换</h4><p role="status">{{modelValue.supersession_limit===0?'当前不允许替换在途资源。':'每轮最多替换 '+modelValue.supersession_limit+' 次。'}}</p><div class="sb-grid"><label>最大替换次数<input type="number" min="0" step="1" :value="modelValue.supersession_limit" :disabled="readonly" @input="set('supersession_limit',Number($event.target.value))"><small>0 表示禁止替换。</small></label><Quantity v-if="modelValue.supersession_limit>0" label="允许替换的时段" note="从本轮机会开始计算；必填且大于 0。" :model-value="modelValue.supersession_seconds" :readonly="readonly" @update:model-value="set('supersession_seconds',$event)"/></div><template v-if="modelValue.supersession_limit>0"><label class="sb-toggle-row"><span><strong>等待秒传或暂存时允许替换</strong><small>只在尚未发布且服务端确认可取代时生效。</small></span><input type="checkbox" :checked="modelValue.waiting_transfer_preemption" :disabled="readonly" @change="set('waiting_transfer_preemption',$event.target.checked)"></label><label class="sb-toggle-row"><span><strong>普通下载中允许替换</strong><small>需要新鲜进度，并满足下方成本限制。</small></span><input type="checkbox" :checked="modelValue.normal_download_preemption" :disabled="readonly" @change="set('normal_download_preemption',$event.target.checked)"></label><div v-if="modelValue.normal_download_preemption" class="sb-grid"><Quantity label="已下载量最多" kind="bytes" note="0 表示只允许尚未下载数据时替换。" :model-value="modelValue.max_downloaded_bytes" :readonly="readonly" @update:model-value="set('max_downloaded_bytes',$event)"/><Quantity label="预计剩余时间至少" :model-value="modelValue.min_remaining_seconds" :readonly="readonly" @update:model-value="set('min_remaining_seconds',$event)"/></div></template></section>

 <section v-if="['all','cooldown'].includes(section)" class="sb-form-section"><label class="sb-toggle-row"><span><strong>升级冷却</strong><small>确认入库后，暂缓下一轮质量升级；补缺不受此限制。</small></span><input type="checkbox" :checked="modelValue.cooldown_enabled" :disabled="readonly" @change="set('cooldown_enabled',$event.target.checked)"></label><Quantity v-if="modelValue.cooldown_enabled" label="升级冷却时间" note="启用后必填；0 表示不等待。" :model-value="modelValue.cooldown_seconds" :readonly="readonly" @update:model-value="set('cooldown_seconds',$event)"/><p v-else class="sb-muted">没有额外的入库后升级冷却。</p></section>

 <section v-if="['all','failure'].includes(section)" class="sb-form-section"><h4>失败恢复</h4><label>最大恢复次数<input type="number" min="0" step="1" :value="modelValue.failure_limit" :disabled="readonly" @input="set('failure_limit',Number($event.target.value))"><small>0 表示不自动开始失败恢复。只统计已经确认失败的处理；未知结果先核对。</small></label></section>
</section></template>
