<script setup>
import Quantity from './Quantity.vue';
const props=defineProps({modelValue:Object,readonly:Boolean});const emit=defineEmits(['update:modelValue']);
const set=(key,value)=>emit('update:modelValue',{...props.modelValue,[key]:value});
</script>
<template><section aria-label="调度设置">
 <section class="sb-form-section"><label class="sb-toggle-row"><span><strong>下载前等一等</strong><small>等待更好资源出现；最长等待到期后，重新按实际候选和权限判定。</small></span><input type="checkbox" :checked="modelValue.observation_enabled" :disabled="readonly" @change="set('observation_enabled',$event.target.checked)"></label>
 <div v-if="modelValue.observation_enabled" class="sb-grid"><Quantity v-for="[key,title,note] in [['base_seconds','基础等待','首次发现候选后至少观察多久。'],['quiet_seconds','稳定等待','出现更好候选后继续等待多久。'],['max_seconds','最长等待','必填且大于 0；基础等待不能超过此值。']]" :key="key" :label="title" :note="note" :model-value="modelValue[key]" :readonly="readonly" @update:model-value="set(key,$event)"/><label class="sb-check"><input type="checkbox" :checked="modelValue.goal_early_enabled" :disabled="readonly" @change="set('goal_early_enabled',$event.target.checked)">达标后允许提前结束观察</label></div><p v-else class="sb-muted">不等待观察窗口，符合其他条件后再决定是否执行。</p></section>
 <section class="sb-form-section"><h4>在途版本替换</h4><p role="status">{{modelValue.supersession_limit===0?'当前不允许质量替换：次数预算为 0。':'每轮最多替换 '+modelValue.supersession_limit+' 次；仅在预算时段和成本允许时处理。'}}</p>
 <div class="sb-grid"><label>每轮替换次数<input type="number" min="0" step="1" :value="modelValue.supersession_limit" :disabled="readonly" @input="set('supersession_limit',Number($event.target.value))"><small>0 表示禁止替换，不是不限制。</small></label><Quantity v-if="modelValue.supersession_limit>0" label="允许替换的时段" note="从本轮机会开始计算；必填且大于 0。" :model-value="modelValue.supersession_seconds" :readonly="readonly" @update:model-value="set('supersession_seconds',$event)"/></div>
 <template v-if="modelValue.supersession_limit>0"><label class="sb-toggle-row"><span><strong>等待秒传或暂存时，允许换更好版本</strong><small>只在尚未发布且后台确认可以取代时生效；秒传重试仍使用独立时钟。</small></span><input type="checkbox" :checked="modelValue.waiting_transfer_preemption" :disabled="readonly" @change="set('waiting_transfer_preemption',$event.target.checked)"></label>
 <label class="sb-toggle-row"><span><strong>普通下载中，允许换更好版本</strong><small>默认关闭。需要新鲜的进度信息，并同时满足下方两项成本限制。</small></span><input type="checkbox" :checked="modelValue.normal_download_preemption" :disabled="readonly" @change="set('normal_download_preemption',$event.target.checked)"></label><div v-if="modelValue.normal_download_preemption" class="sb-grid"><Quantity label="已下载量最多" kind="bytes" note="0 表示只允许尚未下载数据时替换。" :model-value="modelValue.max_downloaded_bytes" :readonly="readonly" @update:model-value="set('max_downloaded_bytes',$event)"/><Quantity label="预计剩余时间至少" :model-value="modelValue.min_remaining_seconds" :readonly="readonly" @update:model-value="set('min_remaining_seconds',$event)"/></div></template>
 <details class="sb-technical"><summary>确认失败后的恢复预算</summary><label>每轮失败恢复次数<input type="number" min="0" step="1" :value="modelValue.failure_limit" :disabled="readonly" @input="set('failure_limit',Number($event.target.value))"></label><p>0 表示不自动开始失败恢复。仅计已确认失败；未知结果先核对，不能直接重试发布。</p></details></section>
 <section class="sb-form-section"><label class="sb-toggle-row"><span><strong>入库后暂缓升级</strong><small>成功入库后，暂缓下一轮质量升级；补缺不受升级冷却限制。</small></span><input type="checkbox" :checked="modelValue.cooldown_enabled" :disabled="readonly" @change="set('cooldown_enabled',$event.target.checked)"></label><Quantity v-if="modelValue.cooldown_enabled" label="升级冷却时间" note="启用后必填；0 表示不等待。" :model-value="modelValue.cooldown_seconds" :readonly="readonly" @update:model-value="set('cooldown_seconds',$event)"/><p v-else class="sb-muted">没有额外的入库后升级冷却。</p></section>
</section></template>
