<script setup>
import {ref} from 'vue';import Field from './Field.vue';import {id} from './client.mjs';import {initial,contract} from './schema.mjs';
const props=defineProps({modelValue:Object,routes:Array,templates:Array,readonly:Boolean});const emit=defineEmits(['update:modelValue']);
const route=ref(''),custom=ref(''),kind=ref('rsshub'),error=ref('');
function update(change){emit('update:modelValue',{...props.modelValue,...change})}
function change(index,key,value){update({sources:props.modelValue.sources.map((s,i)=>i===index?{...s,[key]:value}:s)})}
function add(){error.value='';try{const source={...Object.fromEntries(Object.entries(contract.schemas.SourceConfig.properties).map(([key,schema])=>[key,initial(schema)])),id:'source-'+id().slice(0,12),kind:kind.value};
 if(kind.value==='rsshub'){if(!route.value)throw Error('请选择一个榜单。');source.route_key=route.value;source.url=null;source.source_type_hint=props.routes.find(r=>r.key===route.value)?.media_type==='电影'?'Movie':'TV'}
 else{const parts=custom.value.trim().split('@@');if(parts.length>2||parts[1]&&!['TV','Movie'].includes(parts[1]))throw Error('类型后缀请使用 @@TV 或 @@Movie。');const raw=parts[0];if(!raw)throw Error('请输入榜单地址。');const url=raw.startsWith('/')?new URL(raw,props.modelValue.rsshub_base_url).href:new URL(raw).href;if(!/^https?:\/\//.test(url))throw Error('仅支持 HTTP 或 HTTPS 榜单地址。');source.url=url;source.route_key=null;source.source_type_hint=parts[1]||null}
 update({sources:[...props.modelValue.sources,source]});custom.value=''}catch(e){error.value=e.message==='Invalid URL'?'请填写完整 HTTP 地址，或先设置 RSSHub 地址再填相对路径。':e.message}}
function destination(index,bucket,value){const s=props.modelValue.sources[index],templates={...s.destination_templates},bindings={...s.destination_category_bindings};for(const k of Object.keys(bindings))if(bindings[k]===bucket)delete bindings[k];if(value){templates[bucket]=value;const t=props.templates.find(t=>t.id===value);if(t)bindings[t.category_id]=bucket}else delete templates[bucket];update({sources:props.modelValue.sources.map((r,i)=>i===index?{...r,destination_templates:templates,destination_category_bindings:bindings}:r)})}
const title=s=>props.routes?.find(r=>r.key===s.route_key)?.label||s.url||s.id;
const numeric=(e)=>e.target.value===''?null:Number(e.target.value);
</script>
<template><section aria-label="榜单来源设置"><header class="sb-heading"><div><h3>自部署 RSSHub</h3><p class="sb-muted">使用自己的实例，不依赖公开路由服务。</p></div><label><input type="checkbox" :checked="modelValue.enabled" :disabled="readonly" @change="update({enabled:$event.target.checked})">启用榜单发现</label></header><div class="sb-grid"><label>RSSHub 容器地址<input :value="modelValue.rsshub_base_url||''" :disabled="readonly" placeholder="http://192.168.50.6:1200" @input="update({rsshub_base_url:$event.target.value||null})"></label><label>允许访问的私网范围<textarea :value="modelValue.allowed_private_ranges.join('\n')" :disabled="readonly" placeholder="例如 192.168.50.6/32，每行一个" @input="update({allowed_private_ranges:$event.target.value.split(/\n/).map(v=>v.trim()).filter(Boolean)})"/></label><label>刷新计划（Cron）<input :value="modelValue.cron" :disabled="readonly" @input="update({cron:$event.target.value})"></label><label>豆瓣详情读取间隔（秒）<input type="number" min="1" max="60" :value="modelValue.douban_interval_seconds" :disabled="readonly" @input="update({douban_interval_seconds:numeric($event)})"></label></div><p class="sb-muted">同一媒体会复用缓存；间隔约束新增详情读取。使用私网地址时需填写允许访问的范围。</p>
 <section class="sb-setting-card"><h3>添加榜单</h3><div class="sb-grid"><label>来源方式<select v-model="kind" :disabled="readonly"><option value="rsshub">内置豆瓣榜单</option><option value="custom">自定义地址 / 路由</option></select></label><label v-if="kind==='rsshub'">选择榜单<select v-model="route" :disabled="readonly"><option value="" disabled>请选择</option><option v-for="r in routes||[]" :key="r.key" :value="r.key">{{r.label}} · {{r.media_type}}</option></select></label><label v-else>榜单地址<input v-model="custom" :disabled="readonly" placeholder="完整地址或 /douban/list/...@@TV"></label></div><p class="sb-muted">自定义地址支持 @@TV / @@Movie；相对路径会使用上方 RSSHub 地址。</p><VBtn variant="tonal" :disabled="readonly" @click="add">加入来源列表</VBtn><p v-if="error" role="alert" class="sb-error">{{error}}</p></section>
 <p v-if="!modelValue.sources.length" class="sb-empty">尚未添加榜单。选择来源后，再为该来源绑定下载方案。</p>
 <details v-for="(s,index) in modelValue.sources" :key="s.id" class="sb-setting-card"><summary><strong>{{title(s)}}</strong><span class="sb-muted"> · {{s.enabled?'已启用':'已停用'}}</span></summary><label class="sb-inline"><input type="checkbox" :checked="s.enabled" :disabled="readonly" @change="change(index,'enabled',$event.target.checked)">启用这个来源</label><div class="sb-grid"><label>媒体类型<select :value="s.source_type_hint||''" :disabled="readonly" @change="change(index,'source_type_hint',$event.target.value||null)"><option value="">按识别结果确定</option><option value="TV">电视剧</option><option value="Movie">电影</option></select></label><label>最低年份<input type="number" :value="s.minimum_release_year" :disabled="readonly" placeholder="继承全局" @input="change(index,'minimum_release_year',numeric($event))"></label><label>最低评分<input type="number" min="0" max="10" step="0.1" :value="s.minimum_rating" :disabled="readonly" placeholder="继承全局" @input="change(index,'minimum_rating',numeric($event))"></label><label v-for="[bucket,name] in [['movie','电影'],['tv','剧集'],['anime','动画']]" :key="bucket">{{name}}下载方案<select :value="s.destination_templates[bucket]||''" :disabled="readonly" @change="destination(index,bucket,$event.target.value)"><option value="">不绑定</option><option v-for="t in templates||[]" :key="t.id" :value="t.id">{{t.id}}</option></select></label></div><p class="sb-muted">方案关联其 MoviePilot 分类；没有对应分类方案的作品不会被随意放入其他目录。</p><details class="sb-technical"><summary>高级过滤与读取预算</summary><Field v-for="key in ['media_type_allowlist','season_scope','existing_media_action','request_budget','proxy','destination_category_bindings']" :key="key" :name="key" :schema="contract.schemas.SourceConfig.properties[key]" :model-value="s[key]" :readonly="readonly" @update:model-value="change(index,key,$event)"/></details><VBtn variant="text" color="error" :disabled="readonly" @click="update({sources:modelValue.sources.filter((_,i)=>i!==index)})">移除此来源</VBtn></details>
 <details class="sb-technical"><summary>全局过滤与请求预算</summary><Field v-for="key in ['request_budget','media_type_allowlist','minimum_release_year','minimum_rating','season_scope','existing_media_action']" :key="key" :name="key" :schema="contract.schemas.DiscoveryConfig.properties[key]" :model-value="modelValue[key]" :readonly="readonly" @update:model-value="update({[key]:$event})"/></details>
</section></template>
