<script setup>
import Quantity from './Quantity.vue';import {contract,initial} from './schema.mjs';
const props=defineProps({modelValue:Object,readonly:Boolean,inherit:Boolean}),emit=defineEmits(['update:modelValue']);
const set=(key,value)=>emit('update:modelValue',{...props.modelValue,[key]:value});
const budget=(key,value)=>set('request_budget',{...props.modelValue.request_budget,[key]:value});
</script>
<template><section><div class="sb-grid"><fieldset><legend>媒体类型</legend><label v-for="type in ['电影','电视剧']" :key="type" class="sb-inline"><input type="checkbox" :checked="modelValue.media_type_allowlist.includes(type)" :disabled="readonly" @change="set('media_type_allowlist',$event.target.checked?[...modelValue.media_type_allowlist,type]:modelValue.media_type_allowlist.filter(t=>t!==type))">{{type}}</label><small>{{inherit?'不勾选时继承全局允许的类型。':'不勾选时不限制媒体类型。'}}</small></fieldset>
 <label>季度范围<select :value="modelValue.season_scope||''" :disabled="readonly" @change="set('season_scope',$event.target.value||null)"><option v-if="inherit" value="">继承全局</option><option value="identified">仅识别到的季度</option><option value="all_known">所有已知季度</option></select></label>
 <label>媒体库已有作品时<select :value="modelValue.existing_media_action||''" :disabled="readonly" @change="set('existing_media_action',$event.target.value||null)"><option v-if="inherit" value="">继承全局</option><option value="record_only">只记录，不自动管理</option><option value="manage_authorized">按已授权范围管理</option></select></label>
 <template v-if="!inherit"><label>最低年份<input type="number" min="1870" max="2999" :value="modelValue.minimum_release_year??''" placeholder="不限制" :disabled="readonly" @input="set('minimum_release_year',$event.target.value===''?null:Number($event.target.value))"></label><label>最低评分<input type="number" min="0" max="10" step="0.1" :value="modelValue.minimum_rating??''" placeholder="不限制" :disabled="readonly" @input="set('minimum_rating',$event.target.value===''?null:Number($event.target.value))"></label></template></div>
 <label v-if="inherit" class="sb-inline"><input type="checkbox" :checked="modelValue.proxy" :disabled="readonly" @change="set('proxy',$event.target.checked)">使用宿主代理读取这个来源</label>
 <h4>读取限额</h4><label v-if="inherit" class="sb-inline"><input type="checkbox" :checked="!!modelValue.request_budget" :disabled="readonly" @change="set('request_budget',$event.target.checked?initial(contract.schemas.RequestBudget):null)">为此来源单独设置限额</label>
 <div v-if="modelValue.request_budget" class="sb-grid"><Quantity v-for="[key,title,max] in [['timeout','单次读取超时',60],['interval_min_seconds','请求间隔最短',86400],['interval_max_seconds','请求间隔最长',86400]]" :key="key" :label="title" :model-value="modelValue.request_budget[key]" :max="max" :readonly="readonly" @update:model-value="budget(key,$event)"/><Quantity kind="bytes" label="单次响应最大大小" :model-value="modelValue.request_budget.response_bytes" :min="1024" :max="2097152" :readonly="readonly" @update:model-value="budget('response_bytes',$event)"/><label v-for="[key,title,min,max] in [['items','每次最多读取条目',1,200],['requests_per_run','每轮最多请求次数',1,100],['retry_limit','最多重试次数',0,10]]" :key="key">{{title}}<input type="number" :min="min" :max="max" :value="modelValue.request_budget[key]" :disabled="readonly" @input="budget(key,$event.target.value===''?null:Number($event.target.value))"></label></div><p v-else class="sb-muted">使用全局读取限额。</p>
</section></template>
