<script setup>
import {ref,computed,onMounted,onBeforeUnmount} from 'vue';
import {usePanelPosition} from './panel.mjs';
import AdoptSubscription from './AdoptSubscription.vue';
import BackButton from './BackButton.vue';
import CandidateDecision from './CandidateDecision.vue';import VersionHistory from './VersionHistory.vue';
import UnitProgress from './UnitProgress.vue';import MediaCover from './MediaCover.vue';import ReconcileButton from './ReconcileButton.vue';
import {createReadGate,errorText,id} from './client.mjs';
import {stateLabel,dateText,unitLabel,qualitySummary,qualityExtra,reasonText,taskProgress,taskNext,taskStage} from './media.mjs';
const props=defineProps({api:Object,client:Object,status:Object,returnLabel:String});const emit=defineEmits(['changed','action','configure','return']);
const query=ref(''),filter=ref(''),type=ref(''),applied=ref({query:'',filter:'',type:''}),offset=ref(0),page=ref(null),selected=ref(null),detail=ref(null),unitOffset=ref(0),unitFilter=ref('');
const loading=ref(false),detailLoading=ref(false),error=ref(''),detailError=ref(''),detailErrors=ref({}),detailAuxLoading=ref({}),detailStale=ref({}),auxData=ref({}),adopting=ref(false),confirmation=ref(null),actionBusy=ref(false),attempted=ref(false),actionError=ref(''),notice=ref('');
const decisionOffset=ref(0),planOffset=ref(0),exclusionOffset=ref(0);
const replacement=ref(null),replacementPage=ref(null),replacementBusy=ref(false),replacementError=ref('');let replacementSequence=0;
const position=usePanelPosition(),detailTab=ref('versions');
const currentPlan=computed(()=>detail.value?.effective?.effective?.template);
function editContext(group){const plan=currentPlan.value;emit('configure',group,{id:group==='plans'?plan?.id:undefined,category:plan?.category_id,policy:props.status.current.value?.config.policy.bindings[plan?.category_id],returnLabel:selected.value.title,task_id:selected.value.id})}
const listGate=createReadGate(),detailGate=createReadGate(),auxNames=['observations','decisions','plans','exclusions'],auxGates=Object.fromEntries(auxNames.map(name=>[name,createReadGate()])),emptyPage=()=>({items:[],total:0,next_offset:null});let mounted=true,timer;
async function load(reset=false){if(reset)offset.value=0;const read=listGate.begin();loading.value=true;error.value='';const criteria=applied.value;
 try{const result=await props.client.get('/tasks',{params:{limit:25,offset:offset.value,query:criteria.query,...(['processing','attention'].includes(criteria.filter)?{activity:criteria.filter}:criteria.filter?{state:criteria.filter}:{}),...(criteria.type?{media_type:criteria.type}:{})},signal:read.signal});if(read.current())page.value=result}
 catch(e){if(read.current())error.value=errorText(e)}finally{if(read.current())loading.value=false}}
function apply(reset=true){applied.value={query:query.value,filter:filter.value,type:type.value};return load(reset)}
function auxRequest(name,task,signal){const options={signal};if(name==='observations')return props.client.get('/tasks/'+encodeURIComponent(task.id)+'/observations',{...options,params:{limit:25,offset:0}});if(name==='decisions')return props.client.get('/candidate-decisions',{...options,params:{task_id:task.id,limit:5,offset:decisionOffset.value,sort:'newest'}});if(name==='plans')return props.client.get('/tasks/'+encodeURIComponent(task.id)+'/plans',{...options,params:{limit:5,offset:planOffset.value,sort:'newest'}});return props.client.get('/exclusions',{...options,params:{task_id:task.id,active:true,limit:10,offset:exclusionOffset.value}})}
async function loadAux(name,task=selected.value){if(!task)return;const read=auxGates[name].begin();detailAuxLoading.value={...detailAuxLoading.value,[name]:true};detailErrors.value={...detailErrors.value,[name]:''};
 try{const result=await auxRequest(name,task,read.signal);if(read.current()&&selected.value?.id===task.id){auxData.value={...auxData.value,[name]:result};if(detail.value?.units)detail.value={...detail.value,[name]:result};detailStale.value={...detailStale.value,[name]:false}}}
 catch(e){if(read.current()&&selected.value?.id===task.id){detailErrors.value={...detailErrors.value,[name]:errorText(e)};detailStale.value={...detailStale.value,[name]:!!(detail.value?.[name]||auxData.value[name])};if(!auxData.value[name])auxData.value={...auxData.value,[name]:emptyPage()}}}
 finally{if(read.current()&&selected.value?.id===task.id)detailAuxLoading.value={...detailAuxLoading.value,[name]:false}}}
async function choose(task,reset=true,event){const changed=selected.value?.id!==task.id;if(reset){position.remember(event);detailTab.value='versions'}selected.value=task;if(reset){unitOffset.value=0;decisionOffset.value=0;planOffset.value=0;exclusionOffset.value=0;position.top()}if(changed){detail.value=null;auxData.value={};detailErrors.value={};detailAuxLoading.value={};detailStale.value={};for(const gate of Object.values(auxGates))gate.begin()}const read=detailGate.begin();detailLoading.value=true;detailError.value='';for(const name of auxNames)loadAux(name,task);
 try{const base=await props.client.get('/tasks/'+encodeURIComponent(task.id),{params:{limit:25,offset:unitOffset.value,...(unitFilter.value?{activity:unitFilter.value}:{})},signal:read.signal});if(!read.current())return;detail.value={...base,...Object.fromEntries(auxNames.map(name=>[name,auxData.value[name]||emptyPage()]))};selected.value=base.task}
 catch(e){if(read.current())detailError.value=errorText(e)}finally{if(read.current())detailLoading.value=false}}
function showDetailTab(key){detailTab.value=key;position.top()}
function filterUnits(value){unitFilter.value=value;unitOffset.value=0;choose(selected.value,false)}
const opportunity=computed(()=>detail.value?.opportunities?.items?.find(o=>o.state==='ACTIVE'));
function revoke(row){emit('action',['允许重新选择此资源','/exclusions/{exclusion_id}/revoke/preview'],{exclusion_id:row.id,_bound:true,_label:selected.value.title,_description:'撤销这条排除，资源重新参与后续比较；不会立即下载或替换在库文件。'})}
async function readReplacement(offset,sequence=replacementSequence){replacementError.value='';replacementBusy.value=true;try{const page=await props.client.get('/tasks/'+encodeURIComponent(selected.value.id)+'/replacement-candidates',{params:{target_key:replacement.value.target_key,exclude_candidate_key:replacement.value.processing?.candidate_key,limit:25,offset}});if(sequence===replacementSequence)replacementPage.value={...page,items:[...(offset?replacementPage.value?.items||[]:[]),...page.items]}}catch(e){if(sequence===replacementSequence)replacementError.value=errorText(e)}finally{if(sequence===replacementSequence)replacementBusy.value=false}}
function openReplacement(unit){const sequence=++replacementSequence;replacement.value=unit;replacementPage.value=null;return readReplacement(0,sequence)}
const replacementRows=computed(()=>{const seen=new Set();return (replacementPage.value?.items||[]).filter(row=>row.candidate_key!==replacement.value?.processing?.candidate_key&&!seen.has(row.candidate_key+'\n'+row.plan_digest)&&seen.add(row.candidate_key+'\n'+row.plan_digest))});
function autoChange(){const unit=replacement.value;replacement.value=null;emit('action',[selected.value.media_type==='电影'?'自动重新寻找影片资源':'自动重新寻找此集资源','/candidates/{candidate_key}/change-source/preview'],{candidate_key:unit.processing.candidate_key,task_id:selected.value.id,generation:selected.value.generation,target_keys:[unit.target_key],reason:'USER_REQUESTED_CHANGE',expires_at:null,_bound:true,_label:selected.value.title+' · '+unitLabel(unit),_description:'排除当前资源并让系统按现有策略重新选择。现有可播放版本与下载数据保留；这项排除持续到手动撤销。'})}
function selectCandidate(row){const unit=replacement.value;replacement.value=null;emit('action',['选择这个候选资源','/tasks/{task_id}/select-candidate/preview'],{task_id:selected.value.id,generation:selected.value.generation,opportunity_id:row.opportunity_id,decision_id:row.decision_id,plan_digest:row.plan_digest,target_keys:[unit.target_key],_bound:true,_label:selected.value.title+' · '+unitLabel(unit),_description:'使用这条已经比较通过的候选记录。确认页会列出实际覆盖集数和共享文件；执行时仍会重新校验策略、在库版本、文件范围和外部结果。'})}
function immediate(unit){emit('action',[selected.value.media_type==='电影'?'立即检查版本':'立即检查此集','/tasks/{task_id}/immediate'],{task_id:selected.value.id,generation:selected.value.generation,opportunity_id:opportunity.value.id,target_keys:[unit.target_key],_bound:true,_label:selected.value.title+' · '+unitLabel(unit),_description:'只越过此目标的等待时间；所有权、准入、交付与权限检查仍然生效。'})}
async function release(){const task={...selected.value},read=detailGate.begin();detailLoading.value=true;detailError.value='';try{const r=await props.client.get('/tasks/'+task.id+'/release-preview',{signal:read.signal});if(read.current())emit('action',['交还 MoviePilot 管理','/tasks/{task_id}/release'],{task_id:task.id,revision:r.revision,_bound:true,_label:task.title,_description:'保留文件与下载任务，将订阅控制交还 MoviePilot，恢复接管前记录的原生状态；不会恢复旧过滤条件。'})}catch(e){if(read.current())detailError.value=errorText(e)}finally{if(read.current())detailLoading.value=false}}
function back(){detailGate.begin();for(const gate of Object.values(auxGates))gate.begin();selected.value=null;detail.value=null;auxData.value={};detailLoading.value=false;detailError.value='';detailAuxLoading.value={};if(props.returnLabel)emit('return');else position.restore()}
function confirm(action){confirmation.value={action,task:{...selected.value},operation:'ui-'+id()};attempted.value=false;actionError.value=''}
async function execute(){if(actionBusy.value||attempted.value||!confirmation.value)return;const {action,task,operation}=confirmation.value;actionBusy.value=true;attempted.value=true;actionError.value='';
 try{if(action==='pause')await props.client.post('/tasks/'+task.id+'/state',{state:'PAUSED'});
  else await props.client.post('/tasks/'+task.id+'/resume',{generation:task.generation});
  if(mounted){confirmation.value=null;notice.value=action==='pause'?'已暂停追踪，现有文件和下载任务保留。':'已提交恢复请求，以下显示服务端当前状态。';emit('changed');await Promise.all([load(),choose(task,false)])}}
 catch(e){if(mounted)actionError.value=errorText(e)+' 请关闭确认框并刷新，核对当前状态。'}finally{if(mounted)actionBusy.value=false}}
async function adopted(task){adopting.value=false;notice.value='已提交接管请求，以下显示服务端当前状态。';emit('changed');await load(true);if(mounted)await choose(task)}
function poll(){if(document.visibilityState==='hidden'||adopting.value||confirmation.value||loading.value||detailLoading.value)return;load();if(selected.value)choose(selected.value,false)}
function visibility(){if(document.visibilityState==='hidden'){listGate.begin();detailGate.begin();for(const gate of Object.values(auxGates))gate.begin();loading.value=false;detailLoading.value=false;for(const key of Object.keys(detailAuxLoading))detailAuxLoading[key]=false}else poll()}
onMounted(()=>{load();timer=setInterval(poll,15000);document.addEventListener?.('visibilitychange',visibility)});
onBeforeUnmount(()=>{mounted=false;clearInterval(timer);listGate.close();detailGate.close();for(const gate of Object.values(auxGates))gate.close();document.removeEventListener?.('visibilitychange',visibility)});
async function refresh(){await load();if(selected.value)await choose(selected.value,false)}
function viewState(){return {query:query.value,filter:filter.value,type:type.value,applied:applied.value,offset:offset.value,task:selected.value?.id,unitOffset:unitOffset.value,unitFilter:unitFilter.value,tab:detailTab.value}}
async function restore(s){query.value=s.query||'';filter.value=s.filter||'';type.value=s.type||'';applied.value=s.applied||{query:query.value,filter:filter.value,type:type.value};offset.value=Number(s.offset)||0;unitOffset.value=Number(s.unitOffset)||0;unitFilter.value=['processing','attention'].includes(s.unitFilter)?s.unitFilter:'';detailTab.value=['versions','candidates','history'].includes(s.tab)?s.tab:'versions';await load();if(Number.isInteger(s.task))await choose({id:s.task},false)}
defineExpose({load:refresh,choose,viewState,restore});
</script>
<template><section class="sb-subscriptions" aria-label="订阅作品">
 <header v-if="!selected" class="sb-heading"><div><h2>订阅 <span v-if="page" class="sb-count">{{page.total}}</span></h2></div><div class="sb-actions"><VBtn variant="text" @click="emit('configure','plans')">下载与入库方案</VBtn><VBtn color="primary" @click="adopting=true">接管已有订阅</VBtn></div></header>
 <p v-if="notice" class="sb-notice" role="status">{{notice}}</p>
 <form v-show="!selected" class="sb-list-toolbar" @submit.prevent="apply(true)">
  <div class="sb-quick-filters" role="group" aria-label="订阅状态筛选"><button v-for="[key,title] in [['','全部'],['processing','处理中'],['attention','需核对'],['PAUSED','已暂停']]" :key="key" type="button" :aria-pressed="filter===key" @click="filter=key;apply(true)">{{title}}</button></div>
  <div class="sb-list-search"><label><span class="sb-sr-only">查找订阅</span><input v-model="query" type="search" maxlength="300" placeholder="输入作品名称"></label><VBtn type="submit" variant="text" :disabled="loading">{{loading?'读取中…':'查找'}}</VBtn></div>
  <details class="sb-filter-options"><summary>更多筛选<span v-if="type||!['','processing','attention','PAUSED'].includes(filter)" class="sb-filter-applied">已应用</span></summary><div class="sb-filter-fields"><label>状态<select v-model="filter" @change="apply(true)"><option value="">全部状态</option><option value="processing">处理中</option><option value="attention">需核对</option><option value="ACTIVE">追踪中</option><option value="PAUSED">已暂停</option><option value="PASSIVE">仅观察</option><option value="PENDING">等待接管</option><option value="STOPPED">已停止</option><option value="RELEASED_NATIVE">已交还 MP</option></select></label><label>类型<select v-model="type" @change="apply(true)"><option value="">全部类型</option><option>电影</option><option>电视剧</option></select></label></div></details>
 </form>
 <p v-if="error" role="alert" class="sb-error">{{error}}<span v-if="page"> 以下保留上次读取结果，可能已过期。</span></p>
 <div class="sb-workspace"><section v-show="!selected" class="sb-subscription-list" aria-label="作品列表">
  <p v-if="loading&&!page" class="sb-empty" role="status">正在读取订阅…</p>
  <div v-else-if="page&&!page.items.length&&!error" class="sb-empty"><h3>{{query||filter||type?'没有符合筛选条件的订阅':'还没有接管的作品'}}</h3><p>在 MoviePilot 原生界面添加订阅，或在发现页面配置豆瓣榜单。</p><VBtn variant="tonal" @click="adopting=true">接管已有订阅</VBtn></div>
  <div v-if="page?.items.length" class="sb-media-columns" aria-hidden="true"><span>作品</span><span>在库情况</span><span>当前进度</span></div>
  <button v-for="task in page?.items||[]" :key="task.id" class="sb-work-row" @click="choose(task,true,$event)"><MediaCover :src="task.poster" :type="task.media_type"/><span class="sb-work-identity"><strong>{{task.title}}</strong><span>{{[task.year,task.media_type,task.season!=null?'第 '+task.season+' 季':''].filter(Boolean).join(' · ')}}</span></span><span class="sb-work-collection"><strong>{{taskProgress(task)}}</strong><small v-if="task.progress?.resolutions?.length">{{task.progress.resolutions.map(r=>r===2160?'4K':r+'p').join(' / ')}}</small></span><span class="sb-work-activity"><template v-if="['ACTIVE','PASSIVE'].includes(task.state)&&task.progress?.highlights?.length"><span v-for="entry in task.progress.highlights" :key="entry.target_key" class="sb-task-highlight"><span>{{unitLabel(entry)}}</span><strong class="sb-stage-label" :data-state="entry.phase">{{stateLabel(entry.phase)}}</strong></span></template><strong v-else>{{taskStage(task)}}</strong><small v-if="task.progress?.stage_sample_count<task.progress?.processing">已读取 {{task.progress.stage_sample_count}} / {{task.progress.processing}} 集的处理状态</small></span><span class="sb-row-action">查看</span></button>

  <div v-if="page?.total>25" class="sb-pagination"><VBtn :disabled="loading||offset===0" @click="offset=Math.max(0,offset-25);load()">上一页</VBtn><span>共 {{page.total}} 部 · 第 {{Math.floor(offset/25)+1}} 页</span><VBtn :disabled="loading||page.next_offset===null" @click="offset=page.next_offset;load()">下一页</VBtn></div>
 </section>
 <section v-if="selected" class="sb-work-detail" aria-label="作品详情"><BackButton :to="returnLabel||'订阅列表'" @click="back"/><header class="sb-work-header"><MediaCover :src="selected.poster" :type="selected.media_type"/><div class="sb-work-title"><h2>{{selected.title||'正在读取作品…'}}</h2><small>{{selected.year}} · {{selected.media_type}}{{selected.season!=null?' · 第 '+selected.season+' 季':''}} · {{stateLabel(selected.state)}}</small></div><div v-if="detail" class="sb-work-actions"><VBtn v-if="['ACTIVE','PASSIVE','PENDING'].includes(selected.state)" variant="text" :disabled="!!detailError||detailLoading||!!status.error.value" @click="confirm('pause')">暂停追踪</VBtn><VBtn v-if="selected.state==='PAUSED'" variant="text" :disabled="!!detailError||detailLoading||!!status.error.value" @click="confirm('resume')">恢复追踪</VBtn><VBtn variant="text" :disabled="detailLoading" @click="choose(selected,false)">刷新</VBtn><VBtn v-if="selected.native_id&&!['RELEASED_NATIVE','RELEASING'].includes(selected.state)" variant="text" :disabled="detailLoading||!!detailError||!!status.error.value" @click="release">交还 MP</VBtn></div></header>
  <p v-if="detailLoading&&!detail" role="status">正在读取分集与版本信息…</p><p v-if="detailError" class="sb-error" role="alert">{{detailError}} 详情可能已过期，暂不可操作。 <VBtn variant="text" :disabled="detailLoading" @click="choose(selected,false)">重新读取</VBtn></p>
  <template v-if="detail"><div v-if="currentPlan" class="sb-work-context"><VBtn variant="text" @click="editContext('policy')">策略：{{status.current.value?.config.policy.bindings[currentPlan.category_id]||'未选择'}}</VBtn><VBtn variant="text" @click="editContext('plans')">方案：{{currentPlan.display_name||currentPlan.id}}</VBtn></div>

   <nav class="sb-nav" aria-label="作品详情内容"><button v-for="[key,title] in [['versions','分集与版本'],['candidates','候选比较'],['history','处理记录']]" :key="key" :aria-current="detailTab===key" @click="showDetailTab(key)">{{title}}</button></nav><section v-show="detailTab==='versions'"><div class="sb-quick-filters" role="group" aria-label="分集状态筛选"><button v-for="[key,title] in [['','全部分集'],['processing','处理中'],['attention','需核对分集']]" :key="key" type="button" :aria-pressed="unitFilter===key" @click="filterUnits(key)">{{title}}</button></div><p v-if="!detail.units.total" class="sb-muted">{{unitFilter?'此作品没有符合当前筛选的分集。':'集数范围尚未确认，等待资源或档案信息。'}}</p>
   <details class="sb-help sb-version-help"><summary>如何阅读版本对比</summary><p>改善的规格会高亮显示，偏好降低的规格会单独提示。打开对应集数的版本记录，可以查看来源与文件。</p></details>
   <UnitProgress v-for="unit in detail.units.items" :key="unit.target_key" :unit="unit" :health="{...status.health.value,paused:selected.state==='PAUSED'}">
    <template #actions><ReconcileButton v-for="action in unit.processing?.reconcile||[]" :key="action.object_id" :action="action" :client="client" :status="status" :unknown="unit.processing?.next_step==='RECONCILE'" :disabled="detailLoading||!!detailError" @checked="choose(selected,false)"/><VBtn v-if="unit.processing?.candidate_key" variant="text" :disabled="detailLoading||!!detailError||!!status.error.value" @click="openReplacement(unit)">更换资源</VBtn></template><template #archive><VersionHistory :target="unit.target_key" :version="detail" :count="unit.version_count" :client="client" :status="status" :title="selected.title+' · '+unitLabel(unit)" @action="(...args)=>emit('action',...args)"/></template>
    <VBtn v-if="opportunity" variant="tonal" :disabled="detailLoading||!!detailError||!!status.error.value" @click="immediate(unit)">{{selected.media_type==='电影'?'立即检查版本':'立即检查此集'}}</VBtn>
   </UnitProgress>
   <div v-if="detail.units.total>25" class="sb-pagination"><VBtn :disabled="detailLoading||unitOffset===0" @click="unitOffset=Math.max(0,unitOffset-25);choose(selected,false)">上页分集</VBtn><span>第 {{Math.floor(unitOffset/25)+1}} 页</span><VBtn :disabled="detailLoading||detail.units.next_offset===null" @click="unitOffset=detail.units.next_offset;choose(selected,false)">下页分集</VBtn></div>
   </section><section v-if="detailTab==='history'" class="sb-form-section"><p v-if="detailAuxLoading.observations" role="status">候选观察记录正在读取…</p><p v-if="detailErrors.observations" class="sb-warning">候选观察记录暂时无法读取。<span v-if="detailStale.observations"> 显示上次读取结果。</span> <VBtn variant="text" @click="loadAux('observations')">重新读取候选观察</VBtn></p><template v-if="detail.observations?.items?.length"><h3>候选观察记录</h3><p v-for="o in detail.observations.items" :key="o.id" class="sb-muted">{{unitLabel(o.data)}} · 比较截止 {{dateText(o.data.deadline)}} · 最后改善 {{dateText(o.data.last_better)}}</p></template></section>
   <section v-if="detailTab==='candidates'"><p v-if="detailAuxLoading.decisions" role="status">候选比较正在读取…</p><p v-if="detailErrors.decisions" class="sb-warning">候选比较暂时无法读取。<span v-if="detailStale.decisions"> 显示上次读取结果。</span> <VBtn variant="text" @click="loadAux('decisions')">重新读取候选比较</VBtn></p><p v-else-if="!detailAuxLoading.decisions&&!detail.decisions?.items?.length" class="sb-muted">还没有候选比较记录。</p><h3>候选比较记录</h3><CandidateDecision v-for="d in detail.decisions?.items||[]" :key="d.id" :decision="d" :client="client"/><div v-if="detail.decisions?.total>5" class="sb-pagination"><VBtn :disabled="detailLoading||!decisionOffset" @click="decisionOffset-=5;loadAux('decisions')">上一页比较</VBtn><VBtn :disabled="detailLoading||detail.decisions.next_offset===null" @click="decisionOffset=detail.decisions.next_offset;loadAux('decisions')">下一页比较</VBtn></div><p v-if="detailAuxLoading.exclusions" role="status">资源排除记录正在读取…</p><p v-if="detailErrors.exclusions" class="sb-warning">资源排除记录暂时无法读取。<span v-if="detailStale.exclusions"> 显示上次读取结果。</span> <VBtn variant="text" @click="loadAux('exclusions')">重新读取排除记录</VBtn></p><section v-if="detail.exclusions?.total" class="sb-form-section"><h3>已排除的资源 · {{detail.exclusions.total}}</h3><div v-for="row in detail.exclusions.items||[]" :key="row.id" class="sb-binding-row"><span><strong class="sb-block">{{row.data.candidate_title||'资源名称暂不可用'}}</strong>{{row.data.criteria?.targets?.map(target_key=>unitLabel({target_key})).join('、')}}<small class="sb-block">{{reasonText(row.data.reason)||'手动排除'}} · {{row.data.expires_at?'截止 '+dateText(row.data.expires_at):'直到手动撤销'}}</small></span><VBtn variant="text" :disabled="detailLoading||!!detailError" @click="revoke(row)">允许重新选择</VBtn></div><div v-if="detail.exclusions.total>10" class="sb-pagination"><VBtn :disabled="detailLoading||!exclusionOffset" @click="exclusionOffset-=10;loadAux('exclusions')">上一页排除</VBtn><VBtn :disabled="detailLoading||detail.exclusions.next_offset===null" @click="exclusionOffset=detail.exclusions.next_offset;loadAux('exclusions')">下一页排除</VBtn></div></section></section>
   <section v-if="detailTab==='history'"><p v-if="detail.effective?.effective?.template?.id">下载与入库方案：{{detail.effective.effective.template.display_name||detail.effective.effective.template.id}}</p><p v-if="detail.lifecycle?.expires_at">自动升级期限至 {{dateText(detail.lifecycle.expires_at)}}</p><h3>最近处理计划</h3><p v-if="detailAuxLoading.plans" role="status">处理计划正在读取…</p><p v-if="detailErrors.plans" class="sb-warning">处理计划暂时无法读取。<span v-if="detailStale.plans"> 显示上次读取结果。</span> <VBtn variant="text" @click="loadAux('plans')">重新读取处理计划</VBtn></p><p v-else-if="!detailAuxLoading.plans&&!detail.plans?.items?.length" class="sb-muted">暂无处理计划。</p><p v-for="plan in detail.plans?.items||[]" :key="plan.id">{{stateLabel(plan.state)}} · 最后记录阶段：{{stateLabel(plan.data?.transfer_phase)}} <small>{{dateText(plan.data?.created_at)}}</small></p><div v-if="detail.plans?.total>5" class="sb-pagination"><VBtn variant="text" :disabled="detailLoading||!planOffset" @click="planOffset-=5;loadAux('plans')">较新计划</VBtn><VBtn variant="text" :disabled="detailLoading||detail.plans.next_offset===null" @click="planOffset=detail.plans.next_offset;loadAux('plans')">更早计划</VBtn></div><div class="sb-actions"><VBtn variant="text" @click="showDetailTab('candidates')">查看候选比较</VBtn><VBtn variant="text" @click="showDetailTab('versions')">查看分集版本</VBtn></div><p class="sb-muted">在各集详情中打开“全部版本记录”，查看这集的在库历史。</p></section>
  </template>
 </section></div>
 <v-dialog :model-value="adopting" max-width="860" persistent @update:model-value="adopting=$event"><AdoptSubscription v-if="adopting" :api="api" :client="client" :status="status" @close="adopting=false" @adopted="adopted"/></v-dialog>
<v-dialog :model-value="!!replacement" max-width="760" @update:model-value="value=>{if(!value){replacementSequence++;replacement=null}}"><section v-if="replacement" class="sb-root sb-dialog"><header class="sb-heading"><div><h2>更换{{selected.media_type==='电影'?'影片':'此集'}}资源</h2><p>{{selected.title}} · {{unitLabel(replacement)}}</p></div><VBtn variant="text" @click="replacementSequence++;replacement=null">关闭</VBtn></header><p>选择一条此前比较通过的资源，确认时会按当前策略和在库版本复核；也可以排除当前资源后交由系统重新寻找。</p><p v-if="replacementBusy" role="status">正在读取可选资源…</p><p v-if="replacementError" class="sb-error" role="alert">{{replacementError}}</p><div class="sb-replacement-list"><button v-for="row in replacementRows" :key="row.decision_id+'-'+row.plan_digest" @click="selectCandidate(row)"><span><strong>{{row.title}}</strong><small>{{reasonText(row.change?.reason)||'此前比较通过'}} · 影响 {{row.affected_targets.map(target_key=>unitLabel({target_key})).join('、')}}</small><small v-if="row.shared_files">包含覆盖多集的共享文件，确认页会列出完整范围。</small></span><span>选择</span></button></div><p v-if="replacementPage&&!replacementRows.length&&replacementPage.next_offset===null" class="sb-muted">已检查完当前可查询范围，确实没有其他可选资源。</p><VBtn v-if="replacementPage&&replacementPage.next_offset!==null" variant="text" :disabled="replacementBusy" @click="readReplacement(replacementPage.next_offset)">继续查看候选</VBtn><VBtn variant="tonal" :disabled="replacementBusy||!!replacementError" @click="autoChange">排除当前资源并自动重搜</VBtn></section></v-dialog>
<v-dialog :model-value="!!confirmation" max-width="520" persistent><section v-if="confirmation" class="sb-root sb-dialog"><h2>{{confirmation.action==='pause'?'暂停追踪':'恢复追踪'}} · {{confirmation.task.title}}</h2><p>{{confirmation.action==='pause'?'暂停新的追踪处理，保留现有下载任务和文件。':'按已保存范围恢复追踪，保留原观察期限；如有在途计划或未核实发布结果，必须先对账。'}}</p><p v-if="actionError" role="alert" class="sb-error">{{actionError}}</p><div class="sb-actions"><VBtn color="primary" :disabled="actionBusy||attempted" @click="execute">{{actionBusy?'正在提交…':'确认'}}</VBtn><VBtn variant="text" :disabled="actionBusy" @click="confirmation=null">关闭</VBtn></div></section></v-dialog>
</section></template>
