<script setup>
import {ref} from 'vue';import {useRead} from './read.mjs';import {stateLabel,fileStateLabel,dateText,reasonText,formatBytes,deliveryNext} from './media.mjs';import Record from './Record.vue';
import {usePanelPosition} from './panel.mjs';
const position=usePanelPosition();
const props=defineProps({client:Object,status:Object});const emit=defineEmits(['action','diagnostic']);
const offset=ref(0),state=ref(''),selected=ref(null),detailOffset=ref(0);
const {data,error,busy,refresh}=useRead(async signal=>{const page=await props.client.get('/delivery/bundles',{params:{limit:20,offset:offset.value,...(state.value?{state:state.value}:{})},signal});const detail=selected.value?await props.client.get('/delivery/bundles/'+encodeURIComponent(selected.value),{params:{limit:25,offset:detailOffset.value},signal}):null;return {page,detail}},15000);
function select(id,event){if(id){position.remember(event);selected.value=id;position.top()}else{selected.value=null;position.restore()}detailOffset.value=0;refresh()}
function action(name,path,extra,description){const b=data.value.detail.bundle;emit('action',[name,path],{bundle_id:b.id,revision:b.revision,expected_state:b.state,...extra,_bound:true,_label:b.title||'当前交付',_description:description})}
const unsettled=b=>['UNKNOWN','PUBLISHING','PUBLISH_OUTCOME_UNKNOWN'].includes(b.state);
defineExpose({load:refresh});
</script>
<template><section aria-label="传输与待处理"><header v-if="!selected" class="sb-heading"><div><h2>传输与待处理</h2></div><VBtn variant="tonal" :disabled="busy" @click="refresh">刷新进度</VBtn></header>
 <div v-show="!selected" class="sb-search"><label>处理阶段<select v-model="state" @change="offset=0;select(null)"><option value="">全部阶段</option><option value="WAITING">等待条件</option><option value="UPLOADING">正在上传</option><option value="UNKNOWN">结果未知</option><option value="PUBLISH_OUTCOME_UNKNOWN">发布待核实</option><option value="WAIT_CONSUMER">等待整理与媒体库确认</option><option value="CONFIRMED">已确认交付</option><option value="ABANDONED">已取消</option></select></label></div>
 <p v-if="error" role="alert" class="sb-error">{{error}} <span v-if="data">以下为上次读取结果，操作暂不可用。</span></p><p v-if="busy&&!data" role="status">正在读取交付进度…</p>
 <template v-if="data"><div class="sb-workspace"><section v-show="!selected" class="sb-subscription-list"><div v-if="!data.page.items.length" class="sb-empty"><h3>当前没有{{state?'符合筛选条件的':''}}交付</h3><p>订阅选中资源并完成前置处理后，交付会显示在这里。</p></div><div v-if="data.page.items.length" class="sb-list-columns sb-transfer-columns" aria-hidden="true"><span>作品与文件</span><span>处理状态</span><span>下一步</span></div><button v-for="b in data.page.items" :key="b.id" class="sb-subscription-card sb-transfer-row" :aria-pressed="selected===b.id" @click="select(b.id,$event)"><span class="sb-card-copy"><strong>{{b.title||'交付文件组'}}</strong><small>{{b.file_count}} 个文件 · {{b.rule_id}}</small></span><span class="sb-row-cell"><span class="sb-state" :data-state="b.state">{{stateLabel(b.state)}}</span><small>{{reasonText(b.reason)}}</small></span><span class="sb-row-cell"><span>{{deliveryNext(b,status.health.value)}}</span><small>查看详情 ›</small></span></button>
 <div v-if="data.page.total" class="sb-pagination"><VBtn :disabled="busy||!offset" @click="offset=Math.max(0,offset-20);refresh()">上一页</VBtn><span>共 {{data.page.total}} 组</span><VBtn :disabled="busy||data.page.next_offset===null" @click="offset=data.page.next_offset;refresh()">下一页</VBtn></div></section>
 <section v-if="selected" class="sb-work-detail"><header class="sb-heading sb-detail-header"><h2>{{data.detail?.bundle.title||'当前交付'}}</h2><VBtn variant="text" @click="select(null)">返回交付列表</VBtn></header><template v-if="data.detail&&data.detail.bundle.id===selected"><span class="sb-state" :data-state="data.detail.bundle.state">{{stateLabel(data.detail.bundle.state)}}</span><p>{{reasonText(data.detail.bundle.reason)}}</p>
 <p class="sb-muted">{{data.detail.bundle.consumer_pending===false?'整理已有确认；当前媒体库可用性以档案扫描为准。':data.detail.bundle.consumer_pending?'已交付，等待 Symedia 整理及媒体库确认。':'尚未取得整理与媒体库确认。'}}</p>
 <div class="sb-actions"><VBtn v-if="unsettled(data.detail.bundle)" color="primary" :disabled="busy||!!error" @click="action('核对交付状态','/health/reconcile',{component:'delivery',object_id:data.detail.bundle.id,revision:String(data.detail.bundle.revision)},'核对已有外部操作的实际结果，不把未知结果当作未执行。')">核对实际状态</VBtn><VBtn v-else-if="['PREPARED','UPLOADING','WAITING','BLOCKED','REMOTE_VERIFIED','WAIT_CONSUMER'].includes(data.detail.bundle.state)" color="primary" :disabled="busy||!!error" @click="action('继续当前交付阶段','/delivery/{bundle_id}/retry',{phase:data.detail.bundle.state==='WAIT_CONSUMER'?'consumer':data.detail.bundle.state==='REMOTE_VERIFIED'?'publish':'transfer'},'仅尝试当前阶段，服务端会重新校验交付状态和权限。')">继续处理</VBtn><VBtn v-if="data.detail.bundle.state!=='ABANDONED'" variant="text" :disabled="busy||!!error" @click="action('取消交付','/delivery/{bundle_id}/cancel/preview',{reason:'ADMIN_CANCEL'},'取消当前交付，保留下载器任务与数据；未知外部结果或共享引用可能阻止取消。')">取消交付</VBtn></div>
 <h3>文件与字幕</h3><div v-for="f in data.detail.files.items" :key="f.id" class="sb-file-row"><strong>{{f.data.relative_path||f.data.snapshot?.path||'文件 '+f.id}}</strong><span class="sb-muted">{{formatBytes(f.data.size??f.data.snapshot?.size)}} · {{fileStateLabel(f.state)}}</span><span v-if="Number.isFinite(f.data.uploaded_bytes)" class="sb-muted">已传输 {{formatBytes(f.data.uploaded_bytes)}}</span></div>
 <div v-if="data.detail.files.total>25" class="sb-pagination"><VBtn :disabled="busy||!detailOffset" @click="detailOffset-=25;refresh()">上一页文件</VBtn><VBtn :disabled="busy||data.detail.files.next_offset===null" @click="detailOffset=data.detail.files.next_offset;refresh()">下一页文件</VBtn></div>
 <details class="sb-technical"><summary>外部回执与安全清理</summary><p>删除数据需要独立权限及精确范围预览；取消交付不会自动删除。</p><VBtn variant="text" color="error" :disabled="busy||!!error" @click="action('预览交付数据清理','/delivery/{bundle_id}/cleanup/preview',{},'仅按当前规则已授予的权限清理，先核对服务端预览中的路径和保留对象。')">预览可清理对象</VBtn><Record :value="{原因代码:data.detail.bundle.reason,回执:data.detail.receipts,共享引用:data.detail.shared_references,清理:data.detail.cleanup}"/></details>
 </template><p v-else role="status">正在读取此交付的文件与回执…</p></section></div></template>
</section></template>
