<script setup>
import {ref,watch,onBeforeUnmount,useId} from 'vue';import {createReadGate,errorText} from './client.mjs';import {qualitySummary} from './media.mjs';
const props=defineProps({target:String,client:Object,title:String,status:Object,version:Object,count:{type:Number,default:null}}),emit=defineEmits(['action']);
const opened=ref(false),offset=ref(0),data=ref(null),error=ref(''),busy=ref(false),contentId='version-history-'+useId(),gate=createReadGate();
watch(()=>props.target,()=>{gate.begin();opened.value=false;offset.value=0;data.value=null});watch(()=>props.version,()=>{if(opened.value)load()});onBeforeUnmount(()=>gate.close());
async function load(){const read=gate.begin();busy.value=true;error.value='';try{const result=await props.client.get('/archive/targets/'+encodeURIComponent(props.target),{params:{limit:10,offset:offset.value},signal:read.signal});if(read.current())data.value=result}catch(e){if(read.current())error.value=e.status===404||e.response?.status===404?'尚未建立此集的版本档案。':errorText(e)}finally{if(read.current())busy.value=false}}
async function toggle(){opened.value=!opened.value;if(opened.value&&!data.value)await load()}
function invalidate(row){emit('action',['停用此版本记录','/archive/invalidate/preview'],{version_ids:[row.id],reason:'USER_INVALIDATED',_bound:true,_label:props.title,_description:'仅停止将这份版本记录用于质量比较，保留媒体文件。'})}
</script>
<template><section class="sb-version-history"><span v-if="count===0" class="sb-muted">暂无历史版本</span><VBtn v-else variant="text" :aria-expanded="opened" :aria-controls="contentId" @click="toggle">{{opened?'收起版本记录':'查看版本记录'}}{{Number.isInteger(count)?'（'+count+'）':''}}</VBtn><div v-if="opened" :id="contentId" class="sb-version-history-content"><p v-if="busy" role="status">正在读取版本记录…</p><p v-if="error" role="alert">{{error}}<VBtn variant="text" @click="load">重新读取</VBtn></p><template v-if="data"><p v-if="!data.versions.items.length">此集还没有版本记录。</p><article v-for="version in data.versions.items" :key="version.id" class="sb-version-record"><strong>{{qualitySummary(version.data.quality)}}</strong><span>{{version.data.active?'当前有效':'已停用'}} · {{version.data.data.reliable?'文件记录已确认':'文件关联尚未确认'}}</span><p v-if="version.data.data.raw?.title" class="sb-filename">{{version.data.data.raw.title}}</p><VBtn v-if="version.data.active" variant="text" :disabled="busy||!!error||!!status?.error.value" @click="invalidate(version)">停用此版本记录</VBtn></article><div v-if="data.versions.total>10" class="sb-pagination"><VBtn variant="text" :disabled="busy||!offset" @click="offset-=10;load()">上一页版本</VBtn><span>共 {{data.versions.total}} 个版本</span><VBtn variant="text" :disabled="busy||data.versions.next_offset===null" @click="offset=data.versions.next_offset;load()">下一页版本</VBtn></div></template></div></section></template>
